### ISSUE TITLE
Some themes render with wrong fallback color

### ISSUE THREAD

**Issue by octref** [shikijs/shiki#100]
From https://github.com/shikijs/shiki/issues/45#issuecomment-719525100

For a VS Code theme, the canonical way to specify a fallback color should be to include a `settings` key as first property of `tokenColors` with no scope, for example:

https://github.com/arcticicestudio/nord-visual-studio-code/blob/36dac6cae5996995543af99c12e23587028913a5/themes/nord-color-theme.json#L266-L272

Some theme does not do that, and `vscode-textmate` would generate a wrong color map.
I asked vscode-textmate in this case to use `colors['editor.foreground']` and `colors['editor.background']` as a fallback, but was pointed to open an issue in VS Code to fix their themes. I then opened a PR but that was closed: https://github.com/microsoft/vscode/pull/105418

So here we have to do our own logic: If there's no no-scope global setting with fallback colors, we have to manually insert it into the theme so vscode-textmate can tokenize with correct color.

**Comment by vinkla** [comment]
Thanks for fixing this @octref! Keep up the good work 👏
