### ISSUE TITLE
Reorganization proposal

### ISSUE THREAD

**Issue by leafac** [shikijs/shiki#115]
1. Bring https://github.com/shikijs/shiki-latex into https://github.com/shikijs/shiki.
2. Bring https://github.com/leafac/shiki-rehype into https://github.com/shikijs/shiki **OR** invite https://github.com/rsclarke/rehype-shiki into https://github.com/shikijs/shiki (depending on the outcome of https://github.com/rsclarke/rehype-shiki/issues/49).

/cc @octref @orta

**Comment by orta** [comment]
I'm open to bringing both of these in -  @rsclarke I'd love an opinion in https://github.com/rsclarke/rehype-shiki/issues/49 too

**Comment by octref** [comment]
LGTM. Feel free to send the PRs.
What's the pros and cons of monorepo though? I haven't used it extensively to have an opiniong. I know it reduces manual linking you need to do, but it also makes repo larger and more complex.

**Comment by leafac** [comment]
I believe since @octref’s last comment we went with the monorepo approach, right? I see a `packages/` directory in https://github.com/shikijs/shiki/

I’m checking in to let you know that I’m still around and I’ll get to this in the near future…

**Comment by octref** [comment]
@leafac Sure, let's go with the monorepo approach. I'll close this in favor of #58.
