### ISSUE TITLE
SVG Renderer is assuming whitespaces are wider than they should be

### ISSUE THREAD

**Issue by orta** [shikijs/shiki#122]
![Screen Shot 2021-02-03 at 7 48 48 AM](https://user-images.githubusercontent.com/49038/106714977-7be59080-65f4-11eb-8ad8-e1311a06d5b0.png)

I think this is probably a 1.0 blocker

**Comment by octref** [comment]
@antfu Seems to be caused by https://github.com/shikijs/shiki/commit/18bd9849b271134f1d83381e428df3920a4ef86d#diff-bc52054a154d276aa8fde50ba8ed3cd6cf0e7f18713a384b42feeebf68f2273d

I'm guessing it's because you don't have IBM Plex Mono installed. Can you confirm?
If that's the cause, need to find a way to measure fonts correctly without using having installed it.

**Comment by antfu** [comment]
> don't have IBM Plex Mono installed

Yeah, I don't... maybe you can try to build on your local to see if it fixes?

**Comment by octref** [comment]
I did: https://github.com/shikijs/shiki/commit/87344dadcf271d2bc929db56f5cb3d153be553c8, but I need to make sure build works even if the target machine doesn't have the font. Thanks for confirming for me.

**Comment by orta** [comment]
Can deploy to gh-pages on a push, then we don't have to think about it?

**Comment by octref** [comment]
Added a new API to load remote fonts. Also switched to playwright from puppeteer.

```ts
export interface RemoteFontFamily {
  /**
   * Name of the font
   */
  name: string
  /**
   * URL pointing to the CSS that loads the font
   */
  cssURL: string
}

interface SVGRendererOptions {
  /**
   * A monospace font.
   * If using in Node context and the font is not available in the host machine,
   * provide `cssURL` that loads the font remotely.
   * If using in the browser context, make sure the font is available in the webpage.
   *
   * `getSVGRenderer({ fontFamily: 'SF Mono Regular' })`
   * ```js
   * getSVGRenderer({ fontFamily: {
   *   name: 'SF Mono Regular',
   *   cssURL: 'https://fonts.googleapis.com/css2?family=Inconsolata&display=swap'
   * }})
   * ```
   */
  fontFamily: string | RemoteFontFamily
  /**
   * URL of the CSS that loads the `fontFamily` font remotely.
   */
  remoteFontCSSURL?: string
}
```
