### ISSUE TITLE
Get Global Languag/Theme Path Config Value

### ISSUE THREAD

**Issue by benwis** [shikijs/shiki#125]
I'd love to be able to change the import location of all languages and all themes when not in the browser.

Something like useCDN{}, but that works outside of the browser
I'm working with Vercel and need to change the locations of the themes and the language files, but I'd prefer to load all of them.

**Comment by octref** [comment]
Isn't this already available?

```ts
/**
 * Set the route for loading the assets
 * URL should end with `/`
 *
 * For example:
 * ```ts
 * setCDN('https://unpkg.com/shiki/') // use unpkg
 * setCDN('/assets/shiki/') // serve by yourself
 * ```
 */
```

**Comment by renatorib** [comment]
@benwis how are you changing language file locations? I'm trying to deploy next static-rendered to vercel but it bundles all in one serverless function, and language files are not being bundled.

**Comment by octref** [comment]
@renatorib You should move language files to public folder that serves static assets as-is.

**Comment by octref** [comment]
If you still have issue, please open a new one.
