### ISSUE TITLE
Poor highlighting result for cpp code

### ISSUE THREAD

**Issue by Enter-tainer** [shikijs/shiki#127]
Hi, I'm using shiki to highlight code in my website. But I've found that it behaves strangely when highlighting cpp code. Here are the highlighting results(using theme light+):

![image](https://user-images.githubusercontent.com/25521218/107868511-d36ee080-6ebf-11eb-90cb-a5e9e575dace.png)

As you can see, the macro `#include`, and the keyword `for`, `int`, `if` are not properly colored. And the dark blue color of `array` is also pretty suspicious. The comment is not colored, either. Below is the result from vscode(screenshot from my editor) for contrast:

![image](https://user-images.githubusercontent.com/25521218/107868568-54c67300-6ec0-11eb-8a7c-0ecddaa98c0b.png)

I've also tried other theme like dark+ and nord, but the problem still didn't disappear.

### Reproduction guide

Install the latest shiki, and use following code:

```js
const fs = require('fs')
const shiki = require('shiki')

shiki
  .getHighlighter({
    theme: 'light-plus'
  })
  .then((highlighter) => {
    const html = highlighter.codeToHtml(
      fs.readFileSync('test.cpp', 'utf-8'),
      'cpp'
    )

    const out = `
<title>Shiki</title>
${html}`

    fs.writeFileSync('index.html', out.trim())

    console.log('done highlighting index.js')
  })

```

Example cpp code:

```cpp
#include <iostream>
using namespace std;

int main() {
  int array[100] = {0};
  for (int i = 0; i < 100; ++i) {
    if (array[i] == 0) {
      // do some thing...
    }
  }
}

```

**Comment by Enter-tainer** [comment]
Maybe I just get hang of this bug. It seems that the grammar file of cpp is incorrect, the file `cpp.tmLanguage.json` has scope name `  "scopeName": "source.cpp.embedded.macro"` instead of `source.cpp`. I also found that the [upstream](https://github.com/jeff-hykin/cpp-textmate-grammar/tree/master/syntaxes) actually provides two grammar file for cpp, but only one of them are used in shiki.

**Comment by Enter-tainer** [comment]
OK, after adding the correct grammar file, it now works. I'll send a pr later.

![image](https://user-images.githubusercontent.com/25521218/107960898-2770e680-6fe0-11eb-9b74-2065e32ed811.png)

**Comment by Enter-tainer** [comment]
```
normalized /home/mgt/project/shiki/tmp/grammars/cpp.embedded.macro.tmLanguage.json to /home/mgt/project/shiki/tmp/grammars/cpp.tmLanguage.json
normalized /home/mgt/project/shiki/tmp/grammars/cpp.tmLanguage.json to /home/mgt/project/shiki/tmp/grammars/cpp.tmLanguage.json
```

seems that shiki does wrong normalization, which preventa the coexistence of these two files.

```ts
    const kebabName = newName || kebabCase(newJson.name.toLowerCase())
    const newPath = path.resolve(THEME_FOLDER_PATH, `${kebabName}.json`)
```

shiki choose the name of the grammar file for normalization, however, these two file are of the same name "C++". 

Dose anyone have any idea? May I just add a simple `if` to skip normalization for cpp grammar, or some better solutions?

**Comment by octref** [comment]
I reorganized the pulling scripts so the workaround is no longer needed.
