### ISSUE TITLE
Include samples

### ISSUE THREAD

**Issue by octref** [shikijs/shiki#148]
We should have a sample file for each language, for playground/illustration purpose.

When I run this script:

```ts
const shiki = require('shiki')

shiki.BUNDLED_LANGUAGES.forEach(l => {
  if (!l.samplePath) {
    console.log(l.id)
  }
})
```

I'm getting this:

<details>
  <summary>Output</summary>

```
abap
actionscript-3
ada
apex
applescript
asm
awk
bat
clojure
cobol
coffee
cpp
crystal
csharp
d
dart
diff
docker
elixir
elm
erb
erlang
fsharp
git-commit
git-rebase
gnuplot
graphql
groovy
hack
haml
handlebars
haskell
hcl
hlsl
ini
jinja-html
json
jsonc
jsonnet
jsx
julia
kotlin
latex
less
lisp
logo
lua
make
markdown
matlab
mdx
nix
objective-c
objective-cpp
ocaml
pascal
perl
php
plsql
postcss
powershell
prolog
pug
puppet
purescript
r
raku
razor
rust
sas
sass
scala
scheme
scss
shaderlab
shellscript
smalltalk
sql
ssh-config
stylus
svelte
swift
tcl
toml
typescript
vb
viml
vue
wasm
wenyan
xml
xsl
yaml
```

</details>

We need to have sample for each of them. To do this, add `<id>.sample` to `packages/shiki/samples` and run `yarn update:grammars`.

The requirement for adding any new language will be including a sample, see: https://github.com/shikijs/shiki/blob/master/docs/languages.md#adding-grammar

**Comment by Jadhielv** [comment]
I would like to help you with this @octref

**Comment by octref** [comment]
@Jadhielv Thanks! Feel free to send in PRs.

**Comment by GitMensch** [comment]
`<id>.sample` only allows for one, what about supporting (additional, otherwise that's a one-time rename of all existing examples) `<id>.<num>.sample`? This can then also be used to add a third dropdown in the playground to choose one, but even without that an _internal_ handling of multiple source files seems useful.
