### ISSUE TITLE
Is it possible to keep font-weight?

### ISSUE THREAD

**Issue by usernamehw** [shikijs/shiki#15]
Sample from custom theme for `CSS` language:
```json
{
	"scope": "keyword.other.important",
	"settings": {
		"fontStyle": "bold",
		"foreground": "#dd4a68"
	}
},
```
The color `#dd4a68` is applied properly, but not the font-weight.

**Comment by usernamehw** [comment]
It could be optional:

```js
shiki.getHighlighter({
	preserveFontStyle: boolean
})
```

**Comment by octref** [comment]
Now all font styles will be automatically preserved. Sorry it took long.
