### ISSUE TITLE
How to add custom class on html tag code?

### ISSUE THREAD

**Issue by irfan-maulana-tkp** [shikijs/shiki#150]
Currently when we use `codeToHtml`, shiki will produce tag:

```html
<pre class="shiki">
 <code>
  ....
 </code>
</pre>
```

How if we want to insert any custom class to the `<code>` tag?

```html
<pre class="shiki">
 <code class="custom-class">
  ....
 </code>
</pre>
```

**Comment by octref** [comment]
Use `shiki.codeToThemedTokens`, and write your own renderer. The bundled HTML renderer is quite simple: https://github.com/shikijs/shiki/blob/master/packages/shiki/src/renderer.ts
