### ISSUE TITLE
LaTeX comment should not get highlighted

### ISSUE THREAD

**Issue by yzhang-gh** [shikijs/shiki#152]
It is strange to see LaTeX comment also gets highlighted

![image](https://user-images.githubusercontent.com/7588612/116051883-ab63e080-a6ab-11eb-8aef-7d21cccac842.png)

**Comment by yzhang-gh** [comment]
An interesting fact: it seems that comment is not "recognized" at all.

![image](https://user-images.githubusercontent.com/7588612/116818145-5db01200-ab9c-11eb-85bc-c86b1fb250dc.png)

For comparison

![image](https://user-images.githubusercontent.com/7588612/116818186-a7006180-ab9c-11eb-8c70-425e54638c05.png)

**Comment by octref** [comment]
Good catch. I guess the issue has something to do with onigasm. When I switch to https://github.com/microsoft/vscode-oniguruma this bug is fixed, so I'll just do the upgrade.

**Comment by octref** [comment]
The issue is that LaTeX grammar embeds TeX grammar, but I didn't include TeX grammar.

**Comment by yzhang-gh** [comment]
Not sure what is the difference but

https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/TeX.tmLanguage.json
https://github.com/James-Yu/LaTeX-Workshop/blob/master/syntax/LaTeX.tmLanguage.json

might be helpful.

**Comment by octref** [comment]
I did some refactoring and added an `embeddedLang` property to each language. `latex` would require `tex` to be loaded upfront. After that the highlighting works properly for me: 

![image](https://user-images.githubusercontent.com/4033249/123066411-a371b400-d442-11eb-9925-5fdb6e8a580b.png)

**Comment by yzhang-gh** [comment]
Many thanks!
