### ISSUE TITLE
Synchronous API option optimized for tree-shaking

### ISSUE THREAD

**Issue by jasonkuhrt** [shikijs/shiki#160]
The current API forces async on the consumer. I tracked it back to https://github.com/shikijs/shiki/blob/0f1739944c6047ba09fca4a2000992ba149aff7f/packages/shiki/src/loader.ts#L108 then stopped. Not sure I understand all the reasons for async.

Anyways it would be great if instead of (this is extracted from real world code):

```ts
// NOTE needs to pre-load language for Next.js to actually bundle it
const theme = require('shiki/themes/github-light.json')
const grammar = require('shiki/languages/tsx.tmLanguage.json')

/**
 * Enhance the EPD with highlighted JSDoc example blocks.
 *
 * Note: This mutates the given EPD.
 */
export async function highlightJSDocExamples(eid: ExtractedInterfaceDataEnvelop): Promise<void> {
  const highlighter = await Shiki.getHighlighter({
    theme,
    langs: [
      {
        id: 'tsx',
        scopeName: 'source.tsx',
        grammar,
      },
    ],
  })

```

we could do:

```ts
import * as Shiki from 'shiki'
/**
 * Enhance the EPD with highlighted JSDoc example blocks.
 *
 * Note: This mutates the given EPD.
 */
export function highlightJSDocExamples(eid: ExtractedInterfaceDataEnvelop): void {
  const highlighter = Shiki.getHighlighter({
    theme: Shiki.Theme.GithubLight,
    langs: [
      {
        id: 'tsx',
        scopeName: 'source.tsx',
        grammar: Shiki.Langauge.tsx,
      },
    ],
  })

```

During build the selected language/theme would be brought in and everything unused tree-shaken away.

We have a large codebase that is 99.9999% pure but because of this need to make it async (or split our API in awkward multi-step ways that aren't ideal for us).

**Comment by orta** [comment]
I believe this is because the syntax highlighter runs in WASM and to my knowledge there isn't a way to turn that into synchronous code

**Comment by jasonkuhrt** [comment]
Makes sense then, I have no idea how or if that could be worked around. If it cannot be, then I guess this issue should be closed.
