### ISSUE TITLE
Isomorphic for browser support

### ISSUE THREAD

**Issue by jasonkuhrt** [shikijs/shiki#161]
It would be great for our use-case to have browser support for shiki.

There is currently a 'fs' dependency and maybe more that keeps shiki from working in the browser.

**Comment by jasonkuhrt** [comment]
The issue came up in the context of a Next.js app. I will share more details the next time we encounter this.

**Comment by octref** [comment]
Duplicate of #138, see https://github.com/shikijs/shiki/issues/138#issuecomment-792421710

I think there's no issue, it's just you need to use Shiki in `getStaticProps`.
