### ISSUE TITLE
Help - ERROR Can't find `nord.json`

### ISSUE THREAD

**Issue by babakfp** [shikijs/shiki#168]
No matter what I do, it doesn't work.
Also, we need a default value for `theme` in `getHighlighter({ theme: 'nord' })`.

```js
import * as shiki from 'shiki'

// ...

return shiki
  .getHighlighter({ theme: 'nord' })
  .then(highlighter => highlighter.codeToHtml(source, lang)) // lang: 'html'
  .catch(err => console.log(err))
```

```html
// code:
<p class="text-gray-600">html code</p>
```

```
[Error: ENOENT: no such file or directory, open 'C:\Users\babak\Desktop\projects\front\__sapper__\dev\themes\nord.json'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\babak\\Desktop\\projects\\front\\__sapper__\\dev\\themes\\nord.json'
}
```

**Comment by octref** [comment]
If you are using some sort of bundlers, you need to copy `node_modules/shiki/themes/nord.json` to your frontend assets folder.

**Comment by babakfp** [comment]
I moved Shiki from `devDependencies` to `dependencies` and it fixed.

Now I have another problem. Can you check it out, please? I really want to use this package and it's being 5 days that I'm having this problem (awaiting the promise doesn’t work). [Repo](https://github.com/babakfp/sv-docs.git)
`src/routes/docs/_sections.js` this is the file that I use Shiki with [MarkedJS](https://github.com/markedjs/marked)
