### ISSUE TITLE
How can I load new languages into Shiki?

### ISSUE THREAD

**Issue by pouyakary** [shikijs/shiki#179]
I have figured it out that to load a language you must put the file in the `node_modules/shiki/languages` and then in the `node_modules/shiki/dist/index.js` I can add to the list. But isn't there any way to load it in the setup? I have only found a doc in the repo that explains you can add a new language to the build script but what if I'm interested in languages that you may not want me to put there for everyone?

**Comment by orta** [comment]
We should document this inside this repo ( I did some light docs for it in shiki-twoslash)

**Comment by pouyakary** [comment]
would be really cool. Shiki really needs some good docs. I'm writing a renderer for it, so if you wanted me to, I can contribute a doc for making a renderer.

**Comment by orta** [comment]
Sure thing, having built one too I can edit and help get it in 👍🏻

**Comment by muenzpraeger** [comment]
@pouyakary Is that [solved by this doc](https://github.com/shikijs/shiki/blob/main/docs/languages.md#supporting-your-own-languages-with-shiki)?
