### ISSUE TITLE
Highlight code fragments

### ISSUE THREAD

**Issue by MatTheCat** [shikijs/shiki#181]
Sorry for the somewhat vague title but I’m not sure how to phrase it.

I tested shiki on the following CSS:

```css
aspect-ratio: auto 200 / 100;
```

As it is not valid as a CSS file I got wrong styles because the grammar says `aspect-ratio: auto 200` is a selector and `aspect-ratio` a custom tag (`/ 100` is “just CSS”):

![higlighting-wrong](https://user-images.githubusercontent.com/1898254/127504504-52743dad-b340-443f-9c7a-476adb4bd944.png)

Here you can see the result in the context of a valid CSS file:
![higlighting-right](https://user-images.githubusercontent.com/1898254/127504518-8c174081-ee0e-4f99-b8a9-06b598eec213.png)

Is there a way to handle this case?

**Comment by orta** [comment]
Yes and no - To get accurate syntax highlighting Shiki needs to be able to have the full context, so something like

````
```css
img {
  aspect-ratio: x y z
}
```
````

Then you need to have a way to chop up the file into a smaller cut:

````
```css {2}
img {
  aspect-ratio: x y z
}
```
````

_that_ level of abstraction isn't shiki level, but Shiki-remark or whatever (for example shiki-twoslash supports code like:

````
```ts twoslash
const a = "123"
// ---cut---
const b = a
```
````

And it would know to only show the line with `b`

**Comment by MatTheCat** [comment]
> you need to have a way to chop up the file into a smaller cut

I'll go that way, thanks!
