### ISSUE TITLE
Requires yarn but does not include yarn as a developer dependency

### ISSUE THREAD

**Issue by StoneCypher** [shikijs/shiki#182]
```
$ npm run build

> build
> lerna run build --include-dependencies

lerna notice cli v3.22.1
lerna notice filter including dependencies
lerna info Executing command in 2 packages: "yarn run build"
lerna ERR! yarn run build exited 2 in 'shiki'
lerna ERR! yarn run build stderr:
'yarn' is not recognized as an internal or external command,
operable program or batch file.

lerna ERR! yarn run build exited 2 in 'shiki'
```

**Comment by antfu** [comment]
I don't think this is needed as it suppose to be install globally one the user land

**Comment by StoneCypher** [comment]
this is the reason i could not build

most people will not globally install yarn to use your library.  it's not a common or wanted tool, and its use is on the extreme decline

you should not expect to modify other peoples' global tool state.  this is a bug

**Comment by StoneCypher** [comment]
Anyway, I removed the fix for yarn not working outside of your home computer, at your request.

If you expect your users to modify their global toolchain to be able to build your library (which is completely unnecessary and breaks their ability to build other things,) you should mention it in your documentation.  I had to debug why your build didn't work, because you expected me to have dangerous and uncommon tools installed globally.

I hope you reconsider.  Most people won't debug your build; they'll just switch to a highlighter that works
