### ISSUE TITLE
yarn.lock is not committed

### ISSUE THREAD

**Issue by StoneCypher** [shikijs/shiki#183]
Quoting [the original author's blog](https://classic.yarnpkg.com/blog/2016/11/24/lockfiles-for-all/):

> Lockfiles should be committed on all projects

**Comment by antfu** [comment]
I think we did https://github.com/shikijs/shiki/blob/master/yarn.lock

**Comment by StoneCypher** [comment]
It's not in the NPM repository.  This shouldn't be closed

**Comment by antfu** [comment]
Locks should never goes to NPM

**Comment by StoneCypher** [comment]
> Lock should never goes to NPM

This is incorrect.  Lock is required to go to NPM.  The purpose of the lock file cannot exist without that.  This misses the core concept of the lockfile.

If the lockfile isn't on npm, ***what is the downstream user checking against?***  What's it even for?

I already gave you the manual page explaining this.  Your NPM score is being severely harmed because you're refusing to do what the manual says you're expected to do.

**Comment by StoneCypher** [comment]
It seems like you're not willing to do what the manual and platform require, so I removed the bugfixes from the PR, as you requested

**Comment by StoneCypher** [comment]
Anyway, I removed it from the PR, at your request
