### ISSUE TITLE
package-lock.json is not committed

### ISSUE THREAD

**Issue by StoneCypher** [shikijs/shiki#184]
Quoting [the manual](https://nodejs.dev/learn/the-package-lock-json-file):

> The package-lock.json file needs to be committed to your Git repository, so it can be fetched by other people, if the project is public or you have collaborators, or if you use Git as a source for deployments.

**Comment by antfu** [comment]
we are using yarn, why would we need this?

**Comment by StoneCypher** [comment]
because it's a requirement for node to work correctly, and more than 90% of your users aren't using yarn

**Comment by StoneCypher** [comment]
also because the package is hard-incorrect, as the manual quoted said, until it's in there

this opens up supply chain injection attacks, and since you're used by the standard typescript tooling, that's actually pretty serious
