### ISSUE TITLE
Display filename

### ISSUE THREAD

**Issue by narduin** [shikijs/shiki#199]
Hello,

Is it possible to display a filename somewhere? I could not find any information on this.

For example in mardown, I'm used to specify a filename with: ` ```javascript[main.js]`

Thanks a lot!

**Comment by octref** [comment]
Hey @narduin, you can use a custom renderer to render the HTML differently:

https://github.com/shikijs/shiki/blob/main/packages/shiki/src/renderer.ts

Or open an issue for https://github.com/antfu/markdown-it-shiki
