### ISSUE TITLE
PHP highlighting not working

### ISSUE THREAD

**Issue by atymic** [shikijs/shiki#21]
Hey 👋 

It seems that PHP code blocks without a `<?php` opening tag don't get colorised correctly.

I've tested and if you add a `<?php` tag, everything starts working correctly.

I guess this is probably an upstream issue?

**Comment by atymic** [comment]
So i've tested in VScode and it works correctly. I found these issues related to it:

https://github.com/Microsoft/vscode/issues/14166
https://github.com/microsoft/vscode/pull/16502

So i'm not sure why it doesn't work here. I think maybe because the actual grammar file is not the same as the one used by vscode?

**Comment by octref** [comment]
Seems working in 0.2.0:

![image](https://user-images.githubusercontent.com/4033249/91259232-abb87e80-e7a0-11ea-8eb8-b38b7adb4ae0.png)

**Comment by D-Marc1** [comment]
You're the man, @octref! Big thanks for all of your hard work in OSS!

**Comment by atymic** [comment]
Awesome job, thanks @octref 👍
