### ISSUE TITLE
css-variables theme doesn't apply variable to <pre> wrapper style attr

### ISSUE THREAD

**Issue by tbeseda** [shikijs/shiki#214]
The new `css-variables` theme is rad 👍🏻  
I'm on `shiki@0.9.9`

I don't think the correct style is being applied to the `<pre>` wrapper

I get
```html
<pre class="shiki" style="background-color: #000002">...
```

I would expect
```html
<pre class="shiki" style="background-color: var(--shiki-token-background)">...
```

My highlighter instance looks like
```js
  const highlighter = await shiki.getHighlighter({
    theme: 'css-variables',
    langs: [
      'bash',
      'javascript',
      'json',
      'powershell',
      'python',
      'ruby',
      'toml',
      'yaml',
      {
        // a custom grammar
      }
    ],
  })
```

The rest of the theme is working as expected.

**Comment by FredKSchott** [comment]
I just ran into this while trying to integrate into Astro as well. I think I have a fix, creating a PR now
