### ISSUE TITLE
[Shiki] no CDN provider found

### ISSUE THREAD

**Issue by jiankafei** [shikijs/shiki#216]
## code
```js
import * as shiki from 'shiki';

const html = ref('');
shiki
  .getHighlighter({
    theme: props.theme,
  })
  .then((highlighter) => {
    html.value = highlighter.codeToHtml(props.content, props.lang);
  })
  .catch(console.warn);
```
## result
```txt
[Shiki] no CDN provider found, use `setCDN()` to specify the CDN for loading the resources before calling `getHighlighter()`
```

**Comment by JounQin** [comment]
Can we load all resources manually? I don't want to provide static resource path but bundled by vite/webpack.

**Comment by songhn233** [comment]
When using vite/webpack, there is a hint of `no CDN provider found`, but npm has already downloaded all `themes` and `languages` files, so setting CDN paths should only be an optional configuration?

**Comment by JounQin** [comment]
cc @octref

**Comment by octref** [comment]
Please provide a minimal, reproducible example. Link to a repo would be great.

**Comment by jiankafei** [comment]
@octref @orta https://codesandbox.io/s/beautiful-swirles-i6fr4

**Comment by octref** [comment]
@jiankafei Your example is showing this for error me: `WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0`

**Comment by boring-plans** [comment]
Agree with @Sparkenstein. For now, as is written in [this file](https://github.com/shikijs/shiki/blob/main/packages/shiki/src/loader.ts), we can load assets by `setCDN('https://unpkg.com/shiki/')` manually. But it's a little bit confusing, why not just consider `node_modules/shiki` as a default assets folder 👻(or maybe set a default CDN)

**Comment by social-uni** [comment]
> 请提供一个最小的、可重现的例子。链接到回购会很棒。

https://stackblitz.com/edit/vitejs-vite-gqv1wz?file=package.json,src%2Fcomponents%2FHelloWorld.vue,index.html&terminal=dev

https://github.com/shikijs/shiki/issues/346#issuecomment-1229402139

**Comment by social-uni** [comment]
> @jiankafei你的例子显示了这个错误我：`WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0`

![image](https://user-images.githubusercontent.com/14007972/187071567-11cc7228-0c25-4167-8289-5385019425c3.png)

**Comment by social-uni** [comment]
https://github.com/shikijs/shiki/issues/246

**Comment by kingyue737** [comment]
If you are using vite, you can serve shiki assets with https://github.com/sapphi-red/vite-plugin-static-copy to make them both available in dev mode and production.

```ts
// vite.config.*
import { viteStaticCopy } from 'vite-plugin-static-copy'

export default {
  plugins: [
    viteStaticCopy({
      targets: [
        {
          src: 'node_modules/shiki',
          dest: '.'
        }
      ]
    })
  ]
}
```

Set CDN to the assets served by yourself before get the `Highlighter`:
```ts
setCDN('/shiki/')
```

**Comment by kossidts** [comment]
I am still having an issue with the following setup: 
```js 
import * as shiki from "shiki";

shiki.setCDN("https://unpkg.com/shiki/");
const highlighter = await shiki.getHighlighter({ theme: "nord" }); // <-- This line is causing the error

const shikiOptions = { lang: "js" };

document.addEventListener("DOMContentLoaded", async event => {
    const $codeBlocks = document.querySelectorAll(".code");
    for (const $codeBlock of $codeBlocks) {
        const content = `console.log('shiki');`; // Read the content of the current block
        const renderedHtml = highlighter.codeToHtml(content, shikiOptions);
        $codeBlock.innerHTML = renderedHtml;
    }
})
```
The error: 
`Uncaught LinkError: WebAssembly.instantiate(): Import #4 module="env" function="setTempRet0" error: function import requires a callable`

Has anyone got shiki running client-side?

**Comment by kingyue737** [comment]
@kossidts   Comments in #382 give several workarounds

**Comment by kossidts** [comment]
Thank you @kingyue737 for the hint. It works by setting both `setCDN` and `setWasm`.  
Just for anyone who wants to know: 

```js
import { getHighlighter, setCDN, setWasm } from "shiki";

document.addEventListener("DOMContentLoaded", async event => {
    // setWasm(new Response(await fetch("https://unpkg.com/shiki/dist/onig.wasm"))); // <- Didn't work although this is recommended per README
    const responseWasm = await fetch("https://unpkg.com/shiki/dist/onig.wasm");
    const wasmArrayBuffer = await responseWasm.arrayBuffer();
    setWasm(wasmArrayBuffer);
    setCDN("https://unpkg.com/shiki/");
    const highlighter = await getHighlighter({ theme: "nord", langs: ["js", "php", "python"] });
    
    // container.innerHTML = highlighter.codeToHtml(someCode, {lang: "js"})
})
```

**Comment by muenzpraeger** [comment]
FWIW, if you want to use the prebuild packages from `unpkg` or `jsDelivr` -> [here's an example](https://github.com/shikijs/shiki/pull/394/files#diff-d929a11d0b1fcdcdbce04b5b197b7c2571f76aa626851c3643e473221f899afc). No need to set CDN or WASM manually.

And thanks for the pointer with the `new Response()` - documentation is [fixed here](https://github.com/shikijs/shiki/pull/395). My advice is to just pass in your example `responseWasm` - that's the response, so it'll get compiled while it's streamed.
