### ISSUE TITLE
Can't load in React Component

### ISSUE THREAD

**Issue by gigara** [shikijs/shiki#224]
Hi,
I'm trying to use Shiki in react component. But it throws an error `magic header not detected`

```
import React from "react";
import onigasm from 'arraybuffer-loader!shiki/dist/onigasm.wasm';

class CodeBlock extends React.Component {

    constructor(props) {
        super(props);
    }

    componentDidMount() {
        async function renderCode() {
            const shiki = await import("shiki");
            shiki.setOnigasmWASM(onigasm)
            const highlighter = await shiki.getHighlighter({
            theme: "dark-plus"
            });
            console.log( highlighter.codeToHtml(
                `console.log('sdsds');`,
                "js"
            ));
        }
        renderCode();
    } 

   render() {
     ...
   }
}

export default CodeBlock;
```

![Screenshot from 2021-09-08 10-51-10](https://user-images.githubusercontent.com/16335290/132451058-6e771aa5-f70a-4654-84a2-23f2eb2e4bbb.png)

What is the correct way to use Shiki in a react class component?

**Comment by octref** [comment]
Does `javascript/auto` work?

https://github.com/pine/arraybuffer-loader/issues/12#issuecomment-390834140
https://github.com/webpack/webpack/issues/7264#issuecomment-388377363

**Comment by lithdew** [comment]
> Does `javascript/auto` work?
> 
> [pine/arraybuffer-loader#12 (comment)](https://github.com/pine/arraybuffer-loader/issues/12#issuecomment-390834140) [webpack/webpack#7264 (comment)](https://github.com/webpack/webpack/issues/7264#issuecomment-388377363)

Does not seem to work with create-react-app - error occurs even if `javascript/auto` is specified.

**Comment by muenzpraeger** [comment]
@gigara Is this still an issue/relevant?

**Comment by gigara** [comment]
Didn't found a solution yet.

**Comment by octref** [comment]
https://github.com/callstack/repack/issues/171

It seems you shouldn't use arraybuffer loader for WASM files. Use a WASM loader.

**Comment by M00TSDNS** [comment]
WASM loaders don't appear to work for onigasm, I found. https://github.com/pine/arraybuffer-loader/issues/12#issuecomment-1432570213
