### ISSUE TITLE
[Help] Can't make it work in SvelteKit

### ISSUE THREAD

**Issue by babakfp** [shikijs/shiki#242]
[SvelteKit Docs](https://kit.svelte.dev/)

### Error logs:
![Screenshot 2021-10-04 134643 (2)](https://user-images.githubusercontent.com/44144724/135834882-e1645666-a08e-4ce3-8b83-56d413d92c1c.png)

### Source code:
![Screenshot 2021-10-04 134717 (3)](https://user-images.githubusercontent.com/44144724/135834911-6bdc6c8d-e255-49c9-a40d-5bc0d64010b9.png)
![Screenshot 2021-10-04 134726 (2)](https://user-images.githubusercontent.com/44144724/135834923-1ebaadcf-84eb-4ffa-9ec1-5c0dd3231ec2.png)

**Comment by rmunn** [comment]
Running this under Svelte-Kit will probably involve calling `setCDN()` with an appropriate location (to load the WASM regex code Shiki uses) before calling `getHighlighter`, slightly complicated by the fact that you would want to call it only once.

My off-the-cuff recommendation, not yet tested, for using Shiki in Svelte-Kit would be to create a readable `$highlighter` store whose initializer calls `setCDN()`, then awaits the result of `getHighlighter()` and sets the store value once getHighlighter() returns. That way the `$highlighter` store will call `setCDN()` exactly once, when the browser first loads your Svelte code. After that, any subsequent use of the `$highlighter` store will just get the highlighter that's already been loaded. The only drawback is that the initial value of the store would be `undefined` so you'd need to check it for truthiness before using it, and display a simple `<pre><code>code-to-render</code></pre>` block if the highlighter is not yet available.

**Comment by babakfp** [comment]
I don't remember much but months ago I made this and it works:
https://github.com/babakfp/svelte-shiki
Don't close the issue. I'll check it later and I'll let you guys know...

**Comment by babakfp** [comment]
https://github.com/markedjs/marked/issues/2122
