### ISSUE TITLE
Shiki takes 6+s to boot in browser

### ISSUE THREAD

**Issue by CyriacBr** [shikijs/shiki#245]
When using shiki in a browser, `getHighlighter` takes between 6 ans 10s (depending on the versions I tried) to boot.

Seems to be related to https://github.com/shikijs/shiki/issues/169 but even on 0.9.11 it is pretty slow.

Reproduction:
```ts
const shiki = await import('shiki');
shiki.setCDN('https://unpkg.com/shiki/');
const shikiInstance = await shiki.getHighlighter({ theme: 'github-dark' });
```

I believe this makes shiki unusable on the browser sadly - no user should have to wait 6s for syntax-highlighting to boot.

**Comment by fengzilong** [comment]
> Can you elaborate on that? I do not understand what you mean.

Expose http service such as `/shiki/highlight` and use with XHR in browser
