### ISSUE TITLE
getHighlighter throwing error in react project

### ISSUE THREAD

**Issue by ishan-krishna** [shikijs/shiki#246]
Pardon my ignorance but I am new here and may not know how to properly post a question. 

I am trying to install and use shiki in my react project. I have installed shiki using yarn and am trying to use `getHighlighter` to highlight my code. But I am facing this weird error 

<img width="558" alt="Screenshot 2021-10-14 at 12 41 54 AM" src="https://user-images.githubusercontent.com/10806671/137198155-e49b2276-0bf5-4fa7-b75f-519f5f972956.png">

Also facing below error:

<img width="264" alt="Screenshot 2021-10-14 at 12 01 06 AM" src="https://user-images.githubusercontent.com/10806671/137192635-8b4e1fe7-7af6-43d1-994c-7caf15fd0fc6.png">

Here is my code:

    import React from 'react';
    
    const shiki = require('shiki');
    
    componentDidMount () {
      shiki.getHighlighter({
        theme: 'nord'
      }).then((highlighter) => {
        console.log(highlighter.codeToHtml("console.log('shiki');", "js"));
      }).catch((e) => {
        console.log(e);
      });
    }
    
  Shiki version: `0.9.12`
  React version: `16.14.0`
  Please help me understand this issue and help me resolve this. What am I missing here?

Steps I followed to install and use shiki:
1. yarn add shiki
2. Import the module using `require('shiki')` as mentioned above
3. Use the imported module directly in the file where it is imported

Thanks.

**Comment by pomber** [comment]
I have a working [sample with React here](https://codesandbox.io/s/client-side-shiki-with-react-ul66q?file=/src/App.js) if you want to compare

**Comment by Divlo** [comment]
> I have a working [sample with React here](https://codesandbox.io/s/client-side-shiki-with-react-ul66q?file=/src/App.js) if you want to compare

Thanks for your help, but your example is not working...
![image](https://user-images.githubusercontent.com/25207499/156188659-f0c6238d-88da-45e9-92ef-1601c616908a.png)

I get `shiki` working by generating the HTML server side, but client side with React, I can't figure it out how to make it work.
Is Siki meant to run only on server-side or it should also be possible to run it client side?

**Comment by kylebutts** [comment]
I'm also looking to try to render server side, but it's not working with NextJS. Do you have any idea how to fix the above error @pomber?

**Comment by kouliavtsev** [comment]
@kylebutts For server-side (Nextjs), try this plugin. https://rehype-pretty-code.netlify.app/

**Comment by JeroenDerks** [comment]
@ishan-krishna I ran into a similar issue. The `onig.wasm` file that is loaded by Shiki causes issues with NextJs. 
1 solution is to load Shiki via CDN. You can then store the shiki highligher in a useState and use it through your up

```jsx
import { getHighlighter, Highlighter } from "shiki";
import { setCDN } from "shiki";
setCDN("https://unpkg.com/shiki/");

const YourComponent = () => {
  const [shiki, setShiki] = useState<Highlighter | null>(null);
 
  useEffect(() => {
    getHighlighter({
      theme: YOUR_THEME,
      langs: YOUR_LANGUAGES,
    }).then((hl: Highlighter) => {
      setShiki(hl);
    });
  }, []);

  return (<YourChildComponent shiki={shiki} />);
};

export default YourComponent;

```

**Comment by lou-lan** [comment]
me too

**Comment by kossidts** [comment]
I should have posted my issue here: #216
