### ISSUE TITLE
shiki doesnt have highlighter for vimscript syntax

### ISSUE THREAD

**Issue by alexzanderr** [shikijs/shiki#248]
im trying to convert a simple vimscript file to html using this beautiful library.

but i get an error like this
![image](https://user-images.githubusercontent.com/54772464/139854821-b36b110f-cc15-4b05-8350-3d2aedc463aa.png)

so, can you add language registration for vim, please?
[as a feature request]

my script its just the simple basic demo/example from your readme.
i just import shiki and convert to html.

**Comment by octref** [comment]
Hi @alexzanderr, `viml` was available. I just added `vim` and `vimscript` as aliases for `viml`.
