### ISSUE TITLE
Bug or feature?

### ISSUE THREAD

**Issue by karye** [shikijs/shiki#250]
When using shiki and loading language 'html' for a web page with both HTML and embeded javascript:
```
```html
<!DOCTYPE html>
<html lang="sv">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Canvas</title>
    <link rel="stylesheet" href="../nyckelpiga.css">
</head>
<body>
    <canvas></canvas>
    <script>
        // Element vi arbetar med
        const eCanvas = document.querySelector("canvas");
```

Only the **html is highlighted** but not the javascript.
![only-html-language](https://user-images.githubusercontent.com/13832931/140374867-623c89e5-5f0c-49ab-a148-12f256240bda.png)

But adding having loaded both 'html' and 'js' will make **both HTML and javascript highlighted**.
![both-html-js-language](https://user-images.githubusercontent.com/13832931/140374905-dcd66a9d-6a88-420a-8bc1-7f45c345b4fa.png)

Ok, the issue here, is when the code contains several languages like:
- HTML + js
- HTML + js + CSS
- HTML + PHP
- HTML + PHP + js

How do I specify the correct language to get everything nicely highlighted?

**Comment by stevebauman** [comment]
Hi @karye,

Language definitions contain "embedded" languages. For your example to work, select the "PHP" language, because it has the following "embedded languages" included:

- html
- xml
- sql
- javascript
- json
- css

**Comment by karye** [comment]
Kool!
Thx!

**Comment by octref** [comment]
@karye You need to load the languages `js` and `css` beside `html`. Using `php` grammar is fine as well though.
