### ISSUE TITLE
Deprecate current codeToHtml() method signature in favor of overload with options parameter

### ISSUE THREAD

**Issue by mariusschulz** [shikijs/shiki#260]
In #259, I implemented support for line highlights. I added one more optional parameter to the `codeToHtml` method, which would now have three optional parameters:

```diff
codeToHtml(
  code: string,
  lang?: StringLiteralUnion<Lang>,
  theme?: StringLiteralUnion<Theme>,
+ options?: HtmlOptions
): string

+ export interface HtmlOptions {
+  highlightedLines?: HighlightedLines
+}
+
+ // ...
```

This makes it a little awkward to call the `codeToHtml` method if I the caller wants to provide a value for the `highlightedLines` property, but not provide a value for the `lang` or `theme` parameters:

```js
const html = highlighter.codeToHtml(code, undefined, undefined, {
  highlightedLines: [1, 3]
});
```

## Proposal

I propose that we deprecate the existing overload of the `codeToHtml` method in favor of a new overload that accepts a single required `code` parameter as well as an optional `options` bag:

```diff
+ /**
+  * @deprecated
+  */
codeToHtml(
  code: string,
  lang?: StringLiteralUnion<Lang>,
  theme?: StringLiteralUnion<Theme>
): string

+ codeToHtml(
+   code: string,
+   options?: HtmlOptions
+ ): string
+ 
+ export interface HtmlOptions {
+   lang?: StringLiteralUnion<Lang>,
+   theme?: StringLiteralUnion<Theme>
+ }
```

The `options` bag is a lot easier to extend in the future. With this API in place, the above code could be written as:

```js
const html = highlighter.codeToHtml(code, {
  highlightedLines: [1, 3]
});
```

The only change we'd need to make is to add one more optional property to the `HtmlOptions` type:

```diff
export interface HtmlOptions {
+ highlightedLines?: HighlightedLines,
  lang?: StringLiteralUnion<Lang>,
  theme?: StringLiteralUnion<Theme>
}
```

## Feedback

What do you think about this proposal? I'd be happy to go ahead and implement it if you think it's a good idea.

*(Updated after feedback from @Gerrit0 below.)*

**Comment by Gerrit0** [comment]
I'd rather use overloads, with the 3 option parameter one being marked with `@deprecated`, having two _very_ similarly named methods is confusing.

**Comment by mariusschulz** [comment]
@Gerrit0 I like the idea of using overloads, this design should be even cleaner:

```diff
export interface Highlighter {
+  /**
+   * @deprecated
+   */
  codeToHtml(
    code: string,
    lang?: StringLiteralUnion<Lang>,
    theme?: StringLiteralUnion<Theme>,
    options?: HtmlOptions
  ): string
+
+  codeToHtml(
+    code: string,
+    options?: HtmlOptions
+  ): string
}
```

**Comment by mariusschulz** [comment]
I submitted a PR using overloads here: #263

**Comment by octref** [comment]
I certainly didn't expect people to use the highlighter without providing either a `theme` or `lang`.

By this

```js
const html = highlighter.codeToHtml(code, undefined, undefined, {
  highlightedLines: [1, 3]
});
```

I assume that you want a snippet not syntax-highlighted, but just with 1st and 3rd line highlighted?
In that case I think having a separate API for not highlighting the code, but just applying the HTML transformer would be better. Currently there's no obvious way to do it, but you can use lang `plaintext` for it.

**Comment by mariusschulz** [comment]
With this PR, I didn't want to change the behavior of the `codeToHtml` method beyond the signature deprecation. Both the `lang` and `theme` parameters were optional parameters before, which is why I made the optional properties in the `HtmlOptions` interface.

> I certainly didn't expect people to use the highlighter without providing either a theme or lang.

We could consider enforcing this in both the implementation as well as the type system, although that would be a breaking change.

**Comment by orta** [comment]
( this is nmerged )
