### ISSUE TITLE
Load theme from JS theme object (not file path)

### ISSUE THREAD

**Issue by pcattori** [shikijs/shiki#269]
I'd like to `import` my theme as JSON (i.e. `import theme from 'path/to/theme') during the build for my website, rather than reference the theme path at runtime (via `shiki.loadTheme`). That way I don't need to be aware of the intricacies of where my particular framework/build tools end up putting the theme.

I think this could be accomplished by exporting the [`toShikiTheme` function](https://github.com/shikijs/shiki/blob/4e00e74a2318406b36cd0481e77b22d6d21d5d55/packages/shiki/src/loader.ts#L174) from the package.

What I want:
```tsx
import theme from './night-owl.json'

const higligher = shiki.getHighlighter({ theme: shiki.toShikiTheme(theme) })
```

**Comment by orta** [comment]
https://github.com/shikijs/shiki/pull/254 has this, we just need to ship a release

**Comment by orta** [comment]
0.9.14 has it 👍🏻
