### ISSUE TITLE
[SVG] can't set background to a PowerPoint-compatible transparent

### ISSUE THREAD

**Issue by yume-chan** [shikijs/shiki#276]
I want to insert SVGs generated by shiki and shiki-renderer-svg to PowerPoint, while having a transparent background, but it doesn't work, the background is always black.

![image](https://user-images.githubusercontent.com/1330321/145973624-f041b963-68c5-4e53-b916-766b050f9500.png)

[Old SVG standard doesn't support all CSS color features](https://stackoverflow.com/questions/6042550/svg-fill-color-transparency-alpha#comment7008815_6047978), I tried setting [`bg`](https://github.com/shikijs/shiki/blob/9e6a0e964391657cf074208159dff7caf8893b9b/packages/renderer-svg/src/index.ts#L49) option to `transparent`, `rgba(0,0,0,0)` or `#00000000`, seems like PowerPoint supports none of them.

I tried manually edit the SVG file, [`fill-opacity`](https://www.w3.org/TR/SVG/painting.html#FillOpacity) properties works, and deleting the whole `rect#bg` works.

Maybe it need an extra option like `bgOpacity`, or be capable of parsing CSS colors and generating in a legacy-compatible way.

**Comment by octref** [comment]
I don't have powerpoint. Please verify in the next release (0.13.0)
