### ISSUE TITLE
[SVG] Can't set corner radius and padding to 0

### ISSUE THREAD

**Issue by yume-chan** [shikijs/shiki#277]
Because how the code is written, I can't set `bgCornerRadius`, `bgSideCharPadding`, `bgVerticalCharPadding` to `0` to completely get rid of them.

https://github.com/shikijs/shiki/blob/9e6a0e964391657cf074208159dff7caf8893b9b/packages/renderer-svg/src/index.ts#L73-L75

Also, when setting `bgVerticalCharPadding` to a very small value (for example, `10 ** -16`, the generated SVG will be cropped.

![image](https://user-images.githubusercontent.com/1330321/145975407-2b839491-4673-469c-8c7a-68bc0c587a7c.png)

My full options:

```js
const svgRenderer = await getSVGRenderer({
  bg: "transparent",
  fontFamily: "Cascadia Code",
  fontSize: 14,
  bgCornerRadius: 10 ** -16,
  bgSideCharPadding: 10 ** -16,
  bgVerticalCharPadding: 10 ** -16,
});
```

**Comment by octref** [comment]
Fortuantely we have `??` in TS now. I'll fix this.
