### ISSUE TITLE
Example of adding a language doesn't work

### ISSUE THREAD

**Issue by EvanMachusakNCQA** [shikijs/shiki#280]
I have a tmlanguage converted to JSON and I am attempting to load it into a highlighter according to the docs, e.g.:

            const highlighter = await shiki.getHighlighter({
                langs: [langJson]
            });

            const code = highlighter.codeToHtml("sample language", { lang: 'mine', theme: 'dark-plus'});

This fails.  In the callstack, shiki is calling loadGrammar:

    async loadGrammar(scopeName) {
        const lang = this.scopeToLangMap[scopeName];
        if (!lang) {
            return null;
        }
        if (lang.grammar) {
            return lang.grammar;
        }
        const g = await fetchGrammar(languages.includes(lang) ? `${this.languagesPath}${lang.path}` : lang.path);
        lang.grammar = g;
        return g;
    }

lang resolves to:

{fileTypes: Array(1), name: 'mine', scopeName: 'source.mine', patterns: Array(38)}

lang.grammar is null, so then it attempts to call fetchGrammar.

languages.includes(lang) returns false, and lang.path is null, so fetchGrammar receives null as its parameter and fails to work.

This feels like a bug, but if it's a usage problem, how do I make this work?

I am not forking shiki or anything - I used npm and I am loading the tmlanguage json from an external source, not even a disk file.  The docs imply this should work.

Can anyone please help me?

**Comment by orta** [comment]
We recently exposed `toShikiTheme` in the root exports - it might be worth running your json through that first to see if that fixes it
