### ISSUE TITLE
Add additional htmlEscapes to the list?

### ISSUE THREAD

**Issue by michaelrommel** [shikijs/shiki#291]
Hi,

I have integrated shiki as highlighter into my sveltekit / mdsvex project, which originally uses Prism as a highlighter.
The complete rendering broke, because a few characters in the code made sveltekit stumble, namely the backtick and braces because sveltekit preprocessor uses that for their templating so to speak in a laymans terms.

```
const htmlEscapes = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    '{': '&#123;',
    '}': '&#125;',
    '`': '&#96;',
    "'": '&#39;'
};
function escapeHtml(html) {
    return html.replace(/[&<>"{}`']/g, chr => htmlEscapes[chr]);
}
```
This change fixed the problems and the highlighting now works perfectly.

Would it be possible to make this change at this location:

https://github.com/shikijs/shiki/blob/cc50f8d84ec1073d90ae860ec5ebf7ab2e080638/packages/shiki/src/renderer.ts#L53-L63

or would that break anything? I am happy to create a PR, if this is acceptable.

  Michael.

**Comment by Gerrit0** [comment]
This feels like a bug in your integration of Shiki to me. However you did it, Svelte isn't parsing it as raw HTML to be injected, but as Svelte markup. With this change, the function isn't `escapeHtml`, it is `escapeHtmlAndSpecialSvelteCharacters`

**Comment by michaelrommel** [comment]
Hello @Gerrit0 ,

thanks for the quick reply. 

Yes, you are probably right. The reason why I suggested this is because I did a comparison how the PrismJS rendered markup comes back vs. Shiki's. PrismJS escapes already many, many more HTML entities, I just narrowed it down to the breaking ones.

My integration is very minimal:

```
async function myHighlighter (code, lang) {
  const highlighter = await getHighlighter({
    theme
  });

  const html = highlighter.codeToHtml(code, { lang });

  return `{@html \`${html}\` }`;
  // return html;
  // return `<pre><code>${html}</code></pre>`;
}

const config = {
  extensions: ['.svelte.md', '.md', '.svx'],
  highlight: {
    highlighter: myHighlighter
  },
  smartypants: {
    dashes: 'oldschool'
  },
  remarkPlugins: [
  ],
  rehypePlugins: [
  ]
};
```

I tried different methods, to no avail. Really the escaping is the only thing, that helped me.

If the function has to stay that way, do you have a suggestion, at which other place this would make sense? Of course, I just can re-parse the Shiki-returned markup and do the regex myself, but I thought it might help others.

  Michael.

**Comment by michaelrommel** [comment]
I have just put the lines in my integration and close this issue. Don't want to cause trouble.

```
async function myHighlighter (code, lang) {
  const highlighter = await getHighlighter({
    theme
  });

  let html = highlighter.codeToHtml(code, { lang });

  const htmlEscapes = {
    '{': '&123;',
    '}': '&125;',
    '`': '&#96;'
  };

  html = html.replace(/[{}`]/g, chr => htmlEscapes[chr]);

  return `{@html \`${html}\` }`;
}
```

You can see an example highlighted markdown here, if you want to see: https://www.michaelrommel.com/consume/2022-01-27-code-sample I am much more happy with the rendering, as now my gruvbox theme is very close to the original vim version. PrismJs had too limited tokenization.
