### ISSUE TITLE
How to get only tokens?

### ISSUE THREAD

**Issue by lakscastro** [shikijs/shiki#295]
How can I get only shiki tokens? 

So I'll be able to add add styles programatically. I searched across all repository and didn't find anything related to `css` styles. Also I didn't find an API to get only the tokens

Thanks for the package and the efforts

**Comment by Gerrit0** [comment]
You probably want `highlighter.codeToThemedTokens`

**Comment by lakscastro** [comment]
If someone is getting stuck about how to handle dark mode, this issue is really useful: https://github.com/shikijs/shiki/issues/33 I'll close it for now since the answer for my question is on the issue above
