### ISSUE TITLE
It there a way to support both diff and syntax highlighting at the same time?

### ISSUE THREAD

**Issue by zoubingwu** [shikijs/shiki#297]
For example I can use `diff` as language specifier to get a diff highlighting:

![image](https://user-images.githubusercontent.com/18644268/153232421-589c6f8e-c079-4808-ac1d-ae2396312e0b.png)

to get this:

```diff
+ var a = 1
- var 2 = 2
```

But I lose syntax highlight for other code.

```diff
+ var a = 1
- var 2 = 2

a = 3

function b() {}
```

or use `js` as language to get syntax highlight but you can't show diff highlight then:

```js
+ var a = 1
- var 2 = 2

a = 3

function b() {}
```

wondering is there a way to get both of them work just like the pull request diff view on Github?

![image](https://user-images.githubusercontent.com/18644268/153233120-4be70936-9036-4ed9-98b6-d4dd4695e2a2.png)

**Comment by orta** [comment]
This is feasible, but would require some pretty intense custom code inside shiki itself. You do a full normal syntax run of pre and post versions, then chop them up and give them the custom backgrounds inside the diff

**Comment by zoubingwu** [comment]
hmm sure, seems it's not necessary letting shiki to supoprt this. I could do some parsing before pass it to shiki then tweak shiki result to add some classname to certain lines.

**Comment by kylebutts** [comment]
For what it's worth @zoubingwu, I have some code that does this, modeling from [torchlight](torchlight.dev) https://github.com/kylebutts/shiki-vue

So you can do this and it will remove the comments and add the lines for you
```js
var a = 1 \\ [!shiki +]
var 2 = 2 \\ [!shiki -]

a = 3

function b() {}
```

**Comment by Mr-spShuvo** [comment]
Could you add this feature to Shiki? If not, what's the limitation again?

**Comment by muenzpraeger** [comment]
#381 would be able to solve this.
