### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by jbrooksuk** [shikijs/shiki#3]
Would it be possible to add support for line numbers?

Bonus points for **not** restricting you to auto-generate them either. For example, when showing a Git diff, the line numbers will change.

**Comment by octref** [comment]
It's possible, just need to add that to the [HTML renderer](https://github.com/octref/shiki/blob/master/packages/shiki/src/renderer.ts).

You can do it too if you have time:

```ts
const shiki = require('shiki')

shiki.getHighlighter({
  theme: 'nord'
}).then(highlighter => {
  const tokens = highlighter.codeToThemedTokens(`console.log('shiki');`, 'js')
  const html = shiki.renderToHtml(tokens) // default renderer, replace with yours
})
```

**Comment by alexpeattie** [comment]
As an alternative to writing a custom `renderToHtml` function: since v0.2.3 each line is wrapped in a `<span class='line'>` which makes it quite easy to do line numbering using [CSS counters](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters). I [added](https://github.com/alexpeattie/alexpeattie.com/commit/7840a41c1bba2f4e071ebaa4b982134141eef35b#diff-321385e0cc65c653b1e4c9726a4bf0e516b2566321db181612b95073629b3bbaR29-R47) some CSS like this:

```css
code {
  counter-reset: step;
  counter-increment: step 0;
}

code .line::before {
  content: counter(step);
  counter-increment: step;
  width: 1rem;
  margin-right: 1.5rem;
  display: inline-block;
  text-align: right;
  color: rgba(115,138,148,.4)
}
```

Which yields:
<img width="196" alt="Capture d’écran 2021-05-01 à 08 35 14" src="https://user-images.githubusercontent.com/636814/116773815-4cf68380-aa58-11eb-89d2-e8894843f533.png">

**Comment by bramus** [comment]
Building further upon @alexpeattie's code: using Custom Properties you can set a different start number.

```css
code {
	counter-reset: step;
	counter-increment: step calc(var(--start, 1) - 1);
}
```

```html
<code style="--start: 13;">…</code>
```

If no `--start` is set, it will fall back to start numbering at 1.

Demo: https://codepen.io/bramus/pen/mdmmdQB

_(You might want to opt for a more unique name for the Custom Property)_

**Comment by lloydjatkinson** [comment]
Given that line numbers is pretty much a normal expectation of syntax highlighting and that this issue has been open for three and a half years now, could one of the above solutions be built in?

**Comment by heychazza** [comment]
> Given that line numbers is pretty much a normal expectation of syntax highlighting and that this issue has been open for three and a half years now, could one of the above solutions be built in?

I'd also love to see code diff highlighting, so for example showing added and removed lines of code (with highlighting for whatever lang).

**Comment by zasuNan** [comment]
prefer the style of shiki, but compared with other similar plugins, such as Prism and highlight, they all have the line number function, hope shiki can also support it

**Comment by antfu** [comment]
Consider the solution https://github.com/shikijs/shiki/issues/3#issuecomment-830564854 is quite solid and working well with the existing ecosystem, I think we could consider this is resolved. Otherwise, the newly introduced [transformers API](https://shiki.style/guide/transformers) should allow this to be implemented on user land.

**Comment by tisonkun** [comment]
https://github.com/shikijs/shiki/issues/3#issuecomment-830564854 looks good. While with astro, I found there is always a trailing `<span class='line' />` rendered and it cause an extra dangling line number.

Not sure if it's an issue of Shiki or astro.

````mdx
In index.mdx file -

```rust
let x = 42;
Ok(x)
```
````

Rendered:

```html
<pre class="astro-code github-light" style="background-color:#fff;color:#24292e;overflow-x:auto" tabindex="0"><code><span class="line"><span style="color:#D73A49">let</span><span style="color:#24292E"> x </span><span style="color:#D73A49">=</span><span style="color:#005CC5"> 42</span><span style="color:#24292E">;</span></span>
<span class="line"><span style="color:#6F42C1">Ok</span><span style="color:#24292E">(x)</span></span>
<span class="line"></span></code></pre>
```

Result:

<img width="933" alt="image" src="https://github.com/shikijs/shiki/assets/18818196/35b5acb6-282f-44d5-8037-b0c472c81aab">

**Comment by seancheung** [comment]
> [#3 (comment)](https://github.com/shikijs/shiki/issues/3#issuecomment-830564854) looks good. While with astro, I found there is always a trailing `<span class='line' />` rendered and it cause an extra dangling line number.
> 
> Not sure if it's an issue of Shiki or astro.
> 
> ```mdx
> In index.mdx file -
> 
> ```rust
> let x = 42;
> Ok(x)
> ```
> ```
> 
> Rendered:
> 
> ```
> <pre class="astro-code github-light" style="background-color:#fff;color:#24292e;overflow-x:auto" tabindex="0"><code><span class="line"><span style="color:#D73A49">let</span><span style="color:#24292E"> x </span><span style="color:#D73A49">=</span><span style="color:#005CC5"> 42</span><span style="color:#24292E">;</span></span>
> <span class="line"><span style="color:#6F42C1">Ok</span><span style="color:#24292E">(x)</span></span>
> <span class="line"></span></code></pre>
> ```
> 
> Result:
> 
> <img alt="image" width="933" src="https://private-user-images.githubusercontent.com/18818196/318681030-35b5acb6-282f-44d5-8037-b0c472c81aab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MTkxNDQsIm5iZiI6MTcxMjUxODg0NCwicGF0aCI6Ii8xODgxODE5Ni8zMTg2ODEwMzAtMzViNWFjYjYtMjgyZi00NGQ1LTgwMzctYjBjNDcyYzgxYWFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA3VDE5NDA0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBkMThjYWUwYjA2MDYxNDhlNWZjNTc2YzVlYzc3YWNlODQzYzJhMjM4OTI2MTQ1NjU2OTJjNjA5YjI5NGE0NmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dM1XLx0LgJPx7ayjL21-JEg7hpg_4ArrJ3VdpDe4MCA">

Same dangling line here. You can filter it out:
```css
code > .line:not(:last-child)::before {
 /* styling */
}
```

**Comment by MatthewAry** [comment]
@antfu Would love to see [this solution](https://github.com/shikijs/shiki/issues/3#issuecomment-830564854) on the Shiki docs.

**Comment by antfu** [comment]
PR welcome :)

**Comment by lloydjatkinson** [comment]
> @antfu Would love to see [this solution](https://github.com/shikijs/shiki/issues/3#issuecomment-830564854) on the Shiki docs.

You can also checkout https://expressive-code.com/ which uses Shiki and has a line number option

**Comment by jimfilippou** [comment]
Extending on @alexpeattie's answer, if you're looking to get rid of the last line that this code adds, feel free to use the following code.

```css
code .line:last-child::before {
  content: 'none';
}
```

**Comment by eniodev** [comment]
@seancheung another way of getting rid of that extra line:

```css
code .line:last-child:empty::before {
  content: none;
  counter-increment: none;
}
```

**Comment by michael-andreuzza** [comment]
> As an alternative to writing a custom `renderToHtml` function: since v0.2.3 each line is wrapped in a `<span class='line'>` which makes it quite easy to do line numbering using [CSS counters](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Lists_and_Counters/Using_CSS_counters). I [added](https://github.com/alexpeattie/alexpeattie.com/commit/7840a41c1bba2f4e071ebaa4b982134141eef35b#diff-321385e0cc65c653b1e4c9726a4bf0e516b2566321db181612b95073629b3bbaR29-R47) some CSS like this:
> 
> ```css
> code {
>   counter-reset: step;
>   counter-increment: step 0;
> }
> 
> code .line::before {
>   content: counter(step);
>   counter-increment: step;
>   width: 1rem;
>   margin-right: 1.5rem;
>   display: inline-block;
>   text-align: right;
>   color: rgba(115,138,148,.4)
> }
> ```
> 
> Which yields: <img alt="Capture d’écran 2021-05-01 à 08 35 14" width="196" src="https://user-images.githubusercontent.com/636814/116773815-4cf68380-aa58-11eb-89d2-e8894843f533.png">

You my day  :-) Thank you.

**Comment by LekoArts** [comment]
Regarding the dangling new line when used in Astro:

You can remove it like so:

```ts
import { defineConfig } from 'astro/config'

// https://astro.build/config
export default defineConfig({
	markdown: {
		syntaxHighlight: 'shiki',
		shikiConfig: {
			transformers: [
				{
					preprocess(code) {
						if (code.endsWith('\n')) {
							code = code.slice(0, -1)
						}

						return code
					},
				},
			],
		},
	},
})

```

**Comment by lilpolymath** [comment]
@antfu do you have any reservations on how the transformer for this should be implemented?

**Comment by deadcoder0904** [comment]
Would definitely love this.

Bdw, [Jules](https://jules.google.com/) has 60 free daily tasks (for now) so if any maintainers can just ask the AI, it'll probably implement itself with Gemini 2.5 Pro.

Also, if you can tell me which file is closest to implementation, I can try it myself. Is https://github.com/shikijs/shiki/blob/main/packages/transformers/src/transformers/meta-highlight.ts close enough? There is https://github.com/phothinmg/shiki-lines-number/blob/main/src/index.ts too.

**Comment by arackaf** [comment]
@alexpeattie just wanted to thank you for one of the greatest GitHub comments in history. You absolute legend 👊 🚀

**Comment by babakfp** [comment]
## What me want and me not feel like learning and building it 😭

```ts
import { transformerLineNumbers } from "@shikijs/transformers"
import { codeToHtml } from "shiki"

const code = 'console.log("Hello, World!")'
const html = await codeToHtml(code, {
    lang: "ts",
    theme: "nord",
    transformers: [transformerLineNumbers()],
})
```

### `showLineNumbers` option

Show numbers on all code blocks by default.

```ts
transformerLineNumbers({
    showLineNumbers: true, // or `hideLineNumbers`?
})
```

### `hideLineNumbers` and `showLineNumbers` meta keyword

````md
```md hideLineNumbers
This code block won't have line numbers. It's useful when `showLineNumbers: true` is by default.
```
````

````md
```md showLineNumbers
This code block would have line numbers. It's useful when `showLineNumbers: false` is by default.
```
````

Maybe a syntax like this?

````md
```md showLineNumbers=false
This code block would have line numbers. It's useful when `showLineNumbers: false` is by default.
```
````

Show line numbers for line 1, from 3 to 4, and 6:

````md
```{1,3-4,6}
1 Cat
  Dog
3 Monkey
4 Rat
  Snake
6 Book
```
````

Something like this may be useful too! We are only counting the lines that have numbers:

````md
```{1,3-4,6} specifiedNumbersOnly
1 Cat
  Dog
2 Monkey
3 Rat
  Snake
4 Book
```
````

From 2 to end:

````md
```{2}
  Cat
2 Dog
3 Monkey
4 Rat
```
````

From 2 to end minus 1:

````md
```{2-(-1)}
  Cat
2 Dog
3 Monkey
  Rat
```
````

From start to end minus 1:

````md
```{(-1)}
1 Cat
2 Dog
3 Monkey
  Rat
```
````

### Even more features

This packages has some good other features too, like `data-line-numbers-max-digits` HTML attr on a `code` (or `pre`) tag:

https://rehype-pretty.pages.dev

Adds `[data-line-numbers]` HTML attr (to a `code` (or `pre`) tag) to show it has line numbers.

## Syntax

Whatever syntaxes I have shown here, may have issues, and I haven't put any time and efforting in thinking if they make sense, could be problamatic or what not, so they are simply used as an example.
