### ISSUE TITLE
Bracket pair colorization

### ISSUE THREAD

**Issue by theoludwig** [shikijs/shiki#303]
Hey! :wave:

Thanks for this awesome package, I can finally use VSCode default Dark+ theme syntax highlighting on my blog. :smile:
I'm wondering if [Bracket pair colorization](https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization) could be added to Shiki? It has been added to VSCode natively since v1.60 with `settings.json`: `"editor.bracketPairColorization.enabled": true`.

### With VSCode:

![image](https://user-images.githubusercontent.com/25207499/155231222-6fec990e-8758-49ed-910f-fa426e4fd14b.png)

### With Shiki

![image](https://user-images.githubusercontent.com/25207499/155231320-3cc65428-43d9-4b84-b35c-c53afbf87de6.png)

**Comment by muenzpraeger** [comment]
That should be in [now with 0.12.0](https://github.com/shikijs/shiki/releases/tag/v0.12.0).

**Comment by Divlo** [comment]
> That should be in [now with 0.12.0](https://github.com/shikijs/shiki/releases/tag/v0.12.0).

How do you enable it? It seems like it is not enabled by default? I updated to `shiki@0.12.1`, and there is still no bracket pair colorization. @muenzpraeger

**Comment by muenzpraeger** [comment]
@Divlo VSCode itself has built-in bracket-pair colorization (based on runtime inspection of the code). If that should be replicated in a non-IDE situation like here with Shiki the `tmLangauge` definition as well as the the used theme have to provide that information.

**Comment by octref** [comment]
This requires extracting the VS Code bracket pair colorization logic out and bringing it to shiki. I don't quite have the bandwidth to do it right now.

**Comment by hunghg255** [comment]
@theoludwig I tried to create a transformer, you can refer to my code [transformerBracketPairColor](https://gist.github.com/hunghg255/0fa614ffb8dd0107d39d90a4f131c810)
Hope can solve your problem

<img width="498" alt="Screenshot 2024-02-14 at 11 10 10" src="https://github.com/shikijs/shiki/assets/42096908/db6400f4-4dcc-4025-bcec-c62f3d33b15a">

**Comment by MichaelMakesGames** [comment]
Hey all, I just published a plugin for Shiki that can do this: [GitHub](https://jsr.io/@michael-makes/shiki-colorized-brackets) / [JSR](https://jsr.io/@michael-makes/shiki-colorized-brackets)

It is used as a tranformer, like this:
```ts
import shikiColorizedBrackets from '@michael-makes/shiki-colorized-brackets';
import { codeToHtml } from 'shiki';

const html = await codeToHtml('let values: number[] = [];', {
  lang: 'ts',
  theme: 'dark-plus',
  transformers: [shikiColorizedBrackets()],
});
```
When using shiki + the transformer on the above snippet, this is the output:
![shiki-colorized-brackets-example](https://github.com/user-attachments/assets/8bbfaec8-342a-49fa-ad9a-7a316df672fb)

I've tested lots of languages and situations, but I'm sure there's some edge-cases I've missed, so feedback is appreciated.

PS: if the Shiki maintainers are interested, we could discuss making this an official plugin ;)

**Comment by antfu** [comment]
Awesome @MichaelMakesGames! I'd love to have it as an official plugin :) Do you want to draft a PR first? Thank you

**Comment by MichaelMakesGames** [comment]
@antfu sure thing! But can you take a look at #736 first? The plug-in needs some info from includeExplanation, and #736 could improve the slowdown from ~5x to ~2x

**Comment by MichaelMakesGames** [comment]
@antfu this should be part of the @shiki/transformers package, or a separate package? It seems a bit larger/more complicated than the transformers in @shiki/transformers, but not nearly as complicated as @shiki/twoslash

I might try to get a couple more edge-cases handled before submitting a PR (bracket highlighting in JSDoc comments, and support for multi-character brackets such as `{{` in Angular templates)

**Comment by antfu** [comment]
I would up to have it as a separate package :)

**Comment by MichaelMakesGames** [comment]
Delayed but not forgotten :)
