### ISSUE TITLE
[HTML] Inline-styles are not highlighted correctly

### ISSUE THREAD

**Issue by manniL** [shikijs/shiki#316]
# Update

**Solution/Not an issue**

 I've created [an example](https://codesandbox.io/s/shikijs-316-bpplnh) through the official shiki demo sandbox. Weirdly, it **works** as expected there when using the default theme but not when using `vitesse-dark` nor `github-dark` 😅 

---

Hey 👋 

When using inline styles, e.g. `<p style="color: red">Red content</p>` while using the `html` language setting for shiki, they are not highlighted correctly.

![grafik](https://user-images.githubusercontent.com/640208/165140133-33e01cde-d940-46e2-91de-22f30ca2c70d.png)

# Generated HTML

```html
<pre class="slidev-code shiki shiki-dark" style="background-color: rgb(18, 18, 18);"><code><span class="line"><span style="color: rgb(133, 133, 133);">&lt;</span><span style="color: rgb(66, 153, 136);">p</span><span style="color: rgb(219, 215, 202);"> </span><span style="color: rgb(224, 165, 105);">style</span><span style="color: rgb(133, 133, 133);">=</span><span style="color: rgb(201, 138, 125);">"</span><span style="color: rgb(219, 215, 202);">color: red"</span><span style="color: rgb(133, 133, 133);">&gt;</span><span style="color: rgb(219, 215, 202);">Red content</span><span style="color: rgb(133, 133, 133);">&lt;/</span><span style="color: rgb(66, 153, 136);">p</span><span style="color: rgb(133, 133, 133);">&gt;</span></span></code></pre>
```

**Comment by orta** [comment]
Interesting, what does the html look like?

**Comment by manniL** [comment]
I think https://github.com/textmate/html.tmbundle/issues/88 could be related/the upstream issue?

**Comment by muenzpraeger** [comment]
That should be in [now with 0.12.0](https://github.com/shikijs/shiki/releases/tag/v0.12.0).

**Comment by manniL** [comment]
@muenzpraeger Thanks for the update! I can confirm that it was resolved for the `github-dark` theme but not for vitesse. Is this an issue of the vitesse template from here on then?

**Comment by muenzpraeger** [comment]
@manniL I believe so that it's somehow an issue with the theme.

I tried your example with a few other themes, and only in the `vitesse-dark` theme I'm seeing a _different_ tokenization than with the other themes.

Personally I'm not very deep into the mechanics - but I'm curious to figure why. So stay tuned for a day or two. ;-)

**Comment by octref** [comment]
The closing quote is an issue with vitesse-dark theme itself:

<img width="527" alt="image" src="https://user-images.githubusercontent.com/4033249/214923259-c850d532-9aa4-4f71-a669-ea8338d3e951.png">

**Comment by octref** [comment]
The upstream issue is fixed too.

**Comment by manniL** [comment]
Thanks a lot @octref 🙏
