### ISSUE TITLE
Support for diffs & code blur

### ISSUE THREAD

**Issue by heychazza** [shikijs/shiki#330]
Hi,

It would be great if we was able to highlight diffs similar to this:
![1AFD0748-9545-4650-B6DE-C149F83CE5C6](https://user-images.githubusercontent.com/47271716/176746054-69d80c09-b0fa-4d29-b86e-2527c0506181.jpeg)

In addition, being able to blur surrounding code so only a section is visible.

Not sure if plug-ins exist to do this.

**Comment by brillout** [comment]
For code diffs, see https://github.com/shikijs/shiki/issues/297.

**Comment by octref** [comment]
Let's track it in #297.
