### ISSUE TITLE
Add language alias to c# so it matches file extensions

### ISSUE THREAD

**Issue by botteroxom** [shikijs/shiki#331]
can we have cs for language 
| 'csharp' | 'c#' | 'cs'

we can import files to show the code and would be nice if the language matches the file extension so it can identify the correct language.

see
https://github.com/vuejs/vitepress/issues/861
https://github.com/vuejs/vitepress/pull/875

**Comment by orta** [comment]
Sure, you're welcome to add it if it hasn't been added since this issue came out 👍🏻
