### ISSUE TITLE
don't throw Error 'No language registration for xxx'

### ISSUE THREAD

**Issue by gittig11** [shikijs/shiki#332]
When I call getGrammar('mjs')  in `packages\shiki\src\highlighter.ts`, error occurs: `No language registration for mjs`, which results in a error like ['vitepress build docs' error](https://github.com/vuejs/vitepress/issues/1025#issuecomment-1191481726).

As a result, I **pass the default language 'text'** to `function codeToThemedTokens()` when there is no language registration. This will solve the problem.

**Comment by muenzpraeger** [comment]
Closed b/c PR closed.
