### ISSUE TITLE
dist/onig.wasm not available in 0.11.0

### ISSUE THREAD

**Issue by mcintyre94** [shikijs/shiki#337]
In our app we use `shiki.setCDN('https://unpkg.com/shiki/')`, and the code that loads `dist/onig.wasm` is redirecting from https://unpkg.com/shiki/dist/onig.wasm to the new https://unpkg.com/shiki@0.11.0/dist/onig.wasm

But this path doesn't seem to exist in the 0.11.0 release: https://unpkg.com/browse/shiki@0.11.0/dist/

Is it intentional that there's no `dist/onig.wasm` in the latest version? I can't see any `wasm` files at all in the latest version. The code seems to still be trying to load `dist/onig.wasm` on the latest version: https://github.dev/shikijs/shiki/blob/33ae6b97eda78484460ac05b3338bc72a605194a/packages/shiki/src/loader.ts#L52

**Comment by orta** [comment]
Hrm, there's no docs on how to deploy shiki, so it's very possible that I shipped it wrong - will take a look

**Comment by Gerrit0** [comment]
It should autodeploy if a PR bumping the version is merged

**Comment by orta** [comment]
(sorry, low on time today, will look tomorrow)

Yeah, I thought that would be it ( https://github.com/shikijs/shiki/runs/7785870097?check_suite_focus=true#step:8:304 ) but it failed for what _I_ think are access token issues

**Comment by orta** [comment]
Fixed in 0.11.1 - thanks for the report!

**Comment by JeroenDerks** [comment]
Thanks for the work and the great library!
