### ISSUE TITLE
CDN version breaks above v0.10.1

### ISSUE THREAD

**Issue by mplatts** [shikijs/shiki#338]
`<script src="https://unpkg.com/shiki"></script>`

Gives error:

```
shiki:1 Uncaught ReferenceError: vscode is not defined at shiki:1:31910
```

Fixes it:

`<script src="https://unpkg.com/shiki@0.10.1"></script>`

**Comment by orta** [comment]
Interesting, unsure what triggers this

**Comment by Gerrit0** [comment]
```js
)}(this.shiki=this.shiki||{},vscode-oniguruma,vscode-textmate);
```

... well that's definitely not desirable output. Possibly a rollup update?

**Comment by lnfel** [comment]
same here.

> Uncaught ReferenceError: vscode is not defined
> Uncaught TypeError:
> shiki.getHighlighter is not a function
