### ISSUE TITLE
Rendering without the "pre" and "code" tags

### ISSUE THREAD

**Issue by 6r1d** [shikijs/shiki#341]
Hello.

Previously, there was a related issue, #220, but I'd like to know if it is possible to do rendering without those tags at all in a `codeToHtml` call.

I need to use the result in a Vue component with a custom theme and I am removing those tags with a regular expression that can potentially break later: `r.replace(/<pre class="shiki" style="background-color: #[a-z0-9]+"><code>/, '').replace('</code></pre>', '')`. It would be much nicer if I didn't need to do that and had a rendering option.

Thanks!

**Comment by orta** [comment]
Did you look at using the [elements API](https://github.com/shikijs/shiki/pull/243#issuecomment-939581488) to set a custom pre to an empty string?

**Comment by 6r1d** [comment]
> Did you look at using the [elements API](https://github.com/shikijs/shiki/pull/243#issuecomment-939581488) to set a custom pre to an empty string?

Yes, although when I tried the first time I've missed the fact I have to add `children` attribute in the template and update Shiki. Thanks! It worked with:

```js
import { getHighlighter, renderToHtml } from 'shiki'

getHighlighter({theme: 'nord'})
  .then(highlighter => {
    const tokens = highlighter.codeToThemedTokens(`console.log('shiki');`, 'js')
    const highlightLines = [ 4, 5, 6 ]
    const html = renderToHtml(tokens, {
      fg: highlighter.getForegroundColor('nord'),
      bg: highlighter.getBackgroundColor('nord'),
      elements: {
        pre({ className, style, children }) {
          return `${ children }`
        },
        code({ className, style, children }) {
            return `${ children }`
        },
      }
    })
    console.log( html )
  })

```
