### ISSUE TITLE
Let client add their alias to bundled language?

### ISSUE THREAD

**Issue by dannypsnl** [shikijs/shiki#342]
I cannot find a way to add alias `hs` for haskell code block, and I expect I can do this in the configuration just like prismjs. Maybe something like:
```js
shiki.getLanguage("haskell").addAlias("hs")
```

**Comment by orta** [comment]
I think this is a pretty good idea, open to API contracts for it 👍🏻 

Also open to PRs adding hs to the haskell language, seems like a reasonable expectation by default
