### ISSUE TITLE
dist/onig.wasm not available in 0.11.1

### ISSUE THREAD

**Issue by social-uni** [shikijs/shiki#346]
https://stackblitz.com/edit/vitejs-vite-gqv1wz?file=package.json,src%2Fcomponents%2FHelloWorld.vue,index.html&terminal=dev

i use  shiki on vite get error  

> Uncaught (in promise) CompileError: WebAssembly.instantiate(): BufferSource argument is empty

![image](https://user-images.githubusercontent.com/14007972/187042039-d41780db-ab89-416c-9ad7-a184ea38478b.png)

![image](https://user-images.githubusercontent.com/14007972/187042083-e932e2d0-3d5d-4cd4-99da-a6889d6df34e.png)

https://github.com/vitejs/vite/issues/9874

**Comment by orta** [comment]
Unsure but https://github.com/shikijs/shiki/issues/337 fixed this and it shows as downloadable in https://unpkg.com/shiki@0.11.1/dist/onig.wasm

**Comment by social-uni** [comment]
> Unsure but #337 fixed this and it shows as downloadable in https://unpkg.com/shiki@0.11.1/dist/onig.wasm

https://github.com/vitejs/vite/issues/9874

I'm not sure if this is a vite or shiki issue, so I also filed issues on vite

**Comment by social-uni** [comment]
> Unsure but #337 fixed this and it shows as downloadable in https://unpkg.com/shiki@0.11.1/dist/onig.wasm

This problem may be related to https://github.com/shikijs/shiki/issues/216

**Comment by CrazyBoy49z** [comment]
setWasm('/node_modules/shiki/dist/onig.warm')

**Comment by muenzpraeger** [comment]
Does this happen with Vite _outside_ of StackBlitz?

I'm asking b/c Stack doesn't permit binary files for free accounts.
