### ISSUE TITLE
Usage Missing instructions on setCDN

### ISSUE THREAD

**Issue by social-uni** [shikijs/shiki#347]
Consider adding a note about setCDN to Usage?

Otherwise, it will bring great trouble to users. The following problems are related to the lack of setCDN related content in the document

If you add setCDN related documents to Usage, it may reduce your troubles

https://github.com/shikijs/shiki/issues/216
https://github.com/shikijs/shiki/issues/246
https://github.com/shikijs/shiki/issues/346

no work

![image](https://user-images.githubusercontent.com/14007972/187072072-ad9a5d32-0048-4866-9f99-3be9c4e00649.png)

work ok

![image](https://user-images.githubusercontent.com/14007972/187072133-45fe1635-9e38-4d77-8f2b-076f886c0b5c.png)

**Comment by orta** [comment]
I think this might need a separate code sample, because this would be worse on node (which I think is the majority of usage) and this is only useful for browsers environments - open to PRs

**Comment by social-uni** [comment]
> I think this might need a separate code sample, because this would be worse on node (which I think is the majority of usage) and this is only useful for browsers environments - open to PRs

You can add this line of code and comment when you need this line of code and when you don't

like
```
//when useful for browsers environments
setCDN(xxx)
```
