### ISSUE TITLE
the `path` argument must be of type string

### ISSUE THREAD

**Issue by juliusmarminge** [shikijs/shiki#356]
Given the following client side React code:

```ts
import React from 'react';
import * as shiki from 'shiki';

shiki.setCDN('https://unpkg.com/shiki/');
const highlighterPromise = shiki.getHighlighter({
  themes: ['nord', 'min-light'],
  langs: ['ts'],
});

export const ShikiCodeBlock: React.FC<{ code: string; lang: string }> = ({
  code,
  lang = 'ts',
}) => {
  const [html, setHtml] = React.useState('');
  React.useEffect(() => {
    void highlighterPromise.then((highlighter) => {
      const html = highlighter.codeToHtml(code, { lang, theme: 'nord' });
      setHtml(html);
    });
  }, [code, lang]);
  return (
    <div
      className="shiki-code-block hidden dark:block"
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
};
```

I get the following error at build time:

<img width="1143" alt="CleanShot 2022-09-12 at 23 21 18@2x" src="https://user-images.githubusercontent.com/51714798/189761002-0cf6e77c-a857-4b8a-aaf7-7543266b401b.png">

However, it works properly in dev:

<img width="1334" alt="CleanShot 2022-09-12 at 23 24 08@2x" src="https://user-images.githubusercontent.com/51714798/189761338-640da3b9-1a7f-442c-8af8-421ff601e074.png">

I wonder if there is some step I'm missing when using it on the client? Maybe you should update your docs for this to make it more clear?

**Comment by Gerrit0** [comment]
It sounds like your bundler is trying to include the wasm in your bundle... probably a configuration error there.

**Comment by juliusmarminge** [comment]
> It sounds like your bundler is trying to include the wasm in your bundle... probably a configuration error there. 

Very possible. Do you have any idea what I can do? We're using shiki for docusaurus in markdown, and I'm trying to build a component to use shiki for the jsx stuff too: https://github.com/trpc/trpc/pull/2695
