### ISSUE TITLE
ESM Support for Shiki (usage in Framer)

### ISSUE THREAD

**Issue by benjamindenboer** [shikijs/shiki#357]
Hello! I’d love to support Shiki within Framer, as part of a component such as https://syntax.page/

Unfortunately, it appears Shiki isn’t ESM-compatible. In Framer, I can pull in NPM packages to create custom React components with, but only if they are ESM-compatible. https://www.framer.com/npm/

This is what it errors on:

<img width="1043" alt="image" src="https://user-images.githubusercontent.com/869934/189894712-76c5b5ee-45a4-48ef-8023-1f34435dce86.png">

`T10:04:20.356Z warn: [modules-runtime] Error in 'codeFile/Shiki.tsx': SyntaxError: The requested module 'https://ga.jspm.io/npm:vscode-oniguruma@1.6.2/release/main.js' does not provide an export named 'createOnigScanner'
(anonymous) @ instrument.js:91
instrument.js:91 `

Would appreciate any guidance or tips.

**Comment by orta** [comment]
Think you might need to get support for ESM packages downstream in libraries like vscode-oniguruma before shiki can support ESM with shiki. ESM support is likely to be a (big) community contribution sometime, but I wouldn't hold your breath as I think you're the first to ask.

**Comment by octref** [comment]
It's complicated and here's more info: https://github.com/shikijs/shiki/issues/131
