### ISSUE TITLE
Exception has occurred: Error: No language registration for properties

### ISSUE THREAD

**Issue by NicolasThierion** [shikijs/shiki#359]
Shiki misses a *properties* grammar.

```properties
someprop=someprop
```
=>

Exception has occurred: Error: No language registration for properties
Using Shiki v0.9.15.

Thank you in advance for your help.

**Comment by orta** [comment]
I've never heard of a programming language called properties? If you can find a grammar and submit a PR adding it that seems reasonable.

**Comment by NicolasThierion** [comment]
`.properties` files are basically `ini` files we use to configure java applications.


For the moment, I added an `properties` alias to the `ini` grammar.
I think this is what vscode also did to support `properties`: https://github.com/microsoft/vscode/tree/main/extensions/ini.

I will work on a PR to add `properties` as an alias.
[https://opengraph.githubassets.com/f404ae79646a8f7037318e7f75387d1a7c5668dd5395efc4d9e2f6946a4ecf67/microsoft/vscode]<https://github.com/microsoft/vscode/tree/main/extensions/ini>
vscode/extensions/ini at main · microsoft/vscode<https://github.com/microsoft/vscode/tree/main/extensions/ini>
Visual Studio Code. Contribute to microsoft/vscode development by creating an account on GitHub.
github.com

________________________________
De : Orta Therox ***@***.***>
Envoyé : mercredi 21 septembre 2022 09:37
À : shikijs/shiki ***@***.***>
Cc : Nicolas THIERION ***@***.***>; Author ***@***.***>
Objet : Re: [shikijs/shiki] Exception has occurred: Error: No language registration for properties (Issue #359)


I've never heard of a programming language called properties? If you can find a grammar and submit a PR adding it that seems reasonable.

**Comment by octref** [comment]
Is `ini` different than `properties`? Why can't you use `ini` instead? `properties` could be very ambiguous.

**Comment by muenzpraeger** [comment]
@octref If we'd want to be conform with [how the definition for VS Code is shipped](https://github.com/microsoft/vscode/blob/main/extensions/ini/package.json#L49), then I'd vote for adding `properties` as alias.
