### ISSUE TITLE
How do I use shiki with marked.js?

### ISSUE THREAD

**Issue by talwat** [shikijs/shiki#362]
Hi! I want to use shiki with [marked.js](https://marked.js.org/) but I can't seem to find any results on how to do it. Is it possible?

**Comment by octref** [comment]
Just use `shiki` instead of `highlight.js` here: https://marked.js.org/using_advanced

**Comment by talwat** [comment]
Can I have an example? I was struggling because shiki is asynchronous and highlight.js is not. Thanks.

**Comment by octref** [comment]
something like

```ts
shiki.getHighlighter().then(hl => {
  marked.setOptions({
    highlight: function(code, lang) {
      return hl.codeToHtml(code, lang);
    }
  })
})
```
