### ISSUE TITLE
Stale NPM package

### ISSUE THREAD

**Issue by ruanspies** [shikijs/shiki#364]
The latest publish of the [package on NPM](https://www.npmjs.com/package/shiki) was last updated ~2 months ago. A number of languages has been added in the interim and do not reflect yet because of this. Should their not be a more regular build and publish? Either on a _periodic_ interval or when PRs are merged?

**Comment by muenzpraeger** [comment]
[0.12.0 is out](https://github.com/shikijs/shiki/releases/tag/v0.12.0)
