### ISSUE TITLE
Request for a light_vs.json update

### ISSUE THREAD

**Issue by gregvanl** [shikijs/shiki#366]
We just recently fixed a color contrast issue for code.visualstudio.com HTML and CSS code blocks by making some foreground red colors a little darker.

VS Code commit https://github.com/microsoft/vscode/commit/bf220dd91e46d061cf37dbb6e0092370519ab8e1

We'd like a shiki update so that this change can be reflected on the VS Code website. Not sure the cadence for shiki updates or what is the best process for creating an update request.

Thanks!

**Comment by muenzpraeger** [comment]
[0.12.0 is out](https://github.com/shikijs/shiki/releases/tag/v0.12.0), and languages/themes are updated.
