### ISSUE TITLE
[feature-request] Add `terminal` to the list of languages

### ISSUE THREAD

**Issue by babakfp** [shikijs/shiki#371]
Hey
I was using `terminal` lang in my markdown and when I switched to ShikiJS for highlighting the code blocks, I realized there is no such thing as `terminal` lang, so replaced it with `cmd`.
Can we add `terminal` too? I don't know how much it makes sense to add it or not but the only difference that I'm seeing between `cmd` and `terminal` is this:

### `cmd` example
![Screenshot 2022-11-04 102534](https://user-images.githubusercontent.com/44144724/200038589-a130a777-5403-43fe-9484-afc720cdf4a8.png)

### `terminal` example in vsCode terminal:
![Screenshot 2022-11-04 102557](https://user-images.githubusercontent.com/44144724/200038675-0c4859c7-ec5f-4e9f-aeef-01270b3e10fd.png)

Pay attention to the `-` character between svelte`-`outclick. `-` is part of the package name.

---

By the way, is this the way to exclude unneeded langs from loading?

```js
const highlighter = await getHighlighter({
  theme: 'rose-pine',
  langs: ['html', 'css', 'js', 'svelte', 'php', 'cmd'],
})
```

That's all. Thanks.

**Comment by muenzpraeger** [comment]
One question, one answer. ;-)

Question: what did you use for highlighting? Haven't seen/couldn't find `terminal` as a definition, so would like to take a look.

Answer: yes, that's the best way. Recently doc'd [here](https://github.com/shikijs/shiki#creating-the-highlighter) (2nd example).

**Comment by babakfp** [comment]
Hey
Thank you...

I don't have anything to show related to terminal highlighting because it never existed. I was using it as a placeholder, so I wasn't getting any highlighting from it. When I started using Shiki, I replaced the terminal placeholder with cmd and I got some highlighting. Now, what do I mean by adding a new terminal highlighting? Can you spot the difference between ("`terminal` example in vsCode terminal", and "`cmd` example")? A new highlighting lang that highlights like vscode terminal... It's similar to `cmd` but a bit different...

**Comment by muenzpraeger** [comment]
Ah - that makes now so much sense for me.

"Terminal" is just the app name in VS Code. And a general term used for shell interfaces like cmd, sh, zsh...

What you are looking for is `powershell`, which you also can identify via the PS at the start of each line.
