### ISSUE TITLE
HTML output looks incorrect

### ISSUE THREAD

**Issue by babakfp** [shikijs/shiki#372]
Hi

As you can see in this screenshot, the output looks incorrect because for example ` count++}` shouldn't be inside only 1 element, the output should be ` count` `+` `+` `}` instead (or something like that).

![Screenshot 2022-11-04 140534](https://user-images.githubusercontent.com/44144724/200075238-75aad4d7-a908-4897-a311-4287c3c300d7.png)

- The theme name is `'rose-pine'` in the browser and in the vsCode.
- Please ignore the code block background color between the browser and vsCdoe because I changed it via CSS.
- Link to website http://babakfp.ir/docs/svelte-outclick (code block is under this title `SIMPLE EXAMPLE`).
- Link to Shiki code https://github.com/babakfp/babakfp-site/blob/main/svelte.config.js
- Link to code block source https://github.com/babakfp/babakfp-site/blob/main/src/lib/content/docs/svelte-outclick/index.md#simple-example

**Comment by babakfp** [comment]
![Screenshot 2022-12-15 061254](https://user-images.githubusercontent.com/44144724/207885218-9a30bd76-bfd2-4176-9c1f-ba58234936db.png)

**Comment by muenzpraeger** [comment]
As the code examples above are no longer available just a guess: you're not loading the [needed embedded languages](https://github.com/shikijs/shiki/blob/main/packages/shiki/src/languages.ts#L872) for `svelte`. With that the tokenization can only use the svelte grammar, but not access the definitions from the the other languages that actually make `svelte`.

So load those languages, and you should be good. Eventually this would be solved automagically by PR #379.

For context:
When you inspect the tokenization in VS Code ("Developer: Inspect Editor Tokens and Scopes") you'll directly see from which (embedded) language it derives the tokenization. Like here the `import` keyword from JavaScript or the `++` increment from TypeScript.

![image](https://user-images.githubusercontent.com/2205451/208036062-a568a5e1-1405-4fd4-8c46-3087349c52c9.png)
![image](https://user-images.githubusercontent.com/2205451/208036085-6fde0b6d-9ed9-47b2-ae19-38e5387a9654.png)

**Comment by babakfp** [comment]
Hi

Sorry, I updated the broken URLs.

Your guess was correct, I added `"typescript"` and it fixed it. But the thing is, my code isn't in TypeScript (it's in JavaScript), so how does TypeScript affect it?


![Screenshot 2022-12-16 025510-min](https://user-images.githubusercontent.com/44144724/208090428-543d1086-a857-4b74-95ba-7e44d5ad61c1.png)
![Screenshot 2022-12-16 030207-min](https://user-images.githubusercontent.com/44144724/208090402-5161e97c-5307-4285-b9d5-b5b1db661925.png)

**Comment by babakfp** [comment]
Hi

Sorry, I updated the broken URLs.

Your guess was correct, I added `"typescript"` and it fixed it👏.

![Screenshot 2022-12-16 025510-min](https://user-images.githubusercontent.com/44144724/208090428-543d1086-a857-4b74-95ba-7e44d5ad61c1.png)

> the `++` increment from TypeScript.
> 
> ![image](https://user-images.githubusercontent.com/2205451/208036062-a568a5e1-1405-4fd4-8c46-3087349c52c9.png)

Interesting, but why the language for `++` is typescript?🤨

---

There is still a bit of difference between vsCode and Shiki. 

in vsCode:

![Screenshot 2022-12-16 030207-min](https://user-images.githubusercontent.com/44144724/208090402-5161e97c-5307-4285-b9d5-b5b1db661925.png)

(characters inside the red blocks look different in Shiki)

---

Thanks for the help🧡

**Comment by octref** [comment]
Seems identitcal to me now. If this is still an issue, open a new one.

**Comment by octref** [comment]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/4033249/215143201-cd9fc948-244b-4bd0-bcc2-ffd0ea2ec751.png">

**Comment by babakfp** [comment]
@octref 
I think the difference is because of this feature:
https://code.visualstudio.com/blogs/2021/09/29/bracket-pair-colorization
I'm not sure but I think we have an open issue (a feature request) related to this Bracket pair Colorization feature.

**Comment by octref** [comment]
#303
