### ISSUE TITLE
Cannot set wasm source

### ISSUE THREAD

**Issue by muuvmuuv** [shikijs/shiki#375]
See: https://github.com/shikijs/shiki/blob/a99c9df9818768f432a69387a4687a3344b4926e/packages/shiki/src/loader.ts#L52

Path is fixed to dist..

**Comment by muenzpraeger** [comment]
The function is meant to add the WASM as ArrayBuffer, not an alternative path.

**Comment by muuvmuuv** [comment]
Ohh okay. But then how do I adjust the path? There is CDN Source but it doesnt respect the WASM Source. 

My project is in Angular so I had to manually cooy the assets over but the dir changes so I have to make a few adjustments

**Comment by muenzpraeger** [comment]
Something like this, where you then replace `process.env.SHIKI_ASSETS` at build time with your path.

```javascript
const SHIKI_ASSETS = process.env.SHIKI_ASSETS || "/assets/shiki/";
shiki.setCDN(SHIKI_ASSETS);
const response = await fetch(`${SHIKI_ASSETS}wasm/onig.wasm");
shiki.setWasm(response);
```

Note that the above example directly passes the `response`, and not `response.arrayBuffer()`. That way WebAssembly instantiates the streamed content already, which would save time on the client side.

**Comment by muuvmuuv** [comment]
That worked nice, thanks! Put that in an Observable so it wont be pulled multiple times and now it is nice and reuseable in Angular.
