### ISSUE TITLE
Missing brackets with default export in JavaScript/TypeScript

### ISSUE THREAD

**Issue by mst101** [shikijs/shiki#388]
When using a default export in JavaScript or TypeScript that accepts a parameter, some brackets are missed off the end of the first line:

```ts [plugins/myPlugin.ts]
export const test = (param) => {
  // Displays correctly...
}

export default function() {
  // Displays correctly...
}

export default function(param) {
  // Displays `export default function (param`
  // Instead of `export default function (param) {`
}

export default () => {
  // Displays correctly...
}

export default (param) => {
  // Displays `export default (param) =>`
  // Instead of `export default (param) => {`
}
```

[See example here](https://nuxt.com/docs/guide/directory-structure/plugins#creating-plugins)

**Comment by muenzpraeger** [comment]
This is fixed with the newer `vscode-textmate` version in PR #377

**Comment by muenzpraeger** [comment]
[0.12.0 with the aforementioned PR](https://github.com/shikijs/shiki/releases/tag/v0.12.0) is out.
