### ISSUE TITLE
Console highlighting

### ISSUE THREAD

**Issue by achingbrain** [shikijs/shiki#389]
Github highlights fenced code blocks with the `console` language identifier:

````
```console
$ some-command
command output 1
command output 2
command output 3
etc
```
````

Formatted:

```console
$ some-command
command output 1
command output 2
command output 3
etc
```

Is there any way to configure or support this identifier with shiki?

Refs: https://github.com/TypeStrong/typedoc/issues/2123

**Comment by orta** [comment]
I'd assume this is an alias to `bash` or `shell` or `sh`?

**Comment by achingbrain** [comment]
I don't think so, the output is different.  I think `shell` and `sh` are alias for `bash` (or some variation thereof) and I think `bash` is for bash scripts rather than the console output.

### bash

````
```bash
$ some-command
command output 1
command output 2
command output 3
etc
```
````

Formatted:

```bash
$ some-command
command output 1
command output 2
command output 3
etc
```

### shell

````
```shell
$ some-command
command output 1
command output 2
command output 3
etc
```
````

Formatted:

```shell
$ some-command
command output 1
command output 2
command output 3
etc
```

### sh

````
```sh
$ some-command
command output 1
command output 2
command output 3
etc
```
````

Formatted:

```sh
$ some-command
command output 1
command output 2
command output 3
etc
```

**Comment by muenzpraeger** [comment]
`console` is at GitHub an [alias for shell session](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml#L6288-L6299). There are few grammars on GitHub, most seem to point back to the [definitions from Atom](https://github.com/atom/language-shellscript/blob/master/grammars/shell-session.cson).

**Comment by octref** [comment]
Added `console` as an alias for `shell`.
