### ISSUE TITLE
[0.12.0] __require.resolve is not a function

### ISSUE THREAD

**Issue by kingyue737** [shikijs/shiki#392]
It seems that `resolve.require` cannot be used in ESM

`shiki` v0.11.1 + `vscode-oniguruma` v1.6.2 does not have this bug.

```console
shiki.js?v=85dbaa0a:4320 
        
       Uncaught TypeError: __require.resolve is not a function
    at getOniguruma (shiki.js?v=85dbaa0a:4320:45)
    at getHighlighter (shiki.js?v=85dbaa0a:4829:34)
    at main.js:7:27
```

minimal repro: https://stackblitz.com/edit/vitejs-vite-ziy4v2

**Comment by orta** [comment]
Should be fixed in 0.12.1
