### ISSUE TITLE
[0.12.0] Module "path" has been externalized for browser compatibility. Cannot access "path.join" in client code.

### ISSUE THREAD

**Issue by kingyue737** [shikijs/shiki#393]
Does not have this warning in v0.11.1

![image](https://user-images.githubusercontent.com/40021217/208355898-dd4ba037-3198-4730-8baf-661f8be813a4.png)

minimal repro: https://stackblitz.com/edit/vitejs-vite-ziy4v2
It's the same repro as #392

**Comment by orta** [comment]
Should be fixed in 0.12.1
