### ISSUE TITLE
Mention shiki-es

### ISSUE THREAD

**Issue by orta** [shikijs/shiki#397]
https://github.com/unjs/shiki-es

I'm not really sure about us converting to ESM, because I don't really feel like I grok all the trade-offs and how to do backwards compat, but the README should mention this module as it's a good answer

**Comment by yellowsink** [comment]
I just tried this package and I will say, it has been very simple for me to get working in a browser environment.

Presumably a mix of ESM playing well with bundlers and a CDN being set by default meaning no trouble loading themes and languages.

**Comment by octref** [comment]
Hey @pi0, wanna bring this back to `shiki`? Trying to push for a 1.0 and want to include ESM support out of the box.

**Comment by pi0** [comment]
Hi, dear @octref. Sure I would be happy to push for that. `shiki-es` is kinda hacky ATM. The main difference is the WASM bundling method. Maybe we can add it to monorepo as `shiki-standalone`?

**Comment by octref** [comment]
Just looked through it. It's a clever hack!

> The main difference is the WASM bundling method that is inlined for server and loaded from CDN from browser to reduce bundling issues.

What issues are you running into?

**Comment by antfu** [comment]
CLosing as shiki-es is now deprecated in favor of shikiji, which is merging back to Shiki with #557
