### ISSUE TITLE
wasm file streaming issue

### ISSUE THREAD

**Issue by KevinBatdorf** [shikijs/shiki#400]
Updating to 12 introduced an error for me and I wanted to share it in case others encounter it. I'm not sure how widespread this occurs. 

> Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.

The change is from using a Response object ([here](https://github.com/shikijs/shiki/blob/main/packages/shiki/src/loader.ts#L18)) instead of an ArrayBuffer, which as you know is handled differently by [oniguruma](https://github.com/microsoft/vscode-oniguruma/blob/main/out/index.js#L337)

Using the advice in the readme works:

```js
const wasmBuffer = await fetch('/your/path/onig.wasm').then(res => res.arrayBuffer())
setWasm(wasmBuffer)
```

**Comment by muenzpraeger** [comment]
Thanks for sharing.

That sounds very much like an infrastructure issue. What's the content type that's provided for the WASM?

**Comment by KevinBatdorf** [comment]
`application/octet-stream` which I guess should be `application/wasm`

**Comment by muenzpraeger** [comment]
Correct.

Out of curiosity, what's the server/proxy serving the file? Wondering if this should be doc'd.

**Comment by KevinBatdorf** [comment]
With nginx 1.17.3 I had to add this to get it working there.

```
types {
  application/wasm wasm;
}
```
