### ISSUE TITLE
Odd highlighting for shellscript which does not match VSCode

### ISSUE THREAD

**Issue by Gerrit0** [shikijs/shiki#404]
Running the below repro:

```js
// @ts-check
const fs = require("fs");
const s = require("shiki");

async function main() {
    const h = await s.getHighlighter({
        langs: ["shellscript"],
        themes: ["github-light"],
    });

    const html = h.codeToHtml("npm i your-dependency", { lang: "shellscript" });

    fs.writeFileSync("test.html", html);
}

main();
```

Highlights as:

![image](https://user-images.githubusercontent.com/19329837/211215112-d881f5fc-dfa6-4316-ae34-56c9ddc64f2f.png)

While in VSCode it highlights as:

![image](https://user-images.githubusercontent.com/19329837/211215134-6e9f1b0a-d46f-4693-a925-008f709d9807.png)

This broke with an upgrade from ^0.11.1 to ^0.12.1

Ref: https://github.com/TypeStrong/typedoc/issues/2139

**Comment by Gerrit0** [comment]
git bisect says 3663ccfb97a15982f3d4a74c9ef17e0e481eab6f is the culprit.

**Comment by muenzpraeger** [comment]
Eventually we should move to the standard that's provided by VSC. https://github.com/microsoft/vscode/blob/main/extensions/shellscript/syntaxes/shell-unix-bash.tmLanguage.json

**Comment by octref** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/4033249/215154503-92fc7694-ef86-4ea5-8ce2-dc5d913552cf.png">

Well, I guess this is working as intended by the new grammar included in VS Code. You'll see it in next insiders.

**Comment by octref** [comment]
Unless the old one is more preferable? I don't have a preference myself. This will match VS Code's highlighting from next version on.
