### ISSUE TITLE
Add HTTP language

### ISSUE THREAD

**Issue by dominikcz** [shikijs/shiki#405]
Are there any plans to add HTTP as a supported language? I've migrated from Prism and just realized that Shiki doesn't support color highlighting in HTTP.

Therefore currently the only way to render HTTP is using plain text:
```
GET /my-endpoint HTTP/1.1
Host: api.example.com:8767
Authorization: Bearer my-token-value
```
while in Prism you get this:
![prism](https://user-images.githubusercontent.com/23698552/211388175-a212d7e0-0cab-4777-9315-bdce50cb3199.png)

**Comment by orta** [comment]
If there's a vscode extension with support, I don't see why not - feel free to add it, https://github.com/shikijs/shiki/blob/main/docs/languages.md

**Comment by dominikcz** [comment]
There is for example this plugin: https://marketplace.visualstudio.com/items?itemName=humao.rest-client. Not sure if it's responsible for syntax highlighting, but something definitely does that:

![obraz](https://user-images.githubusercontent.com/23698552/211402285-df69e7ae-3c15-4344-95cf-5d9bcdaf11e4.png)

Thank you for link, I'll try to face this challenge :)

**Comment by dominikcz** [comment]
OK, it looks like I've managed that task :)

The only problem now is that in order for the download script to work I had to correct two more links:

- link for astro changed, I guess it should be https://github.com/withastro/language-tools/blob/main/packages/vscode/syntaxes/astro.tmLanguage.src.yaml now.
- link for vue also changed, my guess is that it should be https://github.com/johnsoncodehk/volar/blob/master/vue-language-tools/vscode-vue/syntaxes/vue.tmLanguage.json now.

Also there are updates to additional files after build in  /packages/shiki/languages:
- astro.tmLanguage.json
- csharp.tmLanguage.json
- dart.tmLanguage.json
- latex.tmLanguage.json
- liquid.tmLanguage.json
- tex.tmLanguage.json
- v.tmLanguage.json

Should I include those additional changes in my PR?

**Comment by dominikcz** [comment]
it's merged and works as expected, so let's close this issue. Thank you
