### ISSUE TITLE
Catppuccin themes

### ISSUE THREAD

**Issue by jolheiser** [shikijs/shiki#411]
Would you be open to a PR for the [catppuccin themes](https://github.com/catppuccin)?

I wanted to ask before opening, as it seems like new themes are [no longer being encouraged](https://github.com/shikijs/shiki/blob/main/docs/themes.md#not-actively-adding-new-themes)?

However, I was hoping this may fall under the "rarely accept" category. 🙂

**Comment by octref** [comment]
I can consider it for 1.0 release, but please don't send a PR yet. Goal is to have a healthy mix of popular themes. Because themes are bundled for each download I don't want to encourage adding more themes.
