### ISSUE TITLE
Add class to comment 

### ISSUE THREAD

**Issue by boussadjra** [shikijs/shiki#416]
Is there a way to add a class name to the `comment` tokens in order to style them?, I need this in order to  change text direction for RTL languages

**Comment by muenzpraeger** [comment]
The only option (for now) would be build a [custom renderer](https://github.com/shikijs/shiki#custom-rendering-of-code-blocks).

Eventually this could be solved via a plugin, if the proposed architecture [makes it into the project](https://github.com/shikijs/shiki/pull/381).

**Comment by antfu** [comment]
It should be possible to use the new transformer API to so now: https://shiki.style/guide/transformers

**Comment by uncenter** [comment]
How would one use a transformer to add something like a `data-token` attribute containing the token type on each `<span>`?
