### ISSUE TITLE
Add ids and styles to LineOption type

### ISSUE THREAD

**Issue by Snapstromegon** [shikijs/shiki#427]
Currently it's possible to add `classes` to lines via the LineOption type in e.g. renderToHtml.
This is really useful, but I'd like to add arbitrary styles and ids too.

**Usecase:**
I'm a torchlight-style annotation system using shiki and I'd like to add things like custom add/remove markers or linenumber jumps. Currently this is not possible / requires classes for each variation.

**Proposed Solution:**
Expand the `LineOption` type to include an optional `ids` and `styles` field which behaves like the `classes` field.

If there is interest for this, I'd be willing to make a PR (or at least attempt it). I also saw that 1.0 is around the corner and there should be a feature freeze - should I wait with a PR until after 1.0?

**Comment by octref** [comment]
`id` makes sense. What is `styles` for? I'm ok for new features, just send them against `dev` branch

**Comment by Snapstromegon** [comment]
`styles` would e.g. allow setting CSS variables which could be used to reset CSS counters, replace the content of line numbers and so on.

**Comment by Snapstromegon** [comment]
A thought that came just now: How about giving the option to add arbitrary attributes to a line?
Also it might be great to have the option to style individual tokens, but at that point we're probably scratching at the point of custom renderers.

**Comment by muenzpraeger** [comment]
Potentially we can utilize for that [what I built for the plugin proposal](https://github.com/shikijs/shiki/blob/98b9be61d34a4d6f87750ce18fac7b8f4b057d5c/docs/plugins.md#example).

**Comment by Snapstromegon** [comment]
@muenzpraeger I like the basic idea of this plugin system, but I have some thoughts on it:

- plugins resetting and needing to be registered every time feels wrong - is there a technical reason for this? This makes shiki harder to use in cases where you want to reuse one highlighter with a plugin setup many times.
- the hooks are missing one for doing work before the code is tokenized and from the name I'd expected "before" to be called before tokenization
- does the before hook get all tokens by line, or just all tokens as a single array? In my usecase I want to modify the tokens of a line by adding styles to the line and removing a token at the same time

In general I don't know wether my usecase is completely covered by the plugin proposal.

**Comment by muenzpraeger** [comment]
> * plugins resetting and needing to be registered every time feels wrong - is there a technical reason for this? This makes shiki harder to use in cases where you want to reuse one highlighter with a plugin setup many times.

Good point. @octref also brought it up. I think there needs to be a balance between "want to reuse the same plugins all the time" vs. "want to use different plugins based on code block config".

Plugin setup can eventually be setup like this for the first use case (not beautiful)

```javascript
function setupHooks(highlighter) {
   return highlighter.usePlugin(coolPlugin);
}
```

But how should that look like if I have for example three code blocks that I want to transform, and only the second one should have a plugin applied? I thought about some register/unregister, but that's also a lot of complexity.

> * the hooks are missing one for doing work before the code is tokenized and from the name I'd expected "before" to be called before tokenization

What would you want to do before tokenization?

This hook gives you full access to the tokenized code, which is also a representation lines and included tokens. This is IMHO the place where modifications should be made.

> * does the before hook get all tokens by line, or just all tokens as a single array? In my usecase I want to modify the tokens of a line by adding styles to the line and removing a token at the same time

See above.

Having said that all, it's just a proposal, and some of that will be eventually just "core" to v1.

**Comment by Snapstromegon** [comment]
> > * plugins resetting and needing to be registered every time feels wrong - is there a technical reason for this? This makes shiki harder to use in cases where you want to reuse one highlighter with a plugin setup many times.
> 
> Good point. @octref also brought it up. I think there needs to be a balance between "want to reuse the same plugins all the time" vs. "want to use different plugins based on code block config".
> 
> Plugin setup can eventually be setup like this for the first use case (not beautiful)
> 
> ```js
> function setupHooks(highlighter) {
>    return highlighter.usePlugin(coolPlugin);
> }
> ```
> 
> But how should that look like if I have for example three code blocks that I want to transform, and only the second one should have a plugin applied? I thought about some register/unregister, but that's also a lot of complexity.

Two immediate ideas: `usePluginOnce()` and "create two highlighters" - one for each plugin configuration.

> > * the hooks are missing one for doing work before the code is tokenized and from the name I'd expected "before" to be called before tokenization
> 
> What would you want to do before tokenization?

One thing would be marker text that might screw with the language tokenization, that gets removed by a plugin. I think in general it probably wouldn't hurt to have such an event, so a plugin doesn't need to be registered for preprocessing before a code blocks gets into shiki and again for processing inside shiki.

> This hook gives you full access to the tokenized code, which is also a representation lines and included tokens. This is IMHO the place where modifications should be made.
> 
> > * does the before hook get all tokens by line, or just all tokens as a single array? In my usecase I want to modify the tokens of a line by adding styles to the line and removing a token at the same time
> 
> See above.
> 
> Having said that all, it's just a proposal, and some of that will be eventually just "core" to v1.

I'm asking, because the types table of the proposal shows tokens as a single dimensional array in the before event.

**Comment by antfu** [comment]
`lineOptions` has been removed in v1.0. You can use the new transformer API to do that with the full control of the generated HTML: https://shiki.style/guide/transformers
