### ISSUE TITLE
ANSI renderer bg color not showing

### ISSUE THREAD

**Issue by KevinBatdorf** [shikijs/shiki#432]
I was messing around with the ansi renderer and It's not rendering well in some cases (maybe with the background only?). Using the test content too. 

![Screen Shot 2023-02-03 at 5 26 40 PM](https://user-images.githubusercontent.com/1478421/216723031-e0ceac5f-311e-4e55-b2d4-a0542aeedb69.png)

![Screen Shot 2023-02-03 at 5 34 07 PM](https://user-images.githubusercontent.com/1478421/216723983-d1747882-7a0c-4aff-b96b-d84d5cd28256.png)

![Screen Shot 2023-02-03 at 5 35 01 PM](https://user-images.githubusercontent.com/1478421/216723992-083079f3-40da-451f-a3e8-974547d8869c.png)

**Comment by octref** [comment]
Can you please include the ANSI sequence in plaintext, the color expected and the color rendered?

**Comment by KevinBatdorf** [comment]
The top section I grabbed it from the test suite here: https://github.com/shikijs/shiki/blob/main/packages/shiki/src/__tests__/ansi.test.ts#L6

It should look like this (dracula terminal theme):

![Screen Shot 2023-02-05 at 12 18 21 PM](https://user-images.githubusercontent.com/1478421/216834104-f3861300-586c-4db0-9a72-948f79de1093.png)

But looks like this (dracula shiki theme):

![Screen Shot 2023-02-05 at 12 20 44 PM](https://user-images.githubusercontent.com/1478421/216834209-fcf48aca-5b87-4785-9fa8-976a8f2efe1e.png)

The bg color behind WARN is the issue

Exact snippet from my screenshots:

```
[0;32;1m❯[0m [0;32mpnpm[0m install --force[0m
[0;30;43m WARN [0m using --force I sure hope you know what you are doing[0m
Scope: all 6 workspace projects[0m
Lockfile is up to date, resolution step is skipped[0m
Packages: [0;32m+1038[0m[0m
[0;32m++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++[0m
```

**Comment by octref** [comment]
i'll take a look later but also @muenzpraeger

**Comment by muenzpraeger** [comment]
Just ran a quick test. The tokens are correctly identified.

```javascript
{
  value: ' WARN ',
  foreground: { type: 'named', name: 'black' },
  background: { type: 'named', name: 'yellow' },
  decorations: Set(0) {}
}
```

Now the thing is that the ANSI tokenizer returns only [a single `color` property](https://github.com/shikijs/shiki/blob/main/packages/shiki/src/ansiThemedTokenizer.ts#L44-L48). So the background color doesn't get passed back to the HTML rendering.

**Comment by octref** [comment]
`IThemedToken` will have a `bgColor` in 1.0's API.

**Comment by octref** [comment]
oops, that's right, i meant to mention @blake-mealey not @muenzpraeger, sorry!

**Comment by Zhengqbbb** [comment]
I found that it currently lacks the awesome feature of not supporting background color.

And I would like to know this feature will add in v1.0 ?  🤩
