### ISSUE TITLE
Highlighter's `loadLanguage` is buggy

### ISSUE THREAD

**Issue by banga** [shikijs/shiki#438]
Hi folks,

I was digging into https://github.com/banga/git-split-diffs/issues/43 and traced it down to me switching to `highlighter.loadLanguage` to load languages on demand to decrease start-up cost. It looks like the behavior of this method is pretty buggy.

Minimal repro here:
```ts
import shiki from 'shiki';

const highlighter = await shiki.getHighlighter({
    theme: 'nord',
    langs: [],
});

await highlighter.loadLanguage('md');

// Throws "Error: No grammar provided for <source.json>"
await highlighter.loadLanguage('json');
```

If you remove the `await highlighter.loadLanguage('md')` line above, this no longer throws.

I tried to dig into it and haven't figure out the source, but this block of code seemed suspicious to me: https://github.com/shikijs/shiki/blob/870acb063e1ca0c2fb8ec15dc0e3991684c33ae7/packages/shiki/src/registry.ts#L59-L65 is passing an async callback to `reduce`. Unless there's something really clever going on here, this seems incorrect. The `acc` will end up being a `Promise` object with some string properties set on to it. Anyway, fixing this (by replacing with a for loop) doesn't actually fix the issue.

**Comment by banga** [comment]
No I've just resorted to loading all of them in `getHighlighter` for now

**Comment by banga** [comment]
cc @muenzpraeger since this was introduced in #377

**Comment by Mokkapps** [comment]
@antfu FYI: I have the same problem using `shikiji`

**Comment by antfu** [comment]
@Mokkapps please create issue in Shikiji with a production

**Comment by Mokkapps** [comment]
> @Mokkapps please create issue in Shikiji with a production

It was a mistake I made during migrating to shikiji, so no need for a reproduction. Works fine, great job!
