### ISSUE TITLE
Accessibility issues in default theme

### ISSUE THREAD

**Issue by AndrewRayCode** [shikijs/shiki#441]
I suggest going through this https://developers.google.com/codelabs/devtools-cvd

Two issues with the default theme:

<img width="293" alt="Screen Shot 2023-03-06 at 6 14 48 PM" src="https://user-images.githubusercontent.com/79215/223302061-68b8544a-e28f-44d7-b30e-d1fc93e77ee9.png">
<img width="379" alt="Screen Shot 2023-03-06 at 6 14 43 PM" src="https://user-images.githubusercontent.com/79215/223302063-196f97b9-d21e-4141-8564-70e808831386.png">

I'm pretty surprised the main color, blue text on blue background, passes the accessibility check:

<img width="271" alt="Screen Shot 2023-03-06 at 6 17 29 PM" src="https://user-images.githubusercontent.com/79215/223302340-c6760252-df18-4276-af1d-6f0f8213bd2c.png">

It's right at the bottom of the acceptable range though (should be higher than 4.5).

**Comment by orta** [comment]
We don't create the themes in shiki, this is the nord theme: https://github.com/nordtheme/nord

**Comment by octref** [comment]
Yeah it's a theme issue. Open issue with their repo.
