### ISSUE TITLE
Add Windows Registry (.reg) support

### ISSUE THREAD

**Issue by KevinBatdorf** [shikijs/shiki#450]
I could set up a PR if you are OK to accept this grammar.

https://github.com/mihai-vlc/reg-vscode/blob/master/syntaxes/reg.tmLanguage

![reg](https://user-images.githubusercontent.com/1478421/227812304-e6d61f11-53a9-4885-95c5-85455873d911.png)

**Comment by orta** [comment]
Sure

**Comment by octref** [comment]
Sure, go ahead!
