### ISSUE TITLE
NPM package needs to be republished?

### ISSUE THREAD

**Issue by nathanpeck** [shikijs/shiki#458]
I just ran into an issue with Shiki not having an alias for `Dockerfile`. It looks like this code was merged some time ago, back in January:
https://github.com/shikijs/shiki/pull/410/files

However, when I view the contents of the latest `0.14.1` package from NPM this change is not reflected yet.

I can download the latest `0.14.1` version straight off NPM, open up `dist/index.js` and on line 255 I see that the language list does not have the alias that was added in #410:

```js
  {
    id: "docker",
    scopeName: "source.dockerfile",
    path: "docker.tmLanguage.json",
    samplePath: "docker.sample"
  },
```

The source code looks good in the repo:

https://github.com/shikijs/shiki/blob/main/packages/shiki/src/languages.ts#L377-L383

But for some reason its just not in the latest version on NPM yet.

In the meantime I've patched it in my code with a hack:

```js
// Patch an issue where it doesn't recognize
// Dockerfiles as Dockerfiles because there is no alias
const DOCKER_LANG = BUNDLED_LANGUAGES.find((lang) => {
  return lang.id == 'docker';
})
if (DOCKER_LANG) {
  DOCKER_LANG.aliases = ['dockerfile']
}
```

Is there a build issue that is causing the #410 change to not make it into the build published to NPM? Or has the package just not been republished to NPM in some time?

**Comment by octref** [comment]
Fixed in the latest release.
