### ISSUE TITLE
The div.language-id element is not rendering when calling `codeToHtml`

### ISSUE THREAD

**Issue by craxrev** [shikijs/shiki#460]
Currently the div.language-id element that contains the `langId` is not rendering when using `codeToHtml`, I can see when it should be rendered here:

https://github.com/shikijs/shiki/blob/7000a1ebccdba77acc33a2402b8fde10d20d3a3f/packages/shiki/src/renderer.ts#L47

but I don't see the `langId` being passed in the `renderToHtml` call in the `getHighlighter` `codeToHtml` function:

https://github.com/shikijs/shiki/blob/7000a1ebccdba77acc33a2402b8fde10d20d3a3f/packages/shiki/src/highlighter.ts#L175-L180

Or is the call deliberately made that way?

**Comment by octref** [comment]
Good catch! Feel free to send a PR.

**Comment by antfu** [comment]
It should be fixed with v1.0, #557
