### ISSUE TITLE
Theme request: New default VS Code 'modern' themes

### ISSUE THREAD

**Issue by jasongerbes** [shikijs/shiki#467]
Given that the default VS Code light and dark themes themes have changed in the latest release, would you consider adding 'Dark Modern' and 'Light Modern' to the built-in theme options?

As per the VS Code release notes for April 2023:

> ### [New default Color Themes](https://code.visualstudio.com/updates/v1_78#_new-default-color-themes)
> New 'Dark Modern' and 'Light Modern' themes replace 'Dark+' and 'Light+' as the new default dark and light color themes.

**Comment by octref** [comment]
Will make it part of 1.0.

**Comment by antfu** [comment]
Hey, thanks for your contribution! With the [recent rewrite of v1.0](https://github.com/shikijs/shiki/pull/557), we have moved the themes out of this repository. We generally suggest you [loading the theme locally](https://shiki.style/guide/load-lang) to move forward. If you believe this is the theme that is widely used, you can send an issue or PR to this repo: https://github.com/shikijs/textmate-grammars-themes

Thank you!
