### ISSUE TITLE
Add human-readable name to the `BUNDLED_LANGUAGES`

### ISSUE THREAD

**Issue by lawvs** [shikijs/shiki#469]
Now the `BUNDLED_LANGUAGES` only includes the language id that is not convenient to display to the users.

We can put the human-readable name at the beginning of the `aliases` field, similar to how it's done in VSCode, like this

```ts
const BUNDLED_LANGUAGES = [
  {
    id: 'typescript',
    scopeName: 'source.ts',
    path: 'typescript.tmLanguage.json',
    aliases: ['TypeScript', 'ts']
    //         ^
  },
]
```

Or adding a `name` field directly to `BUNDLED_LANGUAGES` is also a feasible solution.

If you think this idea is good, I would be more than willing to submit a PR for it.

---

## References

VSCode Extension API [contributes.languages](https://code.visualstudio.com/api/references/contribution-points#contributes.languages)

> You can contribute a human-readable using the `aliases` field. The **first item** in the list will be used as the human-readable label.

![Screenshot 2023-05-11 at 2 20 00 AM](https://github.com/shikijs/shiki/assets/18554747/17c39442-6378-45b3-90fc-6df65b0186a5)

![Screenshot 2023-05-11 at 2 17 56 AM](https://github.com/shikijs/shiki/assets/18554747/a0108266-bcb4-41ff-9953-5ef563b9791c)

The language types inside of VSCode
```ts
// https://github.com/microsoft/vscode/blob/efb49cc271d6eea5634ac395e36e1e4cd108a447/src/vs/editor/common/languages/language.ts#L14-L27
export interface ILanguageExtensionPoint {
	id: string;
	extensions?: string[];
	filenames?: string[];
	filenamePatterns?: string[];
	firstLine?: string;
	aliases?: string[];
	mimetypes?: string[];
	configuration?: URI;
	/**
	 * @internal
	 */
	icon?: ILanguageIcon;
}
```

**Comment by octref** [comment]
I think it's better to add an explicit `displayName`. Do you want to send a PR? Otherwise I can do it too.

**Comment by lawvs** [comment]
Fixed by https://github.com/shikijs/shiki/pull/470
