### ISSUE TITLE
Remove the default loading of `nord` theme when `getHighlighter`

### ISSUE THREAD

**Issue by kricsleo** [shikijs/shiki#473]
If `theme` or `themes` is empty when using `getHighlighter`, then the `nord` theme will be loaded by default. This results in an unnecessary theme load for situations where the theme needs to be loaded dynamically (or an unnecessary theme resource request in the browser environment).
For example:

```ts
// Here there will be an unwanted `nord` theme load.
// Because later the required theme will be loaded dynamically depending on the situation.
const highlighter = await shiki.getHighlighter({})

export async function highlight(code, lang, theme) {
  // Here the real theme will be loaded, e.g. `github-dark`
  await highlighter.loadTheme(theme)
  return highlighter.codeToHtml(code, { lang, theme })
}
```

Can we remove the default theme logic here? Or a way to disable it in the above situations. Thanks :)

https://github.com/shikijs/shiki/blob/b8e88e68d6e1923d57702268deaf922143abd55d/packages/shiki/src/highlighter.ts#L43-L45

(Willing to contribute a PR for this)

**Comment by orta** [comment]
Give that this would be a massive breaking change, it probably shouldn't happen this way unless it ends up in the 1.0 changes in https://github.com/shikijs/shiki/issues/424 and is very well documented

Perhaps passing null could be accepted as the theme and have this behavior instead

**Comment by kricsleo** [comment]
I agree that removing the logic here directly may produce incompatible changes, although the documentation doesn't explicitly mention that the default theme will be loaded, it may be the default behavior when the user relies on not passing `theme`.

If, as you say, we remove the loading of the default theme when the user is shown using `theme: null` or `themes: null`, would this be acceptable as a patch version of `v0.14`?

**Comment by orta** [comment]
Sure, allowing specifically for null is something I'd be OK with merging (as long as that's documented in the jsdoc)
