### ISSUE TITLE
Cannot read properties of undefined (reading 'VSCODE_TEXTMATE_DEBUG')

### ISSUE THREAD

**Issue by kgarchie** [shikijs/shiki#474]
I get this error when trying to use shiki in nuxt3. I do not know the cause, I tried adding that environment variable, but it didn't work.

I've recreated the error here https://stackblitz.com/edit/github-whzftm?file=pages%2F%5B...slug%5D.vue

**Comment by jwhazel** [comment]
Running into this same issue (Nuxt 3.5) and found a workaround at least for now. For whatever reason an .env variable doesn't work, but setting it manually in Vite through nuxt.config.ts does.

```
export default defineNuxtConfig({
  vite: {
    define: {
       'process.env': {
          VSCODE_TEXTMATE_DEBUG: false,
       },
    },
  },
});
```
Credit: https://github.com/Kingwl/monaco-volar/issues/12#issuecomment-1346969175. There is some more chatter on the Nuxt issue linked there but I didn't dig too deep into it. I'm not sure what the correct solution is, but it seems like it's probably outside the scope of Shiki.

**Comment by kgarchie** [comment]
> Running into this same issue (Nuxt 3.5) and found a workaround at least for now. For whatever reason an .env variable doesn't work, but setting it manually in Vite through nuxt.config.ts does.
> 
> ```
> export default defineNuxtConfig({
>   vite: {
>     define: {
>        'process.env': {
>           VSCODE_TEXTMATE_DEBUG: false,
>        },
>     },
>   },
> });
> ```
> Credit: https://github.com/Kingwl/monaco-volar/issues/12#issuecomment-1346969175. There is some more chatter on the Nuxt issue linked there but I didn't dig too deep into it. I'm not sure what the correct solution is, but it seems like it's probably outside the scope of Shiki.
> 

Thank you so much, will try this.

**Comment by octref** [comment]
This is more of a Nuxt-bundling-onigasm issue rather than Shiki issue. Closing.
