### ISSUE TITLE
Problem with GraphQL Syntax Highlighting

### ISSUE THREAD

**Issue by lukecd** [shikijs/shiki#481]
I noticed a bug with syntax highlighting of GraphQL queries where strings that immediately follow a [ are not properly colored.

If you look at

https://docs.bundlr.network/developer-docs/graphql#owners

You'll notice this GraphQL.

The first string, the one following the [ is grey, while the second string is green as it should be. If I delete the [ before the first string, it ends up highlighted green as it should be. Also if I add a space after the [, the string is green as it should be.

My guess is that there's a bug in the file graphql.tmLanguage.json, but I'm not sure.

```graphql
query getByOwner {
	transactions(owners: ["0xBcb812C6e26F4F0F78Bd7B6222461FF24F2942AE", "0xaC568a981B1370B2e1bAA8cE30BD5AC9E28C572D"]) {
		edges {
			node {
				id
				address
			}
		}
	}
}
```

**Comment by orta** [comment]
This is an issue with the .tmlanguage file for graphql, and not a shiki issue - you want to discuss this here: https://github.com/prisma-labs/vscode-graphql
