### ISSUE TITLE
[Feature request]: Add support for `URL`

### ISSUE THREAD

**Issue by xsjcTony** [shikijs/shiki#498]
Please add support for URL, can be used to highlight `GET` request samples

e.g.
```
https://api.test.com/v1/user/25?info=123
```
```
?query1=value1&query2=value2
```

**Comment by antfu** [comment]
Hey, thanks for your contribution! With the [recent rewrite of v1.0](https://github.com/shikijs/shiki/pull/557), we have moved the grammars out of this repository. We generally suggest you [loading the grammar locally](https://shiki.style/guide/load-lang) to move forward. If you believe this is the language that is widely used, you can send an issue or PR to this repo: https://github.com/shikijs/textmate-grammars-themes

Thank you!
