### ISSUE TITLE
Decoration API

### ISSUE THREAD

**Issue by octref** [shikijs/shiki#5]
Offer a decoration API that allows marking specific ranges with:

- bg color
- font settings
- text decorations
- links

This is easy to use programmatically.
The hard problem is how should the original Markdown look like.

**Comment by octref** [comment]
Use cases:

- Use italic font for a specific range
-

**Comment by EldoranDev** [comment]
Hi, are there currently any plans to actually implement this feature ?

**Comment by octref** [comment]
I wanted to gather some feedback before proceeding, because @Atinux asked for this. But it seems he is busy. I'll ask again.

**Comment by wesbos** [comment]
Would love to see this : )

**Comment by Ir1d** [comment]
hi @octref , any plans to bring these features in? They look amazing

**Comment by orta** [comment]
I wonder if we make the highlighting API be consistent with  gatsby-remark-prismjs - https://github.com/andrewbranch/gatsby-remark-vscode#line-highlighting

**Comment by octref** [comment]
Thinking about something like this API below. How each markdown parser would like to integrate with the API is up to them.
@EldoranDev @jlkiri @stefanprobst @Enter-tainer I see each of you have written a remark + shiki plugin — would the API below enable you do what https://github.com/andrewbranch/gatsby-remark-vscode is doing?

```ts
interface BaseLineDecoration {
  /**
   * The line to apply decoration to.
   * Line is 0 based.
   */
  line: number
}

/**
 * Render line with specified background color
 */
export interface LineBgColorDecoration extends BaseLineDecoration {
  /**
   * 3/6/8 digit hex code like `#fff` or color like `cadetblue`.
   */
  bgColor: string
}

/**
 * Render line with line number
 */
export interface LineNumberDecoration extends BaseLineDecoration {
  /**
   * Line number such as `1` or `01`
   */
  lineNumber: string
}

/**
 * A decoration applied to a line
 */
export type LineDecoration = LineBgColorDecoration | LineNumberDecoration

interface BaseTokensDecoration {
  /**
   * The range that includes all tokens. Only tokens that fully
   * fall into the range will be matched.
   * Multi-line is not supported.
   * Line is 0 based.
   * `startIndex` is inclusive and `endIndex` not inclusive.
   */
  range: {
    line: number
    startIndex: number
    endIndex: number
  }
}

/**
 * Render matched tokens with `<a>` tag
 *
 * Cannot overlap with other link decorations.
 */
export interface TokensLinkDecoration extends BaseTokensDecoration {
  /**
   * `href` value of the link
   */
  link: string
}

/**
 * Render matched tokens with specified font style
 */
export interface TokensFontStyleDecoration extends BaseTokensDecoration {
  /**
   * The font style
   */
  fontStyle: FontStyle
}

/**
 * Render matched tokens with specified background color
 */
export interface TokensBgColorDecoration extends BaseTokensDecoration {
  /**
   * 3/6/8 digit hex code like `#fff` or color like `cadetblue`.
   */
  bgColor: string
}

/**
 * A decoration applied to tokens in the matched range
 */
export type TokensDecoration =
  | TokensLinkDecoration
  | TokensFontStyleDecoration
  | TokensBgColorDecoration

export interface HtmlRendererOptions {
  langId?: string
  fg?: string
  bg?: string

  /**
   * Decorations applied to lines
   */
  lineDecorations?: LineDecoration[]

  /**
   * Decorations applied to tokens
   */
  tokensDecorations?: TokensDecoration[]
}
```

**Comment by jlkiri** [comment]
@octref I haven't touched `remark` for a long time. If there is a way to get lines I want to highlight from `remark`, then yes, I would use that information for each code block and pass it to something like `highlighter.codeToHtml`

**Comment by orta** [comment]
For shiki-twoslash, I ended up re-using @andrewbranch's code-fencing syntax from [gatsby-vscode-remark](https://github.com/andrewbranch/gatsby-remark-vscode#line-highlighting)

https://github.com/microsoft/TypeScript-website/blob/54415373f08ef8d707c0dca799b7a454d56ec754/packages/shiki-twoslash/src/parseCodeFenceInfo.ts#L1

**Comment by muenzpraeger** [comment]
Can't we potentially solve this via #380?

**Comment by antfu** [comment]
I would suggest the core should not have an opinion on how code-fence meta string should be handled. Instead, allowing [transformers](https://shiki.style/guide/transformers) to provide their own handling
