### ISSUE TITLE
feat: make a ziglang support

### ISSUE THREAD

**Issue by xihale** [shikijs/shiki#500]
maybe you can take a reference of [the extension of highlight.js support for zig](https://github.com/sksat/highlightjs-zig/blob/master/src/languages/zig.js)

**Comment by orta** [comment]
You're welcome to follow the guide on adding a new language: https://github.com/shikijs/shiki/blob/main/docs/languages.md

**Comment by xihale** [comment]
I am trying to do that, thanks!

**Comment by octref** [comment]
Not sure why you closed your PR, but I did it at fc13a73a5ca48810db9175da84eb0445c5bfa5ff
