### ISSUE TITLE
Vue directives and interpolation highlighting does not work

### ISSUE THREAD

**Issue by Demivan** [shikijs/shiki#503]
Vue directives and interpolation highlighting are handled by injections in https://github.com/vuejs/language-tools/blob/master/packages/vscode-vue/syntaxes/vue-directives.json and https://github.com/vuejs/language-tools/blob/master/packages/vscode-vue/syntaxes/vue-interpolations.json.

Shiki does not have those injections, so highlighting does not work.

**Comment by antfu** [comment]
It should be fixed with v1.0, #557
