### ISSUE TITLE
Infinite Loop when langs is Not Provided in Shiki Highlighter Configuration

### ISSUE THREAD

**Issue by KentonParton** [shikijs/shiki#506]
### Description
When using the shiki library to instantiate a highlighter in a React application, the application falls into an infinite loop if the langs property is not defined. According to the documentation, when langs is not specified, all languages should be loaded. This is a functionality I want to use, but I am currently encountering an issue.

### Code Snippet
Below is the code snippet demonstrating the problem. If the langs array is removed from the configuration object passed to shiki.getHighlighter, an infinite loop occurs.

```javascript
import { useEffect, useState } from "react";
import themeNord from "shiki/themes/nord.json";
import langTS from "shiki/languages/typescript.tmLanguage.json";
import langTSX from "shiki/languages/tsx.tmLanguage.json";
const shiki = require("shiki");
shiki.setCDN("https://unpkg.com/shiki/");

const CodeBlock = ({ children }) => {
  useEffect(() => {
    (async function () {
      const highlighter = await shiki.getHighlighter({
        theme: "nord",
        themes: [themeNord],
        // When removed, shiki goes into infinite loop
        langs: [
          {
            id: "typescript",
            scopeName: langTS.scopeName,
            grammar: langTS,
            aliases: ["ts"]
          },
          {
            id: "tsx",
            scopeName: langTSX.scopeName,
            grammar: langTSX
          }
        ]
      });
      const highlightedCode = highlighter.codeToHtml(
        `console.log('shiki');`,
        "tsx"
      );
      console.log(highlightedCode);
    })();
  }, []);

  return <div></div>;
};

export default CodeBlock;
```

### Reproduction Steps
1. Access the full codesandbox example [here](https://codesandbox.io/s/admiring-frog-8jnnsx?file=/src/CodeBlock.jsx).
2. Remove the langs property from the shiki.getHighlighter configuration.
3. Observe the infinite loop in the application.

### Expected Behavior
When langs is not provided, I expect all languages to be loaded without causing an infinite loop and the HTML displayed in the console.

### Request
Could you please help me understand what might be causing this issue, and provide guidance on how to resolve it? Thank you!

**Comment by antfu** [comment]
It should be fixed in 1.0, #557. If not, please create a new issue with a minimal reproduction. Thanks!
