### ISSUE TITLE
Tokens includeExplanation typings mismatch

### ISSUE THREAD

**Issue by ChcJohnie** [shikijs/shiki#509]
## Description

While trying to optimize performance of great shiki we encountered confusing typings.
`ThemedTokenizer` and [types](https://github.com/shikijs/shiki/blob/e4d08552d20fa808a28ff9967f0604c934c8060e/packages/shiki/src/types.ts#L271) both states default of `false` for `includeExplanation` options.
But [highlighter.codeToThemeTokens](https://github.com/shikijs/shiki/blob/e4d08552d20fa808a28ff9967f0604c934c8060e/packages/shiki/src/highlighter.ts#L150) is overriding `includeExplanation` default to `true`, while being typed with mentioned default `false` thus being wrongly docummented while accessed in code.

## Expected behaviour
Either codeToThemeTokens having `includeExplanation: false` default (would make sense,  its performance save was mindblowing), or fixing types to have correct typing (different defaults) for both `ThemedTokenizer` and `highlighter.codeToThemeTokens` (eg. for compatibility reasons I can see).

Guess should be quick change, but does not feel aligned with project enough to pick solution myself and create PR

**Comment by ShogunPanda** [comment]
I second this. I just incurred into this, sob.
