### ISSUE TITLE
How to stop shiki from escaping HTML characters

### ISSUE THREAD

**Issue by SkyTheCodeMaster** [shikijs/shiki#516]
I'm trying to use shiki for highlighting some code samples, however I'm running into an issue where it is turning `>` into `&gt;`, which is
obviously undesirable for highlighting code samples.
https://i.skystuff.cc/LXFZ2azAAr80.png

I'm highlighting the code like this:
```js
const code = highlighter.codeToHtml(block.innerHTML, { lang: language });
block.innerHTML = code;
```
where `language` is just `python`.

**Comment by SkyTheCodeMaster** [comment]
I can mildly alleviate this by just replacing `&gt;` with `>`, but in cases where shiki highlights the middle of it, this no longer works.

**Comment by Gerrit0** [comment]
I'm pretty sure you should be passing `block.innerText` into the highlighter rather than `block.innerHTML`. It's not shiki doing that replacement, it's the browser appropriately including the escape.

**Comment by SkyTheCodeMaster** [comment]
That is incorrect. `innerText` will escape shiki's highlighting, as it should.
https://i.skystuff.cc/BYwMvOPV0Vz3.png

**Comment by Gerrit0** [comment]
There's a reason I specified "input" - the output, of course, should still be given to innerHTML

**Comment by SkyTheCodeMaster** [comment]
Ah, I misread, but there is nothing wrong with the input either, if I block my shiki script from loading, you can see that the input is perfectly fine (The `>` is not html encoded)
https://i.skystuff.cc/7r4usL9PlNUs.png

**Comment by Gerrit0** [comment]
![image](https://github.com/shikijs/shiki/assets/19329837/b7a275fe-87e1-46ca-948a-cfad6c12adbb)

The `>` *is* html encoded, just because it's displayed as `>` doesn't mean that `innerHTML` won't give you an encoded entity.

**Comment by SkyTheCodeMaster** [comment]
I'll try that out in the morning then, that could very well be the cause of my issues.

**Comment by SkyTheCodeMaster** [comment]
Yep, that fixes it, thanks!
