### ISSUE TITLE
Proposal: to add grammar support for `Poetry`

### ISSUE THREAD

**Issue by endymion1818** [shikijs/shiki#524]
This one is a bit of a left field but hear me out.

I write articles about code. I also love writing about poetry. But it's very challenging to format poetry in the way that the author might intend it on the web. For examples, look particularly at https://deliciousreverie.co.uk/posts/poems-about-time/#keats---ode-on-a-grecian-urn (where I use shiki's `plaintext grammar`) and also the comment here: https://hokku.wordpress.com/

> Here is one of the unfortunate results (by the way, my editing software steadfastly refuses to put all the verses in these books into the line arrangements the authors used, 

The trouble with poetry is that it's not uniform. I cannot just add a rule to add a bit of margin to the start of every paragraph, because it won't work for each poem. 

My pet peeve is poetry that breaks lines where authors didn't intend there to be one, which is why I decided to use Shiki in the first place; so that I can have overflow scroll right and left, as well as indentation as the author intended at the start of each line.

In fact, there are many reasons to use Shiki for poetry, not just for code.

What's your opinion, maintainers? I'm happy to write a PR myself if you give the go-ahead.

**Comment by antfu** [comment]
Hey, thanks for your contribution! With the [recent rewrite of v1.0](https://github.com/shikijs/shiki/pull/557), we have moved the grammars out of this repository. We generally suggest you [loading the grammar locally](https://shiki.style/guide/load-lang) to move forward. If you believe this is the language that is widely used, you can send an issue or PR to this repo: https://github.com/shikijs/textmate-grammars-themes

Thank you!
