### ISSUE TITLE
WordPress specific grammars

### ISSUE THREAD

**Issue by KevinBatdorf** [shikijs/shiki#529]
There's a WP vs code extension that is pretty new.

https://marketplace.visualstudio.com/items?itemName=matthiashunt.wordpress-syntax-highlighter

Syntaxes:
https://github.com/MatthiasHunt/wordpress-syntax-highlighter/tree/main/syntaxes

I think they would be useful to add, but how would you suggest naming them?

**Comment by KevinBatdorf** [comment]
Would they even work or do they need to be combined with php/css/html somehow?

**Comment by antfu** [comment]
Hey, thanks for your contribution! With the [recent rewrite of v1.0](https://github.com/shikijs/shiki/pull/557), we have moved the grammars out of this repository. We generally suggest you [loading the grammar locally](https://shiki.style/guide/load-lang) to move forward. If you believe this is the language that is widely used, you can send an issue or PR to this repo: https://github.com/shikijs/textmate-grammars-themes

Thank you!
