### ISSUE TITLE
Add a new Fortran grammar

### ISSUE THREAD

**Issue by uncenter** [shikijs/shiki#533]
Looks like the Fortran grammar [was removed a few years ago (#111)](https://github.com/shikijs/shiki/pull/111) (because the repository was deleted and grammar removed) but we could use grammars from https://github.com/fortran-lang/vscode-fortran-support/tree/main/syntaxes instead?

**Comment by uncenter** [comment]
Trying to make a PR for this but I have a dillema for sorts... there are two grammars for Fortran, the fixed form grammar and the free form grammar. Fixed form is for older versions of fortran, and free form for the modern versions.

This is what I have right now:

```ts
export const githubGrammarSources = {
  // ...
  ['fortran', 'https://github.com/fortran-lang/vscode-fortran-support/blob/main/syntaxes/fortran_free-form.tmLanguage.json'],
}
export const languageAliases = {
  // ...
  fortran: ['f90', 'f95', 'f03', 'f08', 'f18', 'fpp'],
}
```

But I'm wondering if I should (also) do something like this:
```ts
export const githubGrammarSources = {
  // ...
  ['fortran-fixed', 'https://github.com/fortran-lang/vscode-fortran-support/blob/main/syntaxes/fortran_fixed-form.tmLanguage.json'],
}
export const languageAliases = {
  // ...
  'fortran-fixed': ['f', 'f77', 'for'],
}
```

**Comment by uncenter** [comment]
I gave it a shot a while back and I couldn't get it to properly syntax highlight. I would appreciate if someone else could take a look!

**Comment by GitMensch** [comment]
Like with COBOL it would be good to have separate grammars. If I remember correct a grammar can include/extend another one, which then would be a reasonable thing to do here.

**Comment by antfu** [comment]
Hey, thanks for your contribution! With the [recent rewrite of v1.0](https://github.com/shikijs/shiki/pull/557), we have moved the grammars out of this repository. We generally suggest you [loading the grammar locally](https://shiki.style/guide/load-lang) to move forward. If you believe this is the language that is widely used, you can send an issue or PR to this repo: https://github.com/shikijs/textmate-grammars-themes

Thank you!

**Comment by uncenter** [comment]
I've added it in https://github.com/shikijs/textmate-grammars-themes/pull/18 :)
