### ISSUE TITLE
[Feature Request] Add plain text support.

### ISSUE THREAD

**Issue by zhuozhiyongde** [shikijs/shiki#534]
As the title suggests, shiki is being used as the code rendering module for my blog, but when I specify `text` language, it will not render because it cannot recognize this language. I hope to add support for plain text and further, perhaps render all unknown language formats in a form that can be displayed as plain text.

**Comment by nova1751** [comment]
Actually, if you don't specify the code block lang option,the shiki will return the original code block format.Hope this can help you.

**Comment by antfu** [comment]
We treat these languages are plain text: 
https://github.com/shikijs/shiki/blob/c79153830994df9db82bc2c97169fdd6f8c3cf3d/packages/core/src/utils.ts#L15-L22
