### ISSUE TITLE
Does shiki support fortran?

### ISSUE THREAD

**Issue by liuguanfu1120** [shikijs/shiki#541]
It seems that shiki does not support fortran?
If so, I just wondering why it does not support fortran.

**Comment by liuguanfu1120** [comment]
It seems that shiki does not support fortran?
If so, I just wondering why it does not support fortran.

**Comment by uncenter** [comment]
See #533.

**Comment by antfu** [comment]
Hey, thanks for your contribution! With the [recent rewrite of v1.0](https://github.com/shikijs/shiki/pull/557), we have moved the grammars out of this repository. We generally suggest you [loading the grammar locally](https://shiki.style/guide/load-lang) to move forward. If you believe this is the language that is widely used, you can send an issue or PR to this repo: https://github.com/shikijs/textmate-grammars-themes

Thank you!

**Comment by uncenter** [comment]
I've added it in https://github.com/shikijs/textmate-grammars-themes/pull/18 :)
