### ISSUE TITLE
Potential vscode-oniguruma issue when running shiki on client-side with docusaurus 3.0 and webpack 5

### ISSUE THREAD

**Issue by axmmisaka** [shikijs/shiki#542]
We are a open-source organisation and we are migrating our documentation to docusaurus 3.0. We only have TextMate grammar definition and Shiki appears to be the best choice for syntax highlighting.

I am aware of the existence of https://github.com/shikijs/twoslash, but it runs on server side and I am wondering if it is possible to have something that runs on the client side.

I have written a very small client-side wrapper like this (the rest is docusaurus 3.0 from docuaurus.new which I run on GH codespaces; this file is under `src/components/Shiki/index.ts):
```ts
import * as shiki from 'shiki';

import react from 'react';

export const ShikiHighlight = ({ lang, rawcode, props }: {
  lang: string;
  rawcode: string;
  props: unknown;
}) => {
  const [code, setCode] = react.useState<string>('');

  react.useEffect(() => {
    (async () => {
      try {
        // const onig = await fetch("https://cdn.jsdelivr.net/npm/vscode-oniguruma@2.0.1/release/onig.wasm");
        // shiki.setWasm(onig);
        const highlighter = await shiki.getHighlighter({ theme: 'nord' });
        setCode(highlighter.codeToHtml(rawcode, { lang }));
      } catch (e) {
        console.log(e);
      }
    })();
  }, [lang, rawcode]);

  return <div dangerouslySetInnerHTML={{ __html: code }} />;
};
```

Upon using this component, it shows 
`WebAssembly: Response has unsupported MIME type 'text/html; charset=utf-8' expected 'application/wasm'` on Firefox, or `Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.` on chromium.

Copying `onig.wasm` to `/static` wouldn't fix this issue.

If I fetch and specify `vscode-oniguruma` wasm instead (that is, removing the commented lines), shiki will still error:
`import object field '_embind_register_constant' is not a Function` on Firefox, or `LinkError: WebAssembly.instantiate(): Import #3 module="env" function="_embind_register_constant": function import requires a callable` on Chromium.

Finally, if I use `vscode-oniguruma@1.6.2` as instructed here: https://github.com/shikijs/shiki/issues/382#issuecomment-1340987499, it will instead show `LinkError: WebAssembly.instantiate(): Import #4 module="env" function="setTempRet0": function import requires a callable`.

I am puzzled. Is this the expected behaviour when trying to run shiki on browser with oniguruma wasm, or is there anything related to shiki which I did wrong? I hope that I asked this question at the correct place, and I apologize if I didn't.

**Comment by maheshmnj** [comment]
@axmmisaka Any success using shiki in docusaurus?

**Comment by axmmisaka** [comment]
> @axmmisaka Any success using shiki in docusaurus?

We transitioned to https://github.com/antfu/shikiji for now.

**Comment by weisjohn** [comment]
@axmmisaka have you updated back to Shiki now that Shikiji has be merged back?

**Comment by axmmisaka** [comment]
> @axmmisaka have you updated back to Shiki now that Shikiji has be merged back?

No, because I am lazy, but I expect the wasm loading issue will be gone when we transition.
