### ISSUE TITLE
can someone add monicelli highlight?

### ISSUE THREAD

**Issue by PEPPEsant01** [shikijs/shiki#546]
can someone that know monicelli language https://github.com/esseks/monicelli add this feature?
i want learn monicelli and his supercazzole, but i need a highlight system for this language.
i love this language because is designed by an italian with the deep meaning of monicelli's films and supercazzole.
can i use this tool to learn monicelli language?
thanks for all from italy.

**Comment by antfu** [comment]
Hey, thanks for your contribution! With the [recent rewrite of v1.0](https://github.com/shikijs/shiki/pull/557), we have moved the grammars out of this repository. We generally suggest you [loading the grammar locally](https://shiki.style/guide/load-lang) to move forward. If you believe this is the language that is widely used, you can send an issue or PR to this repo: https://github.com/shikijs/textmate-grammars-themes

Thank you!
