### ISSUE TITLE
Move grammars/themes update script as a seperate package

### ISSUE THREAD

**Issue by antfu** [shikijs/shiki#551]
Currently, we serve all those grammar and themes update logics inside this repo and create quite some noise to the commit history. And since those themes can also be reused by other integrations like Monaco editors, it would be nice to extra those logics as separate packages so they can be better reused and well organized.

I actually already did the work by porting some scripts from Shiki:
- https://github.com/antfu/textmate-grammars-themes/tree/main/packages/tm-grammars
- https://github.com/antfu/textmate-grammars-themes/tree/main/packages/tm-themes

The rewrite would also help us to obtain more info and properly credit the original authors with their [licenses](https://github.com/antfu/textmate-grammars-themes/blob/main/packages/tm-grammars/NOTICE).

Meanwhile, the packages are automatically upgraded and released. So if we end up migrating to using it as the source, we only need to bumper the dependencies periodically to get the latest grammar/themes.

I would prepare the PR if the team agreed on that. I am also open to transferring that repo into this org.

Related:
- https://github.com/shikijs/shiki/issues/57#issuecomment-1407411941

**Comment by orta** [comment]
👍🏻
