### ISSUE TITLE
`julia-repl`: formatted output from repl

### ISSUE THREAD

**Issue by lazarusA** [shikijs/shiki#569]
### Clear and concise description of the problem

This feature will expand the current support for the `julia` language by adding support for repo-like output.

### Suggested solution

The current solution to this is coded here:

https://github.com/highlightjs/highlight.js/blob/58dc5961f6f2bb8bc8bb1e7ce39f268a2fdd874f/src/languages/julia-repl.js

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
Grammars are maintained at https://github.com/shikijs/textmate-grammars-themes. And we generally prefer PRs to improve them as we, the maintainers, can't be experts in every language.
