### ISSUE TITLE
`Julia-ansi`: combine ansi + language (it should work any language I suppose)

### ISSUE THREAD

**Issue by lazarusA** [shikijs/shiki#570]
### Clear and concise description of the problem

When using VitePress to render code this is possible:

````shell
```julia
julia> printstyled("This should be in bold light cyan.", color=:light_cyan, bold=true)
�[96m�[1mThis should be in bold light cyan.�[22m�[39m
```
````
but only the language highlighting works, whereas 

````shell
```ansi
julia> printstyled("This should be in bold light cyan.", color=:light_cyan, bold=true)
�[96m�[1mThis should be in bold light cyan.�[22m�[39m

```
````
would only highlight the ansi bits and the language-coding colours are gone. Hence the feature request or rather question: Is there a way to combine both? ansi + language?

### Suggested solution

Not a solution, but maybe some possible syntax could be (if this is at all possible)

````shell
```ansi-julia
julia> printstyled("This should be in bold light cyan.", color=:light_cyan, bold=true)
�[96m�[1mThis should be in bold light cyan.�[22m�[39m

```
````

or maybe better

````shell
```julia-ansi
julia> printstyled("This should be in bold light cyan.", color=:light_cyan, bold=true)
�[96m�[1mThis should be in bold light cyan.�[22m�[39m

```
````

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
I honestly feel this is quite a nitch use case. And in the example you gave, there are parts that are not actually the Julia language itself; directly passing it to the grammar might mess up the state machine to generate the incorrect results. In your case, I would suggest you to split your text into multiple snippets, passing to Shiki separately to get the themed tokens and then merge them into one. It's also possible to do it through a user-land transformer.

I am closing this as the request itself is probably out-of-scope. Thanks for bringing this up!
