### ISSUE TITLE
How do I implement word-wrapping?

### ISSUE THREAD

**Issue by vcheeze** [shikijs/shiki#575]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

First off, this isn't a bug but I couldn't find an appropriate forum on which to ask questions.

I am new to shiki, and really love how simple it is to use. I'm trying to see how I can wrap my code when the character length of a certain line exceeds a certain number. Is this something that's already supported in shiki, or do I have to implement this myself? If it's the latter, from my limited knowledge, is [transformers](https://shiki.style/guide/transformers) the place to start?

Thank you very much!

### Reproduction

Set .shiki `<pre>` tag to any width and define some code that exceeds its width.

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
Shiki outputs a plain HTML structure, while the wrapping is actually a rendering thing - so this isn't something Shiki controls.

The easier way to do so is by adding this CSS to your app:

```css
pre.shiki {
  white-space: pre-wrap;
}
```

**Comment by vcheeze** [comment]
@antfu understood. Thanks!
