### ISSUE TITLE
Hope to add support for ArkTS(*.ets)

### ISSUE THREAD

**Issue by FurryWolfX** [shikijs/shiki#577]
### Clear and concise description of the problem

ArkTS(*.ets) is the development language for Harmony OS.

Hope to add support for ArkTS(*.ets).

### Suggested solution

add ArkTS(*.ets) support

doc：https://developer.huawei.com/consumer/cn/doc/harmonyos-guides-V2/arkts-ui-development-overview-0000001438467628-V2

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
In general, we suggest you [loading our own grammar locally](https://shiki.style/guide/load-lang) to going forward. If you really believe the language you are proposing is widely used, please send PR to https://github.com/shikijs/textmate-grammars-theme, while will eventually be included in Shiki.
