### ISSUE TITLE
Languages not included when using a custom theme

### ISSUE THREAD

**Issue by wesbos** [shikijs/shiki#583]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

I'm trying to use Shiki with a custom theme, but it seems by loading a custom theme, all the default languages are then lost.

I get `Error: Language `javascript` not found, you may need to load it first` 

The example from the docs does not run:

```js
import { getHighlighter } from 'shiki';

const myTheme = {
  name: 'my-theme',
  settings: [
    {
      scope: ['comment'],
      settings: {
        foreground: '#888',
      },
    },
    // ...
  ],
};

const highlighter = await getHighlighter({
  themes: [myTheme],
});

const code = `console.log('hello')`;
const html = highlighter.codeToHtml(code, {
  lang: 'javascript',
  theme: 'my-theme',
});
```

<img width="997" alt="Screenshot 2024-02-08 at 11 06 29 PM" src="https://github.com/shikijs/shiki/assets/176013/5985e553-9d85-41a9-aee1-bd185cb01977">

### Reproduction

above

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
Since Shiki v1.0, langs have to be explicitly specified in order to be used:
https://shiki.style/guide/install#highlighter-usage

If you want to use all langs available:
```ts
import { bundledLanguages, bundledThemes, getHighlighter } from 'shiki'

const highlighter = await getHighlighter({
  themes: Object.keys(bundledThemes),
  langs: Object.keys(bundledLanguages),
})
```

Or if your code only runs on Node, you can use the automated shorthand:
https://shiki.style/guide/install#shorthands

**Comment by antfu** [comment]
Made the type stricter, hope this could help avoid the confusion.

**Comment by wesbos** [comment]
Gotcha! So I started with the shorthand, and then followed the docs for a custom theme.  because I switched away from the shorthand to load my own theme, I have to explicitly pass the langs needed. 

Thank you!
