### ISSUE TITLE
`Vue SFC`: add a different highlight color to vue components in Upper Camel Case

### ISSUE THREAD

**Issue by nova1751** [shikijs/shiki#587]
### Clear and concise description of the problem

Add a different highlight color to vue components in Upper Camel Case in Vue SFC.Just like the picture below: give child component a different color.
![image](https://github.com/shikijs/shiki/assets/97817985/7fc57f2c-7e9b-4314-b5e3-a0797daf496c)

### Suggested solution

Maybe set a different rule for vue `template` rendering.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [X] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
This is about #68, which I don't expect it be implemented anytime sooner due to the complexity. Close as duplication.
