### ISSUE TITLE
Shell script comment wrong color

### ISSUE THREAD

**Issue by Menci** [shikijs/shiki#591]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

This piece of shell code:

```
git commit --allow-empty -m "Initial commit" # commit
git push git@github.com:user/repo origin # push
```

On VSCode:

<img width="446" alt="image" src="https://github.com/shikijs/shiki/assets/11341955/fc22eb02-e7e0-4343-8e26-c8237c48d530">

On Shiki:

<img width="549" alt="image" src="https://github.com/shikijs/shiki/assets/11341955/20511911-df46-490c-abc1-f636865270c5">

### Reproduction

In the description

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
I can confirm the behavior is indeed not expected - but I am not sure why - as we are supposed to use the same grammar as in VS Code. Help appreciated if anyone wants to have a deeper look

**Comment by hippotastic** [comment]
I just tested the downloading & processing performed by `tm-grammars` locally and found that the processing seems to be the issue.

For example, the source grammar file on GitHub contains the following line:
https://github.com/microsoft/vscode/blob/a16d8d0a3e2062678c599134e78f8aa7b124363b/extensions/shellscript/syntaxes/shell-unix-bash.tmLanguage.json#L87

In the processed version, the same line changes looks like this instead:
https://github.com/shikijs/textmate-grammars-themes/blob/7d3b513c5c8fe4b1c220e12c1cdbab8c23cf28e9/packages/tm-grammars/grammars/shellscript.json#L108

When comparing them side by side, these are the strings:
```
// VSCode: "match": "[ \\t]*+([^ \t\n'&;<>\\(\\)\\$`\\\\\"\\|]+(?!>))"
// Shiki:  "match": "[ \\t]*+([^\n'&;<>\\(\\)\\$`\\\\\"\\|]+(?!>))"
```

I assume the post-processing of the downloaded grammars is causing this issue somehow.

**Comment by hippotastic** [comment]
I found the error. The `.trim()` command in this line here in the cleanup step is causing the differences:

https://github.com/shikijs/textmate-grammars-themes/blob/7d3b513c5c8fe4b1c220e12c1cdbab8c23cf28e9/scripts/grammars/cleanup.ts#L32

Once removing it and forcing a grammar re-download, the error is gone.

**Comment by antfu** [comment]
Nice catch @hippotastic, thanks!

**Comment by hippotastic** [comment]
No worries, thanks for the quick fix! Quite the edge case with an unescaped character in a regexp range triggering an issue in postprocessing like this. :)
