### ISSUE TITLE
[QUESTION] How to use shiki and twoslash with vitepress in vue component

### ISSUE THREAD

**Issue by kravetsone** [shikijs/shiki#593]
I need to use shiki and twoslash in the vue component (with vitepress) but I don't understand how to do it.
Sorry if the question is not specific to Shiki.

For example, prism has such a [vue-prism-component](https://www.npmjs.com/package/vue-prism-component). The same one from Shiki would solve my problem

**Comment by antfu** [comment]
You can reference to https://github.com/pi0/nuxt-shiki. Shiki is just a library and we don't have plan to provide framework component wrappers at this moment.
