### ISSUE TITLE
[Question] Usage for colorReplacements option

### ISSUE THREAD

**Issue by elkmod** [shikijs/shiki#601]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Hey folks, I am currently setting up syntax highlighting in my project using shiki and I'm getting stuck at trying to set the background color without creating a custom theme. I found the [`colorReplacements`](https://shiki.style/guide/theme-colors#color-replacements) option, but I can't really find an example of how to use it correctly.

I would like to change only the background color of the theme (since `shiki` sets it inline, there's no other way to override it). I tried a few variations, but couldn't seem to "guess" the correct API for it - e.g. the code below is not working (I assumed that `colorReplacements` uses the same structure as theme options.

Reproduction:

```js
const html = await codeToHtml(
  props.snippet,
  {
    lang: props.lang,
    theme: 'dracula',
    colorReplacements: {
      bg: '#1e1b4b',
    }
  }
)
```

<img width="832" alt="image" src="https://github.com/shikijs/shiki/assets/7780750/93e3e975-b520-4956-9d31-dd09234ed2c5">

![localhost_3000_blocks](https://github.com/shikijs/shiki/assets/7780750/dab8cb2d-190f-4737-9a66-199a39434be3)

I'll be happy to add an example for the correct usage in the docs.

### Reproduction

See example code above.

### Contributes

- [x] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
`colorReplacements` are for "color-to-color" replacements but not "type-to-color". If you put the hex of the background to replace it should work.

Or if you want to remove the background color from the root element, you could use a transformer:

```ts
const html = await codeToHtml(
  props.snippet,
  {
    lang: props.lang,
    theme: 'dracula',
    transformers: [{
      pre(node) {
        delete node.properties.style
      }
    }]
  }
)
```
