### ISSUE TITLE
Support inline code/lang?

### ISSUE THREAD

**Issue by lslzl3000** [shikijs/shiki#603]
One simple usage, e.g. a `ts` file with inline `glsl`/`wgsl` codes, the code highlights works well in VScode with some extensions, e.g. https://marketplace.visualstudio.com/items?itemName=ggsimm.wgsl-literal

```ts
const wgsl = /* wgsl */  `
    struct a {
       ....
    }
    @group(0) @binding(0) var<storage, read> input: a;
`

const glsl = /* glsl */ `
    #version 450
    layout(location = 0) in vec3 position;
    layout(location = 1) in vec3 normal;
    layout(location = 2) in vec2 uv;
`
```

Can `shiki` style inline codes with `/* lang */` header ?

**Comment by antfu** [comment]
You may do it by:

- Custom grammar injection to attach the scope based on the comment (for example, markdown supports embedded langs)
- A custom transformer that runs Shiki again for the matched string with the expected language and merges the tokens back.

It has a certain complexity and might not be very easy to do. I don't think Shiki will provide built-in support for this particular use case.
