### ISSUE TITLE
bash script code highlight on <name> with ending white charater

### ISSUE THREAD

**Issue by himself65** [shikijs/shiki#606]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

```shell
#!/bin/bash
# weather.sh
# Copyright 2018 computer-geek64. All rights reserved.

pnpm install <hello-world>
```

<img width="1006" alt="image" src="https://github.com/shikijs/shiki/assets/14026360/8aeac693-7d6c-40d6-90cc-bb7d8f1d2f94">

### Reproduction

https://github.com/nodejs/nodejs.org/issues/6363

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
<img width="699" alt="Screenshot 2024-03-06 at 12 01 10" src="https://github.com/shikijs/shiki/assets/11247099/64c9363c-45a1-454e-bd21-fa6136c692d2">

This is not a valid Bash syntax - VS Code also behaves the same. You might want to report to the upstream grammar instead.
