### ISSUE TITLE
`transformerNotationDiff` and `transformerNotationHighlight` don't apply any styles to code blocks

### ISSUE THREAD

**Issue by francisko-rezende** [shikijs/shiki#610]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

The transformers `transformerNotationDiff` and `transformerNotationHighlight` don't seem to be working. From what I've gathered, they do add their respective classes to the tags related to the code blocks but the classes don't seem to have any css rules, resulting in no visual changes to the lines that were supposed to be transformed.

![image](https://github.com/shikijs/shiki/assets/39991049/d3e7a9df-f610-4912-82ba-50ca0f857875)

Cheers and thanks for the awesome work you've been doing in this project :)

### Reproduction

https://stackblitz.com/edit/vitejs-vite-rzz2qj?file=main.js

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
It doesn't come with styles, it's up to users to write the CSS themself.

**Comment by francisko-rezende** [comment]
Oh cool, thanks for the reply @antfu ! In that case may I suggest that this is a bit more explicit in the docs, specially in the section on Transformers? For instance, this bit makes me think that the styles are baked in 
![image](https://github.com/shikijs/shiki/assets/39991049/eb601f31-3974-45e9-bb59-b724f49de93d)


I'd gladly add a suggestion if that's alright :)

Cheers and thanks again

**Comment by antfu** [comment]
Of course! Would you like to send a quick PR to improve the docs?

**Comment by francisko-rezende** [comment]
Sure thing, it'll be a pleasure! I'll get to it ASAP :D
