### ISSUE TITLE
Idea: Rename `@shikijs/transformers` 'notation' transformers -> 'comment'

### ISSUE THREAD

**Issue by richardgill** [shikijs/shiki#618]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Idea: 

I've found the names of these transformers a little confusing: 

`transformerNotationDiff`
`transformerNotationHighlight`
`transformerNotationWordHighlight`
`transformerNotationFocus`
`transformerNotationError`

Perhaps the following naming would be clearer:

`transformerCommentDiff`

### Reproduction

This is just a suggestion

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
Thanks for bringing this up. But since the name is decided and shipped, I would try to avoid breakage if there is no absolute necessary, considering `Notation` and `Comment` both are quite general, I feel it doesn't justify the cost of breaking changes.
