### ISSUE TITLE
Question about custom `vscode-textmate` dependency

### ISSUE THREAD

**Issue by GalAster** [shikijs/shiki#62]
https://github.com/shikijs/shiki/blob/56c230a2fd4d5f0bb5478a53ccaa808aeec961b8/packages/shiki/package.json#L19-L24

What is the function of the self-built dependency here, can it be upgraded to textmate5?

**Comment by octref** [comment]
For https://github.com/microsoft/vscode-textmate/issues/79, now it's possible to update.

**Comment by octref** [comment]
Upgraded and all seems good.

**Comment by GalAster** [comment]
Also remove here:

https://github.com/shikijs/shiki/blob/12accaa53a9a919f9964e2c7a6e54a8fdd1ddb10/packages/languages/package.json#L19-L21

**Comment by octref** [comment]
OK, removed.
