### ISSUE TITLE
Add gleam language

### ISSUE THREAD

**Issue by jacobdalamb** [shikijs/shiki#621]
### Clear and concise description of the problem

[gleam](https://gleam.run/)
Note: could you create a `add language` template?

### Suggested solution

na

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
<img width="1262" alt="image" src="https://github.com/shikijs/shiki/assets/11247099/9b0a8aca-865d-4c8d-b0b1-a8623e9d70d0">

https://github.com/shikijs/textmate-grammars-themes
