### ISSUE TITLE
Mangled code output with @shikijs/twoslash

### ISSUE THREAD

**Issue by ClearedFram3** [shikijs/shiki#623]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

I am using the `@shikijs/twoslash` integration to parse the TS website docs. The issue I have is that the output is code is highlighted correctly, but the twoslash blocks don't work.
```
import { hfs } from '@humanfs/node';
import markdownIt from 'markdown-it';
import Shiki from '@shikijs/markdown-it';
import { transformerTwoslash } from '@shikijs/twoslash';

const md = markdownIt();

md.use(
	await Shiki({
		themes: {
			light: 'vitesse-light',
			dark: 'vitesse-dark'
		},
		transformers: [transformerTwoslash()]
	})
);

const readingPath = './TS for OOPers.md';

const f = await hfs.text(readingPath);
const h = await md.render(f);

await hfs.write(`./testmd.html`, h);
```

Here is an image of twoslash block incorrectly compiled:
<img width="620" alt="Screenshot 2024-03-13 at 10 03 16 PM" src="https://github.com/shikijs/shiki/assets/16619896/1db4530f-4191-4451-b4e4-1dffa02bcf31">

And this is what is should look like:
<img width="518" alt="Screenshot 2024-03-13 at 10 12 59 PM" src="https://github.com/shikijs/shiki/assets/16619896/da8b25d5-e4c8-4395-a2d5-6faf4a5d1a9f">

### Reproduction

https://github.com/ClearedFram3/shiki-error

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
You need CSS to proper style them
