### ISSUE TITLE
Add option to configure tokenizeMaxLineLength and tokenizeTimeLimit in @shikijs/monaco

### ISSUE THREAD

**Issue by floriansbh** [shikijs/shiki#625]
### Clear and concise description of the problem

Currently both of these settings are are statically set in the tokenize() function (tokenizeMaxLineLength to 20.000 and tokenizeTimeLimit to 500) and cannot be changed in any way. My problem is that I'm mostly dealing with bigger files which are most of the time minified and exceed the tokenizeMaxLineLength and tokenizeTimeLimit so I can't really get any syntax highlighting most of the time.

### Suggested solution

Adding an argument for these settings to the shikiToMonaco() function exported by @shikijs/monaco or just making use of the options passed to the monaco.editor.create() function would probably be the most optimal solution

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
Sure, pr welcome!
