### ISSUE TITLE
Template literals in  Monaco editor

### ISSUE THREAD

**Issue by h-hristov** [shikijs/shiki#626]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

When using template literals in the Monaco editor, the parameters inside them are treated as string tokens.
This cause incorrect syntax highlighting.

-monaco-editor: 0.47.0,
-shiki: 1.2.0,
-@shikijs/monaco: 1.2.0

![monaco-editor](https://github.com/shikijs/shiki/assets/72193428/2e9c9b27-1fbf-4f9d-b031-bb68a285588f)

### Reproduction

monaco-editor: 0.47.0 and @shikijs/monaco: 1.2.0

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
I have no idea how to fix that as it can be a problem with in either Monaco, the grammar, or the integration. It does not seem significant to me either, and I don't have enough incentive to investigate. I'd suggest you dig in yourself and send PRs - if that matters to you. Thank you.
