### ISSUE TITLE
`shiki support tiptap`: can shiki support tiptap editor

### ISSUE THREAD

**Issue by buttercannfly** [shikijs/shiki#631]
### Clear and concise description of the problem

We are using tiptap editor for doc center. During research, we found shiki so good, but how does our tiptap use it?

### Suggested solution

currently, we don't know how to solve it as shiki is so strong

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [X] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
I don't use TipTap so no interest on my side to maintain that official - it would be better if they are willing to do it on their side (also easier to keep us their changes) - otherwise I think it could be a community solution.
