### ISSUE TITLE
`@shikijs/rehype` backgroundColor instead of background-color in style attribute

### ISSUE THREAD

**Issue by sek-consulting** [shikijs/shiki#633]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Hi :)
I'm currently in the process of updating the solid-ui.com docs to the newest solid-start version and I took the opportunity to also update to shiki 1.0.
But I found an issue with the style attributes that are getting set on the pre-element.

For background you usually expect `style="background-color:#ff00ff;"` but shiki generates `style="backgroundColor:#ff00ff;"` which doesn't set the color.

![image](https://github.com/shikijs/shiki/assets/8871906/f9e11c71-bbb8-447e-b8da-e556845b25d7)

I use the rehype plugin in combination with the vinxi mdx plugin:
```tsx
rehypePlugins: [
  [
    rehypeShiki,
    {
      theme: "github-dark",
      transformers: [transformerMetaHighlight()],
    },
  ],
],
```

versions used:
```
"@shikijs/rehype": "^1.2.0",
"@shikijs/transformers": "^1.2.0",
"shiki": "^1.2.0",
```

### Reproduction

https://github.com/sek-consulting/solid-shiki1.0

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
I don't know where to look at with your reproduction - `backgroundColor` doesn't seems to come from our codebase. Case convention is not the responsibility of Shiki, that you might want to fix that either in your usage or pipeline - unless you can provide a clear reproduction indicates it's a Shiki's issue. Thank you.

**Comment by sek-consulting** [comment]
Thanks for having a look at the problem.

I stripped down the example even more to really make sure it's not some weird side effect.
I removed:

- tailwindcss 
- the frontmatter plugins
- the highlight transformer

So it's basically just the rehype plugin included in the barebones mdx template from solidstart:

```tsx title:app.config.ts
const { default: mdx } = pkg;

export default defineConfig({
  ssr: true,
  extensions: ["mdx", "md"],
  vite: {
    plugins: [
      mdx.withImports({})({
        jsx: true,
        jsxImportSource: "solid-js",
        providerImportSource: "solid-mdx",
        rehypePlugins: [[rehypeShiki, { theme: "github-dark" }]],
      }),
    ],
  },
});
```
```tsx title:App.tsx
export default function App() {
  return (
    <Router
      root={(props) => (
        <MDXProvider components={{}}>
          <main>
            <Suspense>{props.children}</Suspense>
          </main>
        </MDXProvider>
      )}
    >
      <FileRoutes />
    </Router>
  );
}
```

```json title:package.json
  "devDependencies": {
    "@shikijs/rehype": "^1.2.3",
    "shiki": "^1.2.3"
  }
```

I updated the repo with the code:
https://github.com/sek-consulting/solid-shiki1.0

![grafik](https://github.com/shikijs/shiki/assets/8871906/11f69ec0-ad41-491f-b977-16d12663a0ff)

If I can help in any other way please let me know :)

**Comment by s7tya** [comment]
Hi. I’m leaving this comment for anyone using Shiki with MDX who runs into the `backgroundColor` issue. From what I can tell, the problem seems to stem from the MDX compiler’s `stylePropertyNameCase` option defaulting to `"dom"`, which converts CSS properties to camelCase. Switching this option to `"css"` keeps them in kebab-case (`background-color`) and appears to fix the issue.
