### ISSUE TITLE
Misleading documentation in `@shikijs/transformers`

### ISSUE THREAD

**Issue by YieldRay** [shikijs/shiki#643]
### Additional context

Also tested on @shikijs/transformers v1.2.1.

# transformerNotationErrorLevel

The outer `<pre>` tag is actually `<pre class="has-highlighted">`

![has-error-levels](https://github.com/shikijs/shiki/assets/24633623/c1d70af3-bec2-450b-9d27-00135fd7f945)  

Relevant code:
https://github.com/shikijs/shiki/blob/639aa6b0629a81c97e191f1aa2bc36edd833969b/packages/transformers/src/transformers/notation-error-level.ts#L12-L24

# transformerNotationFocus

In Vitepress, the documentation, the outer class is `has-focused-lines` and the inner class is `has-focus`
![image](https://github.com/shikijs/shiki/assets/24633623/122e1f44-8f84-429b-b297-ea7fb3bb211e)

This differs from what I tested on @shikijs/transformers v1.2.1.
![image](https://github.com/shikijs/shiki/assets/24633623/3a432bc9-f35d-4d92-ad8a-e9045601a329)

Relevant code:
https://github.com/shikijs/shiki/blob/639aa6b0629a81c97e191f1aa2bc36edd833969b/packages/transformers/src/transformers/notation-focus.ts#L15-L24

**Comment by YieldRay** [comment]
> PR welcome! Thanks

But I don' t known which one is correct, the docs or the source code?

**Comment by antfu** [comment]
The code. There were some mistakes in the docs.

**Comment by YieldRay** [comment]
ok, will try to do it.
