### ISSUE TITLE
Is it possible to highlight code synchronously without top-level await being available?

### ISSUE THREAD

**Issue by xsjcTony** [shikijs/shiki#647]
### Clear and concise description of the problem

I'm using React, hence I need to synchronously highlight the code and use `dangerouslySetInnerHTML` to inject the content.
However, using `async` in React environment is a bit hard.
I tried to create a highlighter instance to highlight code synchronously in my local and it worked well, however it's not supported in the production environment, due to the browser version as required:
![image](https://github.com/shikijs/shiki/assets/45784210/092ae4e5-4ed2-4fbd-ab6d-dab67a85db3a)
Any way I can use the synchronous way without top-level await being available?
I need to use it fully synchronously, but seems either shorthand needs to be async, or getHighlighter needs to be async. I know we are dynamically loading modules, but I wonder whether we have any solution to this.

### Suggested solution

This is a Question as no discussion is available

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
I'd wish to, but no. It's how JS works, you can't workaround it.

**Comment by RobinTail** [comment]
The following setup enables a single instance of Shiki without top level await, @xsjcTony 

```ts
// context.ts
import type { HighlighterGeneric } from "@shikijs/types";

export interface WrapperContextType {
  highlighter: Pick<HighlighterGeneric<string, string>, "codeToHtml">;
}

export const noopHighligher = { codeToHtml: (code) => code };

export const WrapperContext = createContext<WrapperContextType>({
  highlighter: noopHighligher,
});
```

```tsx
// Wrapper.tsx
import { noopHighligher, WrapperContextType, WrapperContext } from "context.ts";

export const Wrapper = ({ children }) => {
  const [highlighter, setHighlighter] = React.useState<
    WrapperContextType["highlighter"]
  >(noopHighligher);

  React.useEffect(() => {
    createHighlighter({
      themes: ["github-dark-dimmed", "github-light"], // adjust
      langs: ["shell", "json", "typescript", "javascript", "diff"], // adjust
    }).then(setHighlighter);
  }, []);

  return (
    <WrapperContext.Provider value={{ highlighter }}>
      {children}
    </WrapperContext.Provider>
  );
};
```

```tsx
// Code.tsx
export const Code = () => {
  const { highlighter: { codeToHtml } } = React.useContext(WrapperContext);
  // ...
};
```

**Comment by RobinTail** [comment]
The following is a shorter way when using React 18+ with `<React.Suspense>` and `.use()` hook (no context and state needed), @xsjcTony 

```tsx
// Code.tsx
const hlPromise = createHighlighter({
  themes: ["github-dark-dimmed", "github-light"],
  langs: ["shell", "json", "typescript", "javascript", "diff"],
});

export const Code = () => {
  const { codeToHtml } = use(hlPromise);
  // ...
};
```

```tsx
// App.tsx

return () => (
  <React.Suspense fallback={<Alert severity="info">Loading...</Alert>}>
    <Code />
  </React.Suspense>
);
```
