### ISSUE TITLE
LaTeX and TeX highlighted incorrectly in Markdown

### ISSUE THREAD

**Issue by BearToCode** [shikijs/shiki#652]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

LaTeX and TeX are highlighted incorrectly inside Markdown, they stop working after a `\section`(and also other commands) is used.

### Reproduction

Go to the playground, select Markdown and type the following (please unescape the backticks `)

```
\`\`\`latex
\begin{document}
    \maketitle

    \section{Hello World!} Highlighted correctly!
\end{document} No longer highlighted :(
\`\`\`
```

Result:

![snippet](https://github.com/shikijs/shiki/assets/47280851/5575a28b-b0a8-4408-9a8f-0bc195b44e04)

### Contributes

- [ ] I am willing to submit a PR to fix this issue(I don't know how to fix it)
- [ ] I am willing to submit a PR with failing tests(Probably doesn't apply)

**Comment by BearToCode** [comment]
This issue is also present in vscode, so I guess the issue is with the TextMate grammar. What do you suggest is the best repo to move the issue to?

**Comment by antfu** [comment]
Please report upstream:

https://github.com/shikijs/textmate-grammars-themes/blob/8aec3d775cf7ad32d4d3b11de6c180046195f35f/sources-grammars.ts#L160-L164

->

https://github.com/microsoft/vscode/blob/main/extensions/latex/syntaxes/LaTeX.tmLanguage.json#L3C38-L3C127

-> 

https://github.com/jlelong/vscode-latex-basics/blob/main/syntaxes/LaTeX.tmLanguage.json

**Comment by BearToCode** [comment]
The grammar has been [fixed](https://github.com/microsoft/vscode/pull/209932) and the changes were [merged](https://github.com/microsoft/vscode/pull/209932) into vscode. They will automatically be picked up and used in the next released, right?

**Comment by BearToCode** [comment]
@antfu It's been 3 weeks, and the changes are yet to be published. Is any release planned soon?
