### ISSUE TITLE
`@shikijs/rehype`: support for inline code

### ISSUE THREAD

**Issue by jeremt** [shikijs/shiki#660]
### Clear and concise description of the problem

There is no support for highlighting inline code (similarly to [rehype-pretty-code](https://github.com/rehype-pretty/rehype-pretty-code)). It would be nice to be able to highlight something like `console.log('coucou')`.

### Suggested solution

Apply highlighting when there is something like \`console.log('coucou'){:js}\`

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
It would be a good feature to have - however I don't know what syntax we should follow as there is not standard right now. I see people doing

- ``` `code`{lang=js} ```
- ``` `code`{js} ```
- ``` `code`{.js} ```
- ``` `code{:js}` ```

**Comment by souporserious** [comment]
In my own parser, I parse a prefix that works similar to normal triple slash code blocks:
`` `js const a = 'a'` ``

And similarly these can be tagged with a filename:
`` `filename.js const a = 'a'` ``

The presence of the space is used to determine if it needs highlighting, so this wouldn't be highlighted for example:
`` `js` ``

The idea was to bring familiarity with how it's already done in code blocks. However, this does unfortunately look weird in raw markdown since it's embedded in the code snippet.

**Comment by fuma-nama** [comment]
I think \`code{:js}\` will be better since people migrating from `rehype-pretty-code` will need it and it shouldn't break existing transformers (theoretically). This doesn't follow the standard markdown format and I'm not sure if any change is needed to support this feature.

**Comment by jcayzac** [comment]
I've used ``[`some code` lang]`` a lot in another (closed source) project, FWIW.

**Comment by jcayzac** [comment]
Also, just noting that `` `code`{js}`` would be ambiguous in MDX.

**Comment by fuma-nama** [comment]
Working on the PR, it's working very great. Should it be enabled by default?

**Comment by antfu** [comment]
https://github.com/shikijs/shiki/pull/751 get shipped. Free feel to bring more options if you needed as PRs. Closing this issue now to clean up our tracker. Thanks

**Comment by ryoppippi** [comment]
Is this feature available in markdown-it?

**Comment by fuma-nama** [comment]
It's not added to markdown-it, I have only made the PR to rehype.

You can also open a feature request or a PR for it.
