### ISSUE TITLE
WASM usage with getHighlighterCore errors with Buffer.isBuffer (this doesn't exist in the browser)

### ISSUE THREAD

**Issue by NullVoxPopuli** [shikijs/shiki#664]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Versions

    "@shikijs/rehype": "^1.2.0",
    "shiki": "^1.2.0",

### Describe the bug

![image](https://github.com/shikijs/shiki/assets/199018/d3348698-b381-448e-888b-a9ff67e58002)

and the entrypoint is from this path:
![image](https://github.com/shikijs/shiki/assets/199018/111fe378-88be-44b7-be46-cf599b985952)

I will be working around this for now by defining `Buffer.isBuffer` on window/globlaThis via this in my index.html
```js
globalThis.Buffer = { isBuffer: () => false }
```

### Reproduction

call `await getHighlighterCore({`

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
<img width="154" alt="Screenshot 2024-04-29 at 13 02 47" src="https://github.com/shikijs/shiki/assets/11247099/f958a71f-c607-4332-b15b-5d82e037db4f">

But the case is that `Buffer` should not exist in browser (we already do the check before calling `Buffer.isBuffer` - are you doing some shimming for your client? I don't mind doing an extra check of the `Buffer.isBuffer?()` if that helps

**Comment by NullVoxPopuli** [comment]
I see this:
![image](https://github.com/shikijs/shiki/assets/199018/5db9df04-6287-4a48-8c2c-61f6095053e2)


which is probably because Webpack is doing something silly -- not sure I can have control over it in this case :thinking: I don't have any explicit configuration that would add this ... a blank Buffer object :thinking: 

> I don't mind doing an extra check of the Buffer.isBuffer?() if that helps

It would!

**Comment by antfu** [comment]
Would you like to send a quick PR? Thanks

**Comment by NullVoxPopuli** [comment]
ye! https://github.com/shikijs/shiki/pull/666
