### ISSUE TITLE
shiki transformer this.addClassToHast is not a function in astro

### ISSUE THREAD

**Issue by blackPeppper** [shikijs/shiki#673]
### Validations

- [x] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

shiki transformer this.addClassToHast is not a function in astro

Astro                    v4.6.2
Node                     v20.11.1
System                   Windows (x64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             auto-import
                         @astrojs/mdx
                         @astrojs/sitemap
                         astro-compress
                         astro-purgecss
                         @vite-pwa/astro-integration
                         astro-meta-tags
                         astro-icon
                         astro-compressor
                         
                         
                         
 ```md
 ```tsx
console.log("Introduction.")

console.log("Subtraction.") // [!code focus] // [!code --]

console.log("Addition.") // [!code focus] // [!code ++]

console.log("In focus.") // [!code focus]

console.log("End.")
```
```


```js
   // astro.config 
    mdx({
      optimize: true,
      shikiConfig: {
        experimentalThemes: {
          light: "material-theme-lighter",
          dark: "material-theme-darker",
        },
        transformers: [
          transformerNotationDiff(),
          transformerNotationFocus(),
          transformerMetaHighlight(),
          transformerNotationWordHighlight(),
          transformerNotationErrorLevel(),
          transformerRenderWhitespace(),
          transformerMetaWordHighlight(),
          transformerCompactLineOptions(),
          transformerRemoveLineBreak()
        ],
      },
    }),
    ```

### Reproduction

https://github.com/spices-solutions/fruitUI/tree/upgrade-shinki

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by blackPeppper** [comment]
https://github.com/spices-solutions/fruitUI/tree/upgrade-shinki

**Comment by antfu** [comment]
This is not a minimal reproduction, please provide a minimal one. Thanks

**Comment by blackPeppper** [comment]
Sorry for the noise just needed to upgrade to astro ->4,8

so where I can get  these styles
https://github.com/blackPeppper/shiki-min-trans-pord

 
![image](https://github.com/shikijs/shiki/assets/93441520/19eb2d63-334e-4bf2-9316-042fb36da655)

**Comment by fuma-nama** [comment]
I'll suggest to close this issue if Astro has fixed it.

For transformers styles, Vitepress has a built-in stylesheet: https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/styles/components/vp-doc.css
You can add your own styles, Shiki transformers only add relevant classes to the elements.
