### ISSUE TITLE
shiki-renderer-svg support

### ISSUE THREAD

**Issue by hhk-png** [shikijs/shiki#678]
### Clear and concise description of the problem

After shiki refactoring, shiki no longer support shiki-renderer-svg. And I tried to write a shiki-renderer-svg-other using a bit different process. 

### Suggested solution

Would it to be a independent repository if shiki don't do this, or I commit a pr?

https://github.com/hhk-png/shiki-renderer-svg-other

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [x] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
It was removed because we didn't know if people actually use it (the npm stats was low).

In that sense - feel free to PR and add it back, thanks!

**Comment by hhk-png** [comment]
ok
