### ISSUE TITLE
Vue 当没有写 `template` 时无法正常高亮

### ISSUE THREAD

**Issue by WangJincheng4869** [shikijs/shiki#686]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

![图片](https://github.com/shikijs/shiki/assets/41162158/9533900a-4a81-438a-8c77-651264d51746)

```vue
<sp-with-sidebar>
  <template #default>
    <sp-card title="工单管理"></sp-card>
  </template>
  <template #sidebar>
    <sp-sidebar v-model="activeName">
      <sp-sidebar-pane icon="customer" tip="客户信息">
        <sp-card title="客户信息" :title-underline="false"> 客户信息内容</sp-card>
      </sp-sidebar-pane>
      <sp-sidebar-pane icon="application" tip="应用中心">2</sp-sidebar-pane>
      <sp-sidebar-pane icon="message" tip="消息队列">3</sp-sidebar-pane>
    </sp-sidebar>
  </template>
</sp-with-sidebar>
```

### Reproduction

https://shiki.tmrs.site/

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
That's how the grammar work, and it's not a Shiki issue. You may use `vue-html` lang as a workaround.
