### ISSUE TITLE
@shikijs/markdown-it: code block is wrong when entering a non-existent language

### ISSUE THREAD

**Issue by Only566** [shikijs/shiki#687]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Code block is wrong when entering a non-existent language, even if the input is not complete, an error will be reported.
![image](https://github.com/shikijs/shiki/assets/55044991/ae1fe623-c013-47d7-abf6-7b058108eacc)
![image](https://github.com/shikijs/shiki/assets/55044991/1053912a-f50f-4419-b1b4-bda168b6dde9)

Allowing configuration of a default language during initialization may be a good solution. 
```
MarkdownItPluginShiki({
  defaultLang: 'text'
})
```

### Reproduction

-

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
PR welcome :)

**Comment by rglover** [comment]
This can be resolved if you add a `fallbackLanguage` to the options like so:

```javascript
md.use(await Shiki({
  fallbackLanguage: 'javascript',
  defaultLanguage: 'javascript',
  themes: {
    light: 'slack-ochin',
  }
}));
```

Just tested against latest v1.6.2 release and can confirm it falls back as expected when you have non-existent language (or a typo in the language name).
