### ISSUE TITLE
Adobe Illustrator cannot import svg correctly

### ISSUE THREAD

**Issue by GalAster** [shikijs/shiki#69]
![](https://i.loli.net/2020/08/18/NIJKYc3e2FzkaxE.png)

Notice these black parts, this is because `Adobe Illustrator(2020)` cannot handle **colors with alpha**.

`style="fill: #D8DEE9FF"` must be written as `style="fill: #D8DEE9; opacity:1;"` or just trim `FF`.

---

Adobe XD(2020) also has this problem.

**Comment by octref** [comment]
Testing on Chrome/Figma/Affinity Designer, `opacity` only works in Chrome, whereas `fill-opacity` works on all.

**Comment by octref** [comment]
I don't have AI. Can you give it a try with the latest svg in `packages/site/svg.svg`?

**Comment by GalAster** [comment]
Now works well

![](https://i.loli.net/2020/08/19/SLZfuHT9oiOyewp.png)
