### ISSUE TITLE
`remove-notation-escape`: notation escape syntax’s normalize transformer

### ISSUE THREAD

**Issue by sor4chi** [shikijs/shiki#690]
### Clear and concise description of the problem

Hi there, thank you for this wonderful project!

Currently, when using Notation expressions such as `// [!code highlight]` in Shiki, and you want to render this directly to markdown code, the escape notation `// [\!code highlight]` is used. 
However, this expression doesn’t normalize, `// [\!code highlight]` is output as is.

### Suggested solution

https://github.com/shikijs/shiki/blob/a397882fa19d267917c0f8cd59b7717118f4b89f/docs/.vitepress/config.ts#L123-L128

### Alternative

Therefore, shiki's docs has created its own transformer to solve this problem.
At this time, why not export it as a `@shiki/transformers` function, or provide built-in support for it?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [X] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by sor4chi** [comment]
I'd like someone's opinion on whether this should go ahead.

**Comment by antfu** [comment]
Well, feel free to send a PR! Thanks
