### ISSUE TITLE
`@shikijs/rehype` - "30 instances have been created"

### ISSUE THREAD

**Issue by babakfp** [shikijs/shiki#714]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Hi 👋

```
[Shiki] 30 instances have been created. Shiki is supposed to be used as a singleton, consider refactoring your code to cache your highlighter instance; Or call `highlighter.dispose()` to release unused instances.
```

Yes, this is not a bug, but I don't understand how someone can use `@shikijs/rehype` without hitting into this issue.

I'm using this plugin in my website https://github.com/babakfp/babakfp.ir and in this preprocessor https://github.com/babakfp/mdx-svelte. Svelte loops through all markdown files, and inside that loop I use the unified stuff and rehype shiki.

Maybe it can be made in a way that I can create an instance outside the preprocess function and pass that to `@shikijs/rehype` via an option?

```ts
import { createHighlighter } from "@shikijs/rehype"

const highlighterInstance = createHighlighter()

processor.use(rehypeShiki, { highlighterInstance })
```

### Reproduction

https://github.com/babakfp/babakfp.ir

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [X] I am willing to submit a PR with failing tests

**Comment by xarthurx** [comment]
Same problem here.
Using `markdown-it` as a plugin for `nuxt3`.

```
import mdShiki from "@shikijs/markdown-it";

  const renderer = MarkdownIt({
    linkify: true,
    html: true,
  })
    .use(mdFootnote)
    .use(
      await mdShiki({
        themes: {
          light: "snazzy-light",
          dark: "nord",
        },
      }),
    )
```

**Comment by boidushya** [comment]
Facing the same issue with `@shikijs/rehype`

**Comment by antfu** [comment]
@babakfp I am sorry, where is your related code in your reproduction?

**Comment by antfu** [comment]
About this warning in general, ideally you should avoid creating new rehype instance in a loop. For everyone who encountered this warning, please review your usage and see if there is a refactor you could make. Also share your usage and fix here, so we could have a better understanding of how people are using it, and potentially improve the docs.

**Comment by babakfp** [comment]
> @babakfp I am sorry, where is your related code in your reproduction?

Sorry about that.

I made a proper reproduction here: https://github.com/babakfp/shikijs-shiki-issues-714

Watching this video may be helpful.

https://github.com/shikijs/shiki/assets/44144724/0974f8e3-250c-4c18-9d8d-a80e55a5652a

It seems like the message only shows up on every second or third restart of the server. When just running `pnpm dev`, it doesn't show up. If you do (`ctrl` + `s`) after that, it still doesn't show up. If you do it again, it shows up.

In my https://github.com/babakfp/babakfp.ir project, it happens after running `pnpm dev`. Maybe something is wrong with my code that Vite/SvelteKit auto restarts the server, and it triggers the message.

https://github.com/shikijs/shiki/assets/44144724/b7676462-89a1-4977-8fcf-204030b35331

**Comment by antfu** [comment]
Thanks, I see it better now. If in unified, the plugin are supported to be used in a factory function, I think that would make sense for us to use the shared singleton instance by default. Made the change in c4f030d7c173f6b8a1eeabaa0c3208306c7910ee.
