### ISSUE TITLE
shiki/wasm dependency not found

### ISSUE THREAD

**Issue by weixq709** [shikijs/shiki#716]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Install the full shiki package, then import it, prompting dependency not found.
1. install shiki
`npm install shiki @shikijs/markdown-it`
2. import
`import shiki from "@shikijs/markdown-it";`

reuslt:
This dependency was not found:

* shiki/wasm in ./node_modules/shiki/dist/chunks/wasm-dynamic.mjs

To install it, you can run: npm install --save shiki/wasm

### Reproduction

MRE

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by XiayidanAlimu** [comment]
I have the same issue with importing shiki/monaco

**Comment by weixq709** [comment]
> I have the same issue with importing shiki/monaco

这个似乎是vue-cli无法支持wasm的问题。我试过在vue config配置wasm，但是不生效。你可以试试修改wasm配置或者直接使用vite，vite对wasm支持很好。

**Comment by XiayidanAlimu** [comment]
> > I have the same issue with importing shiki/monaco
> 
> 这个似乎是vue-cli无法支持wasm的问题。我试过在vue config配置wasm，但是不生效。你可以试试修改wasm配置或者直接使用vite，vite对wasm支持很好。

原来如此，但我们项目挺陈旧的，所以还在用vue2那一套工具，现在如果升级构建工具vite代价有点大。
