### ISSUE TITLE
Support for Lit

### ISSUE THREAD

**Issue by JosefJezek** [shikijs/shiki#725]
### Clear and concise description of the problem

Lit templates are written using JavaScript template literals tagged with the html tag. The contents of the literal are mostly plain, declarative, HTML:

```js
static styles = css`
  :host {
    color: blue;
  }
`;

render() {
  return html`<p>Hello, ${this.name}!</p>`;
}
```

https://lit.dev/docs/components/overview/

### Suggested solution

I don't know any solution.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by JosefJezek** [comment]
@antfu Thank you 👍🏻

**Comment by JosefJezek** [comment]
@antfu please add support for these tags

### svg

```js
const rect = svg`<rect width="10" height="10"></rect>`;
const myImage = html`
  <svg viewBox="0 0 10 10" xmlns="http://www.w3.org/2000/svg">
    ${rect}
  </svg>`;
```

https://lit.dev/docs/api/templates/#svg

### math - MathML

```ts
const num = math`<mn>1</mn>`;

const eq = html`
   <math>
     ${num}
   </math>`;
 ```
 
https://github.com/lit/lit/pull/4637

**Comment by antfu** [comment]
Feel free to send PRs and help out. I don't use Lit myself.

**Comment by JosefJezek** [comment]
pls reopen issue

**Comment by antfu** [comment]
No. The original issue is resolved. You can't just keep asking more. Open source is voluntary, help out to move things forward.
