### ISSUE TITLE
Add support for Svelte

### ISSUE THREAD

**Issue by codechips** [shikijs/shiki#73]
Is there any chance we can get Svelte support? Because I am tired of fighting with Prism.js and its themes. 

Is it only a matter of adding upstream VSCode language syntax file and adding it to the list of supported languages? What else is needed? How can I help?

https://github.com/sveltejs/language-tools/blob/master/packages/svelte-vscode/syntaxes/svelte.tmLanguage.json

**Comment by octref** [comment]
I just made adding languages easier added a contributing guide: https://github.com/shikijs/shiki#contributing
