### ISSUE TITLE
`@shikijs/transformers` not working with Astro

### ISSUE THREAD

**Issue by satnaing** [shikijs/shiki#733]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

As the title suggests, `@shikijs/transformers` doesn't seem to work with Astro. I tested this with my own repo, [AstroPaper](https://github.com/satnaing/astro-paper), and Astro's minimal blog [starter template](https://astro.build/themes/details/blog).

Code snippets like `// [!code ++]` are rendered as plain text instead of being processed. I’ve created a branch where you can check out and test the issue. After setting up the local environment, you can visit [this URL](http://localhost:4321/posts/how-to-configure-astropaper-theme/#configuring-site) to see the result.

<img width="752" alt="Screenshot 2024-08-04 at 7 04 05 PM" src="https://github.com/user-attachments/assets/d31d7155-49a1-491e-a052-611c2716ee14">

### Reproduction

https://github.com/satnaing/astro-paper/tree/bug/shikijs-transformers-issue

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by rishi-raj-jain** [comment]
Take a look at https://www.launchfa.st/blog/shiki?

**Comment by satnaing** [comment]
@rishi-raj-jain 
Unfortunately, it doesn't work well with AstroPaper.

**Comment by antfu** [comment]
I'd suggest you to report to astro instead.
