### ISSUE TITLE
Option to exclude themeMatches from explanations

### ISSUE THREAD

**Issue by MichaelMakesGames** [shikijs/shiki#736]
### Clear and concise description of the problem

I want an option to exclude `themeMatches` from token explanations, but still include `scopeName`, so that plugins that need scope information can work without the slowdown of including all the themeMatches too

### Suggested solution

In @shiki/core codeToTokensBase could check an additional option to add explanations but skip `themeMatches`

### Additional context

I wrote a [shiki transformer for VSCode-style bracket colorization](https://github.com/MichaelMakesGames/shiki-colorized-brackets). It uses the textmate scopes for avoid matching some potential brackets (eg `>` when used as "less than") and to detect embedded languages (eg `ts` in a `svelte` file). It does not use the `themeMatches` on the explanations. I did some benchmarking and noticed that shiki is ~4.7x slower when `includeExplanation` is true, but when I manually edit the code to skip adding `themeMatches` it is only ~2x slower.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [X] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
I think we could have `includeExplanation: 'scope-only'` as an option to do so
