### ISSUE TITLE
Allow overriding/optionalizing background color

### ISSUE THREAD

**Issue by sdegutis** [shikijs/shiki#742]
### Clear and concise description of the problem

I'm using `dark-plus` and it sets a background, but I want it to be transparent.

### Suggested solution

Add an API option to either specify the background color (overriding the theme), or disable the bg color altogether.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by fuma-nama** [comment]
Why? Output of Shiki doesn't add `background` styles directly, it only provides a CSS variable. You can use CSS to control the background color of code blocks.

**Comment by sdegutis** [comment]
dunno

**Comment by Visual-Dawg** [comment]
I am using `codeToHtml` with `defaultColor: false` and it still applies inline-styles: `style="background-color:#fff;color:#24292e"`

From Svelte:
```svelte
{#await codeToHtml( text, { lang: language, theme: 'github-light', defaultColor: false }, ) then highlighted}
    {@html highlighted}
{/await}
```

**Comment by fuma-nama** [comment]
You need to use `themes` instead of `theme`. This also specifies the name of generated CSS variables.
