### ISSUE TITLE
`New grammar`: org support

### ISSUE THREAD

**Issue by Eliot00** [shikijs/shiki#749]
### Clear and concise description of the problem

support https://orgmode.org/ highlight

### Suggested solution

Add a new grammar?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
https://github.com/shikijs/textmate-grammars-themes
