### ISSUE TITLE
fromHighlighter requires repetitive input of `themes`  

### ISSUE THREAD

**Issue by xarthurx** [shikijs/shiki#757]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

I have a separate file defining a highlighter:
```ts
// shikiHighlighter.ts
import { createHighlighter, type Highlighter } from "shiki";
// import { createHighlighterCore } from 'shiki/core'

let highlighter: Highlighter | null = null;

export async function getShikiHighlighter() {
	if (!highlighter) {
		highlighter = await createHighlighter({
			themes: ["snazzy-light", "nord"],
			langs: ["javascript", "csharp", "cpp", "python"],
		});
	}
	return highlighter;
}
```

Then, in my `markdown-it` plugin file:
```ts
import MarkdownIt from "markdown-it";
// shiki
import { fromHighlighter } from "@shikijs/markdown-it/core";
import { getShikiHighlighter } from "~/utils/shikiHighlighter";

export default defineNuxtPlugin(async () => {
	const shikiHighlighter = await getShikiHighlighter();

	const renderer = MarkdownIt({
		linkify: true,
		html: true,
	})
		.use(
			fromHighlighter(shikiHighlighter, {    // <= cannot leave empty
				themes: {
					light: "snazzy-light",
					dark: "nord",
				},
			}),
		);

	return {
		provide: {
			md: renderer,
		},
	};
});
```

I cannot leave just a `{}` in the `fromHighlighter` function, as seen here: https://shiki.matsu.io/packages/markdown-it#fine-grained-bundle

and get an error:: **Invalid options, either `theme` or `themes` must be provided**

Then I need to do:
```
			fromHighlighter(shikiHighlighter, {
				themes: {
					light: "snazzy-light",
					dark: "nord",
				},
			}),
```

in this case, why does the function `createHighlighter` requires the input of `themes` if I need to put it into the `options` of `fromHighlighter` anyway?

### Reproduction

https://stackblitz.com/edit/vitejs-vite-ibaugh?file=plugins%2Fmarkdownit.ts

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
Because `createHighlighter` **loads** as many themes as you need and makes them **ready to use**. While which specific themes you **want to use** is up to the callee side. You can refactor that into a shared object if you want to, but this is how Shiki works.
