### ISSUE TITLE
Add an option to renderToHtml that wraps lines in extra spans

### ISSUE THREAD

**Issue by codepunkt** [shikijs/shiki#76]
This could be used for different things.
Amongst them, the highlighting of lines or adding line numbers via CSS counters.

**Comment by octref** [comment]
I don't like too many options. If it makes sense to add the `<span>` or other semantic structure to it I should add it without options. Maybe even with a `class`.

**Comment by codepunkt** [comment]
Sounds okay to me, i'm also like good defaults 👍

**Comment by codepunkt** [comment]
@octref Should i update my pull request to always wrap into spans? Do you want a specific `class` on them? (e.g. "line")
