### ISSUE TITLE
How can I get AST (not HAST)?

### ISSUE THREAD

**Issue by leodevbro** [shikijs/shiki#760]
Hi, I'm the author of VS Code extension "[Blockman](https://marketplace.visualstudio.com/items?itemName=leodevbro.blockman)". In Blockman, I have implemented third-party parsers/tokenizers to get the locations (line and column) of curly/square/round brackets and Python indent/dedent tokens, but the problem is that I found tokenizers for only some languages, the extension still does not support many languages. Also some tokenizers are very slow.

So, I'm trying to find a good third party tokenizer library to get AST tree from a code-text of many languages.

So far, I have found [shiki](https://www.npmjs.com/package/shiki) and [@wooorm/starry-night](https://www.npmjs.com/package/@wooorm/starry-night) which are probably what I need, but I'm not sure.

I read the docs and I see that I can get HAST like this:

```
{
  type: 'root',
  children: [
    {
      type: 'element',
      tagName: 'span',
      properties: {className: ['pl-mh']},
      children: [
        {type: 'text', value: '# '},
        {
          type: 'element',
          tagName: 'span',
          properties: {className: ['pl-en']},
          children: [{type: 'text', value: 'hi'}]
        }
      ]
    }
  ]
}

```

shiki can also provide simple tokens data like this:
(and it has locations, yeah, but it's not usable for Blockman because there is no information about the type of each token, I mean, for example we cannot detect which opening bracket `{` is in a code comment and which one is a real code nesting bracket. )
```
[[], [{
  "content": "def",
  "offset": 1,
  "color": "#F97583",
  "fontStyle": 0
}, {
  "content": " dfd",
  "offset": 4,
  "color": "#B392F0",
  "fontStyle": 0
}, {
  "content": ":",
  "offset": 8,
  "color": "#BBBBBB",
  "fontStyle": 0
}], [{
  "content": "    print",
  "offset": 10,
  "color": "#B392F0",
  "fontStyle": 0
}, {
  "content": "(",
  "offset": 19,
  "color": "#BBBBBB",
  "fontStyle": 0
}, {
  "content": "4",
  "offset": 20,
  "color": "#F8F8F8",
  "fontStyle": 0
}, {
  "content": ")",
  "offset": 21,
  "color": "#BBBBBB",
  "fontStyle": 0
}], []] 
```

**But I want to see a classic AST, I want to see the location** (line and column -> or global index of multi line string) **and type** (to know -> is it a square bracket, or curly bracket, or indent token of python? or something else?) **of each token of a multi-line code-text.**

**I don't need any highlighting style data, I just need a classic AST, I need only locations and types of block-tokens.**
I mean something like this:
**(tree structure is not needed necessarily. Just a simple array of tokens is enough for me)**
```
{
  type: "Program",
  start: 0,
  end: 23,
  sourceType: "module",
  body: [
    {
      type: "VariableDeclaration",
      start: 0,
      end: 23,
      kind: "const",
      declarations: [
        {
          type: "VariableDeclarator",
          start: 6,
          end: 23,
          id: {
            type: "Identifier",
            start: 6,
            end: 7,
            name: "a",
          },
          init: {
            type: "ObjectExpression",
            start: 10,
            end: 23,
            properties: [
              {
                type: "Property",
                start: 14,
                end: 20,

                value: {
                  type: "Literal",
                  start: 19,
                  end: 20,
                  value: 7,
                  raw: "7",
                },
                kind: "init",
              },
            ],
          },
        },
      ],
    },
  ],
}

```

Well, classic AST shows everything, all tokens. For my VS Code extension "Blockman", I don't need all the tokens, I need only the tokens which are block openers and block closers, for example brackets:
```
{        }
(        )
[        ]
```

also `INDENT` and `DEDENT` tokens of python and other indentation based languages.

also string openers and closers:
```
'        '
"        "
`        `
``` 

also multi-line comment openers and closers:
```
/*        */
"""        """
```

also HTML/XML/JSX/TSX tag openers and closers:
```
<div>        </div>
<img />
and all the other tags
```

also TypeScript/TSX generic type openers and closers:
```
<        >
```

So, can I get such kind of tokens with shiki or starry-night? Yeah, I know there are other libraries too but as I understand -> they are slow because they don't use textmate/oniguruma of VS Code.

**Comment by antfu** [comment]
Sorry Shiki is **not** a parser and it does not produce AST in any form. The best you can get is https://github.com/shikijs/shiki/blob/e09972f05010feaa64d57fee83d45b7253524925/packages/core/src/types/tokens.ts#L150-L158

Cool extension btw! But unfortunately Shiki might not be the best tool for that.

**Comment by leodevbro** [comment]
@antfu, actually, I checked out this `includeExplanation` option, and it really seems what I wanted. Thanks so much. I'll do some experiments for my Blockman soon, and I'll come back with the results.
