### ISSUE TITLE
`theme`: make json key and value not use same color

### ISSUE THREAD

**Issue by bluelovers** [shikijs/shiki#765]
### Clear and concise description of the problem

![image](https://github.com/user-attachments/assets/7278f80e-3b01-4b4d-bda6-2283e7ef0241)

### Suggested solution

something like this

![image](https://github.com/user-attachments/assets/d9b1ce2a-5cd2-4b52-a5db-18a1889f6567)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
We use https://github.com/mrmlnc/vscode-json5/blob/master/syntaxes/json5.json for JSON5, and it's how the grammar work. You might want to bring up the issue there instead.
