### ISSUE TITLE
Shiki In Next.js Witk `remark-math`

### ISSUE THREAD

**Issue by fweth** [shikijs/shiki#766]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

I try to use Shiki in Next.js. It's fine if I use no remark plugins, but when I add `remark-math` to my remark plugins, I get the error

```
ShikiError: page.md:ShikiError: Language `math` not found, you may need to load it first
```

Any way to get around this?

### Reproduction

```js
const withMDX = createMDX({
  extension: /\.(md|mdx)$/,
  // Add markdown plugins here, as desired
  options: {
    remarkPlugins: [remarkMath],
    rehypePlugins: [
      [
        rehypeShiki,
        {
          themes: {
            light: "vitesse-light",
            dark: "vitesse-dark",
          },
        },
      ],
    ],
  },
});
```

**Comment by fuma-nama** [comment]
Add rehype katex before your rehype shiki plugin
