### ISSUE TITLE
Should I create an issue first if I want to provide a translation?

### ISSUE THREAD

**Issue by XIYO** [shikijs/shiki#768]
I have been very satisfied using SvelteKit. 
However, since I'm not very comfortable with English, I often refer to translations. 
If I want to provide a translation for Korean users, should I create an issue and proceed with the work?

**Comment by antfu** [comment]
Thanks for your interest in helping. But sorry, we don't accept translations due to the maintenance effort to synchronize the changes. If you want, you can also fork and host your own translation site.

**Comment by XIYO** [comment]
Would a pull request adding a link for self-hosting be accepted?
