### ISSUE TITLE
inlined wasm violates chrome webstore no obfuscation policy

### ISSUE THREAD

**Issue by amk-dev** [shikijs/shiki#774]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

I've been using shiki in my chrome extension. but when i submitted to the chrome webstore i got a violation for obfuscated code.

on looking into it, i found its coming from shiki's inlined wasm. ( i'm using vite )

is there anyway to not include the wasm import in my bundle ?
how can i handle this situation ?

<img width="931" alt="image" src="https://github.com/user-attachments/assets/a7d3b54a-72ce-4624-a81f-4b9bb17f558a">

### Reproduction

import and use codeToHtml from the full bundle

```typescript
import { codeToHtml } from "shiki/bundle/full"
``` 

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
There is nothing we can do about it, maybe you can try using the JS engine: https://shiki.style/guide/regex-engines#javascript-regexp-engine-experimental be be aware of it's limitations and still experimental
