### ISSUE TITLE
`shiki@1.15.2` -> `1.17.5` wasm export chang

### ISSUE THREAD

**Issue by ovflowd** [shikijs/shiki#775]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

When updating from `1.15.2` towards `1.17.5` it doesn't become clear (at least on the CHANGELOG) (if this was an intentional change) that the exports for `getWasmInstance ` exported at `@shikijs/core/wasm-inlined` changed to `default` causing the following change necessary on downstream consuming apps:

```js
import { getWasmInstance } from '@shikijs/core/wasm-inlined';
```

unto

```js
import { default as getWasmInstance } from '@shikijs/core/wasm-inlined';
```

I understand this is a bit of a nitpick. Out of curiosity, I wonder if this should have been mentioned in the CHANGELOG to increase visibility? 🤔

Anyhow, fantastic work you've been doing here! Thanks!

### Reproduction

I'm not sure a reproduction is needed here, since the issue is just an import change.

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by ovflowd** [comment]
Also, food for thought, maybe I wasn't supposed to import the inline-wasm this way?

Just for future reference, I've changed the code, and we're using the new `engine` API you introduced with:

```js
import { createJavaScriptRegexEngine } from '@shikijs/engine-javascript';
```

Which seems super cool BTW!

**Comment by antfu** [comment]
It was an unintentional bug introduced during the refactoring, v1.17.6 should brought them back (https://github.com/shikijs/shiki/releases/tag/v1.17.6).

**Comment by ovflowd** [comment]
Thanks @antfu! Had no idea it was an unintentional side effect, I would have been more than happy to contribute with a PR!

Cheers :)
