### ISSUE TITLE
Add mmd alias to mermaid

### ISSUE THREAD

**Issue by emersonbottero** [shikijs/shiki#789]
### Clear and concise description of the problem

Tthis should fix the mermaid official docs documentation...

mermaid generates render so we need a different name when we want to actually show the code.. 
right now all codes in the official docs show as text with no text highlight 

### Suggested solution

add mmd as alias to mermaid

### Additional context

I tried to find where to add it but the only place I found is generated by CICD or a script I couldn't find as well. 

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
PR welcome to https://github.com/shikijs/textmate-grammars-themes/blob/main/sources-grammars.ts
