### ISSUE TITLE
html class output 

### ISSUE THREAD

**Issue by alterae** [shikijs/shiki#790]
### Clear and concise description of the problem

i want an option to output markup with `class` attributes rather than inline `style` attributes so that i can easily change highlighting colors (ie: dark theme or arbitrary color scheme changes) without altering the markup

### Suggested solution

when the proposed option is enabled, output markup like `<span class="hl kw">foo</span>` rather than `<span style="color: #aaaaaa">foo</span>`

### Alternative

an alternative solution is programmatically transforming the html output to convert style attributes to class attributes based on color, but this is tedious and fragile

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [ ] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
This is how Shiki fundamentally works, the TextMate grammar and scope level are so complex to the represented in class, that's also why Shiki as the most rich highlight result. You might write a custom transformer to enumerate what you want in a lossy way on userland https://shiki.style/guide/transformers, but we would consider this as out-of-scope from our side.
