### ISSUE TITLE
`postprocess` function not called in Shiki Rehype transformer

### ISSUE THREAD

**Issue by nikolailehbrink** [shikijs/shiki#793]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

I am using `@shikijs/rehype` with a custom transformer, similar to another setup I reported in a separate ticket. While the `preprocess` function works as expected, the `postprocess` function is never called. No logs or operations inside `postprocess` are executed.

**Steps to Reproduce:**
1. Implement a Shiki transformer with both `preprocess` and `postprocess` functions.
2. Load a code block with Shiki processing enabled on a page (e.g., `/test`).
3. Open the browser console and check for logs inside the `postprocess` function.

**Example Transformer:**

```ts
const transformer = () => ({
  name: "transformer",
  preprocess(code, options) {
    console.log("preprocess:", options.meta);
  },
  postprocess(html, options) {
    console.log("postprocess:", options);
  },
});
```

**Expected Behavior:**
The `postprocess` function should be executed after the code block is processed, and any logs or operations inside it should be visible in the console.

**Actual Behavior:**
The `postprocess` function is never called, and nothing is logged to the console.

**Environment:**
- Vite setup using `@shikijs/rehype` and the custom transformer.

Sample `vite.config.ts`:

```ts
import { defineConfig } from "vite";
import tsconfigPaths from "vite-tsconfig-paths";
import mdx from "@mdx-js/rollup";
import rehypeShiki from "@shikijs/rehype";

const transformer = () => ({
  name: "transformer",
  preprocess(code, options) {
    console.log("preprocess:", options.meta);
  },
  postprocess(html, options) {
    console.log("postprocess:", options);
  },
});

export default defineConfig({
  plugins: [
    mdx({
      rehypePlugins: [
        [rehypeShiki, { theme: "nord", transformers: [transformer()] }]
      ]
    }),
    tsconfigPaths(),
  ],
});
```

### Reproduction

https://github.com/nikolailehbrink/shiki-rehype-bugs

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by fuma-nama** [comment]
Post process receives HTML while Rehype Shiki outputs Hast nodes, hence it's never called. I think it is the expected behaviour, what do you want to do with `postprocess`?

**Comment by nikolailehbrink** [comment]
Ahh okay, thanks for the clarification @fuma-nama. Just wanted to get to know `shiki` better and tried to log it and wanted to see, what I can do with that, nothing more!
