### ISSUE TITLE
transformerNotationHighlight and transformerNotationFocus rendering bug

### ISSUE THREAD

**Issue by M0rtzz** [shikijs/shiki#813]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

When the first line is a shiki transformer comment, it may result in a blank line at the beginning of the code block, as indicated by the red box in the following images, possibly due to the shiki transformer comment.

[transformerNotationHighlight](https://shiki.style/packages/transformers#transformernotationhighlight)

code:

````md
```ts
// [!code highlight:3]
console.log('Highlighted')
console.log('Highlighted')
console.log('Not highlighted')
```
````

![图片](https://github.com/user-attachments/assets/1fbc4f47-512c-454d-8df4-c4c14e100e0f)

[transformerNotationFocus](https://shiki.style/packages/transformers#transformernotationfocus)

code:

````markdown
```ts
// [!code focus:3]
console.log('Focused')
console.log('Focused')
console.log('Not focused')
```
````

![图片](https://github.com/user-attachments/assets/5b682a18-1ec0-4351-b50d-560fd16d6702)

### Reproduction

Install shiki then run npm run dev

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by fuma-nama** [comment]
related to https://github.com/shikijs/shiki/issues/619
