### ISSUE TITLE
Feature request: exposing a low level API that returns AST instead of HTML

### ISSUE THREAD

**Issue by CNSeniorious000** [shikijs/shiki#815]
### Clear and concise description of the problem

In the era of Generative AI, code generation is a common use case. So we usually need to render a code block that is continually receiving new content. For now, we can only render code into HTML. If I want the rendering to be more performant, I can only split the whole HTML manually into spans, which is absolutely not the best practice.

Although I am not familiar with shiki's inner implementation, I believe there exist a stringify step which renders the AST into HTML. What I want is the AST before stringifying.

### Suggested solution

Expose an API to get the highlighted AST, or just return the span lists is useful enough for me.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/eslint-stylistic/eslint-stylistic/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://eslint.style/contribute/guide).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

### Contributes

- [X] If this feature request is accepted, I am willing to submit a PR to fix this issue

**Comment by antfu** [comment]
Did you read the docs? 
https://shiki.style/guide/install#usage
https://shiki.style/guide/transformers#codetohast
