### ISSUE TITLE
Export supported themes + languages as runtime values

### ISSUE THREAD

**Issue by Gerrit0** [shikijs/shiki#84]
As titled, it would be useful to export an array or set of the supported themes and values that don't require custom setup so that they can be easily referred to by calling code. I'd like to use this for TypeDoc to be able to check that a user supplied theme is valid, before getting all the way to the rendering step and dying when shiki tells me it doesn't know what to do with it.

**Comment by octref** [comment]
Sounds good.

**Comment by octref** [comment]
`BUNDLED_THEMES` and `BUNDLED_LANGUAGES` are now exported.
