### ISSUE TITLE
Shiki package structure

### ISSUE THREAD

**Issue by Gerrit0** [shikijs/shiki#844]
I'd like to propose an alternative package structure for Shiki. The main motivation behind this is that it isn't possible to only install the parts of Shiki which are relevant for getting a list of themed tokens.

The pieces of Shiki that I use are:
- Loading grammars/themes (`shiki.createHighlighter`)
- Converting code to tokens (`highlighter.codeToTokensWithThemes`)

Ideally, I'd like to avoid adding an unused dependency on 26 utilities for Shiki's `codeToHtml` and `codeToHast` functions as the functionality is entirely unused. This would remove around a third of my dependency graph.

Thoughts?

**Comment by antfu** [comment]
You can use https://github.com/shikijs/shiki/blob/1da0bc8a12ae2d80f7704aaa3a7246b7c00c9321/packages/core/src/constructors/internal.ts#L14

Everything else should be tree-shakable.

**Comment by Gerrit0** [comment]
Tree shaking isn't relevant for node modules which depend on this -- packages are either entirely in my dependency tree or not

**Comment by antfu** [comment]
In that case we have no interest in making it more granular as we believe it's granular enough. Feel free to fork or rebundle.
