### ISSUE TITLE
Supported languages list is outdated

### ISSUE THREAD

**Issue by Uninen** [shikijs/shiki#85]
Some added languages (at least `jinja-html`) are missing and removed (at least `vue-html`) are still there. This is unfortunate especially for new and potential users.

I recall Simon Willison writing some markdown plugins to do this kind of documentation with a script or maybe the link in the homepage readme could deeplink into the code instead for less manual work?

I'm happy to do a manual PR in the meanwhile if it helps.

**Comment by octref** [comment]
This should happen with each automated themes/languages update. I updated the script to update README as well.
