### ISSUE TITLE
Prisma regression with JS engine

### ISSUE THREAD

**Issue by slevithan** [shikijs/shiki#868]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Prisma just regressed with the JS engine (moving from supported to unsupported), and is throwing "Error: Quantifier requires a repeatable token" via the `report-engine-js` script. Looks like the cause is [this recent addition](https://github.com/shikijs/textmate-grammars-themes/blob/f500671646af78db5e24b9f7b2fc564107ad92b0/packages/tm-grammars/grammars/prisma.json#L371-L375) from commit https://github.com/shikijs/textmate-grammars-themes/commit/f500671646af78db5e24b9f7b2fc564107ad92b0 (upstream PR: https://github.com/prisma/language-tools/pull/1806).

Looks like the addition to the Prisma grammar is meant to be treated as a literal text search (since `*/` is not a valid regex pattern). Should the JS engine be handling this block as literal text searches rather than passing it to the regex engine as regex patterns?

### Reproduction

pnpm run report-engine-js

### Contributes

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by antfu** [comment]
I am curious how Oniguruma handles this. To me this looks like a mistake in their grammar where they should escape it properly

**Comment by slevithan** [comment]
You're right. They've now fixed it in https://github.com/prisma/language-tools/pull/1807 and released the fix in v6.1.0.
