### ISSUE TITLE
Using the JS engine by default

### ISSUE THREAD

**Issue by slevithan** [shikijs/shiki#870]
The latest version of Shiki's JS engine is [robust](https://github.com/shikijs/shiki/blob/main/docs/references/engine-js-compat.md), handling 95% of grammars (99.9% of regexes). The next version of `oniguruma-to-es` will also move Markdown and PO to supported (at minimum, since they're already fully working on `main`). Ada (maybe also Hack) will move to supported after a single invalid Oniguruma regex is fixed upstream [[1]](https://github.com/AdaCore/ada_language_server/issues/1229), [[2]](https://github.com/slackhq/vscode-hack/pull/163). And I've also identified a complex subroutine edge case (Oniguruma subroutines are horrifyingly complex to emulate if you want to cover 100% of edge cases) causing mismatches for Apex. Although it's a really tricky one, I'm optimistic that I'll figure out how to emulate it (with a fair amount of work and special handling in `oniguruma-to-es`'s RegExp subclass).

Not counting other potential improvements (and grammars that might come along for the ride with the Apex fix), supporting the grammars mentioned above would mean 97% of grammars are supported. For people who understand the full depth of Oniguruma's advanced features and crazy edge cases (and JavaScript's limitations), I think this is epic. 😊

Given that the JS engine is about 4% of the size of the WASM engine and roughly performance-neutral (some grammars are faster, some slower), I'm curious what it would take to remove the experimental label and/or make it the default engine.

It's certainly possible to keep grinding away at improving the underlying `oniguruma-to-es` library to add even more support (help would be very welcome). However, it would probably be easier to modify patterns in the remaining unsupported / mismatched grammars to avoid problematic features (like overlapping recursions and some uses of `\G`). That approach would also probably allow more people to help.

What do you think? Is moving to the JS engine as the default the right goal?

**Comment by antfu** [comment]
Yeah I think it's definitely ready to mark as stable, thanks to your hard work! I am still not sure about to have it as the default yet (if we cover 100% then I'd be totally up to it, we could also remove those really-hard-to-support grammars, or change to sources that are more compatible).

My goal is definitely to have Shiki to not coupled with Oniguruma. The separation is almost done, but it's still be bundled in the main entry, that I planned to make them composable/exchangable in the next major.

**Comment by antfu** [comment]
In terms of improving the grammars, do you think we should provide a better toolset for authoring grammars? We can have starter template with a playground that can inspect the state machine and tokens, also would tell if you are using some Oniguruma-specific feature and whether they can be polyfilled by `oniguruma-to-es` etc. This would also make it easier for us to port some grammars for better compatibility/performance.

**Comment by slevithan** [comment]
> Yeah I think it's definitely ready to mark as stable

Cool. I'll make related documentation changes alongside the next `oniguruma-to-es` version bump.

> we could also remove those really-hard-to-support grammars, or change to sources that are more compatible

Nice to have that as an option. E.g., it might be worth removing Razor.

> My goal is definitely to have Shiki to not coupled with Oniguruma. The separation is almost done, but it's still be bundled in the main entry, that I planned to make them composable/exchangable in the next major.

Aside: Would it also be possible to upgrade `vscode-oniguruma` in the next major version? Not sure what you'd have to do for that. Oniguruma cares about backcompat, so the underlying upgrades and bug fixes for regex syntax and behavior that come from upgrading the Oniguruma version are probably minor enough to not change support for any grammars. However, `oniguruma-to-es` is intended to emulate the latest Oniguruma version (I generally test using `vscode-oniguruma` 2.0.1), so it will be nice to not have to worry about edge-case discrepancies coming from Oniguruma itself (or older versions of Unicode used by older Oniguruma). `vscode-oniguruma` 2.0.1 includes Oniguruma 6.9.8, which is one patch removed from the latest version.

> In terms of improving the grammars, do you think we should provide a better toolset for authoring grammars? We can have starter template with a playground that can inspect the state machine and tokens, also would tell if you are using some Oniguruma-specific feature and whether they can be polyfilled by `oniguruma-to-es` etc. This would also make it easier for us to port some grammars for better compatibility/performance.

I think it's a great idea. TM grammar authors need all the help they can get, and if it catches on, it will help ensure future grammars are compatible with Shiki (including its JS engine). It's probably not something I'd be able to take on, though, apart from helping with `oniguruma-to-es` related integration and suggestions. E.g., it would be nice to warn when a regex can be emulated with option `allowUnhandledGAnchors` but not without it, so those regexes can be targeted for refactoring.

**Comment by antfu** [comment]
> Would it also be possible to upgrade vscode-oniguruma in the next major version?

Is there any feature/fix missing with the current version? I see `2.0.1` (which was over one year ago) only changes the wasm from vendoring to building in CI (https://github.com/microsoft/vscode-oniguruma/commit/e51f3e95f2b0d4c9c1f26087694cafbb3b2f7385) - where the new build changes the binding so it would require extra work to adopt. But I see not much to gain for using the new version

**Comment by slevithan** [comment]
Oh, you're right! `vscode-oniguruma` v1.7.0 is the version that bumped Oniguruma to v6.9.8 (https://github.com/microsoft/vscode-oniguruma/commit/ef79edfddbecaf172e20f30710c714b4458aebbe). So v1.7.0 and v2.0.1 are using the same version of Oniguruma. In that case, no worries! Since v1.7.0's `onig.wasm` is slightly smaller (456KB) than in v2.0.1 (463KB), I'd incorrectly assumed it was an earlier version of Oniguruma.

`oniguruma-to-es`'s parsing/emulation includes two bug fixes from Oniguruma 6.9.9, but they're very minor and are not affecting the JS engine compat report. And in any case v6.9.9 is not yet available via any version of `vscode-oniguruma`.

**Comment by slevithan** [comment]
Closing this since you removed the "experimental" label in https://github.com/shikijs/shiki/commit/25695aa743130100d1915dd062187b3db3fcfad2 (released in v1.24.4).

**Comment by slevithan** [comment]
> In terms of improving the grammars, do you think we should provide a better toolset for authoring grammars? We can have starter template with a playground that can inspect the state machine and tokens, also would tell if you are using some Oniguruma-specific feature and whether they can be polyfilled by `oniguruma-to-es` etc. This would also make it easier for us to port some grammars for better compatibility/performance.

@antfu In case you pursue this in the future, an idea that might be interesting is to use @RedCMD's [TmLanguage-Syntax-Highlighter](https://github.com/RedCMD/TmLanguage-Syntax-Highlighter) to highlight TM grammar syntax. RedCMD is also a deep Oniguruma and TM grammar expert who might have additional insights or maybe even be interested/available to collaborate (just throwing it out there, not sure what RedCMD will think!)
