### ISSUE TITLE
HCL with the JavaScript engine causes browser tab freeze due to catastrophic backtracking

### ISSUE THREAD

**Issue by yoavbls** [shikijs/shiki#871]
### Validations

- [X] Follow our [Code of Conduct](https://github.com/shikijs/shiki/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/shikijs/shiki/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

### Describe the bug

Since [this change](https://github.com/hashicorp/syntax/commit/cc2b4d4fe389f14b8a13937f4e0d7b2811b57588#diff-ba9b5e36a521a3f3ebff9d0931598f0515b133934cc75f87e23e3f18dfb23428L79) on HCL tmGrammer almost anything causes HCL snippets on the JavaScript engine freezing the whole tab due to catastrophic backtracking.

I opened an issue about it + a fix here: https://github.com/hashicorp/syntax/issues/164
but until it's merged it would be great if we could make Shiki handle it instead of freezing.

#### optional solutions

1. Pin the grammar JSON file link ([here](https://github.com/shikijs/textmate-grammars-themes/blob/f877f31226a95bb855830eb0a3b3ba0dd71a9d4a/sources-grammars.ts#L650)) to the version before the bug.
I don't see pinned versions of anything there so I'm assuming it's not desirable
2. Fix the bad regex on the generated file ([here](https://github.com/shikijs/textmate-grammars-themes/blob/main/packages/tm-grammars/grammars/hcl.json#L83))
I'm not sure if there is an option to prevent it from overridden

If these or other solutions are acceptable I'll open a PR.
Thanks!

### Reproduction

https://textmate-grammars-themes.netlify.app/?grammar=hcl&theme=github-dark&code=var+%3D+%5B%22Every%22%2C+%22Item%22%2C+%22Slows%22%2C+%22Down%22%2C+%22Everything%22%5D

### Contributes

- [X] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests

**Comment by slevithan** [comment]
The best solution will be for https://github.com/hashicorp/syntax to publish a patch release with the change. Can you ask them to do that? If they do so, it can then be quickly picked up for new `tm-grammars` and Shiki releases.

Up to @antfu if he's okay with you submitting a PR with one of your alternative solutions in the meantime.

@yoavbls can you confirm whether Shiki runs into similar runaway backtracking when using Oniguruma directly via the WASM engine? Presumably yes unless Oniguruma is running some prevention or early-fail strategy that is not built into browser regexp engines.

**Comment by slevithan** [comment]
It might be possible to build protection against runaway backtracking into future versions of Shiki's JS engine (at least when it's running in Node, which has an [API for killing processes](https://stackoverflow.com/questions/50477552/how-can-i-always-terminate-a-nodejs-script-with-a-timeout-even-if-the-event-loop)) but that is beyond the scope of the underlying `oniguruma-to-es` library that I maintain.

Also note that Oniguruma has features for backtracking control like atomic groups and possessive quantifiers, and if you use them, `oniguruma-to-es` knows how to emulate them.

**Comment by yoavbls** [comment]
Thank you! they merged the fix now and it seems like Shiki reference to the updated file [here](https://github.com/shikijs/textmate-grammars-themes/blob/f877f31226a95bb855830eb0a3b3ba0dd71a9d4a/sources-grammars.ts#L650C14-L650C87).

So I think that releasing a new version of Shiki will solve it 🙂

@slevithan about the Oniguruma engine, it seems like the time does go up on every additional word but it's probably not exponentially because it is still super fast even with gigantic and complicated HCL files.
 I assume they do have some kind of protections or limitations against it

**Comment by slevithan** [comment]
> So I think that releasing a new version of Shiki will solve it 🙂

The change first needs to show up in https://github.com/shikijs/textmate-grammars-themes/ and then Shiki's version of `tm-grammars` can be bumped. Feel free to ping me when that happens.

**Comment by slevithan** [comment]
> So I think that releasing a new version of Shiki will solve it 🙂

The change first needs to show up in https://github.com/shikijs/textmate-grammars-themes/ and then Shiki's version of `tm-grammars` can be bumped. Feel free to ping me when that happens.

> about the Oniguruma engine, it seems like the time does go up on every additional word but it's probably not exponentially because it is still super fast even with gigantic and complicated HCL files.

Size and complexity of the file is not relevant, since the thing with exponential backtracking is that it is typically triggered by almost-but-not-quite matching strings. So it is specifically the frequency and length of inputs that trigger the problem that will affect performance.

**Comment by slevithan** [comment]
OK, the HCL grammar fix is now in `tm-grammars` v1.21.9.

@antfu can you publish a new release that includes #872 plus also bumps `tm-grammars`?

**Comment by antfu** [comment]
Thanks! Released as 1.24.4
