### ISSUE TITLE
[feature request] import syntaxes and themes from dependency

### ISSUE THREAD

**Issue by Shigma** [shikijs/shiki#9]
Hi there! shiki is really awesome and thanks for your effort.

I hope syntaxes and themes will be available from dependency so we can make the most of the vast ecosystem of vscode.

Example:
```json
// package.json
{
  "dependencies": {
    "vscode-night-owl": "https://github.com/sdras/night-owl-vscode-theme",
    "vscode-rainbow-csv": "https://github.com/mechatroner/vscode_rainbow_csv"
  }
}
```
```js
shiki.use('vscode-night-owl')
shiki.use('vscode-rainbow-csv')

shiki.getHighlighter({
  theme: 'night-owl'
}).then(highlighter => {
  return highlighter.codeToHtml('foo,bar,baz', 'csv')
})
```

**Comment by octref** [comment]
I added guide for adding a new theme. I don't think we are bundling night-owl, but you can easily add it locally by downloading https://github.com/sdras/night-owl-vscode-theme/blob/master/themes/Night%20Owl-color-theme.json, and then load it with:

```ts
const shiki = require('shiki')

const t = shiki.loadTheme(<PATH-TO-JSON>)

shiki.getHighlighter({
  theme: t
})
```

There's no easy way to access VS Code extension programmatically, so I can't look it up by publisher/id.
